// src/content/ascendant_signs.ts
// Solar Return: Ascendant (Rising Sign) in each of the 12 signs
// Sources: Cafe Astrology Solar Return Ascendant series (Annie Heese);
// Journeys Yearly Solar Return Report (Volguine method);
// Mary Fortier Shea "Planets in Solar Returns" (3rd ed.)
// NOTE: The SR Ascendant describes overall temperament, attitude, and approach
// for the year. It changes every year based on location and time of the SR.
// The ruler of the SR Ascendant and its house position provide additional focus.

export const ASCENDANT_SIGNS: Record<string, string> = {

  Aries: `With Aries rising in your solar return, this is a year of new initiatives, heightened energy, and a powerful drive to act on your own terms. You approach the year with more courage, impatience, and physical vitality than usual — circumstances that once would have given you pause now seem like invitations rather than obstacles. If you have been holding back from making a change, the Aries Ascendant gives you the push to move. You are less inclined to deliberate and more inclined to act, which serves you well when the direction is clear but can lead to impulsive decisions when it is not. Your personal needs take precedence this year, and others may notice that you are more self-directed and less accommodating than usual — this is not selfishness so much as a necessary focusing of energy. Physical activity is important; the Aries rising year often comes with restlessness that genuinely needs an outlet in exercise or movement. Be aware that the increased energy also carries a risk of accidents from acting too quickly without enough awareness of your surroundings. Mars, as ruler of Aries, holds important clues about where the year's primary action and attention will be directed — check its house position for the specific arena of life where this energy is most concentrated.`,

  Taurus: `With Taurus rising in your solar return, the year's tone is one of consolidation, patience, and a deep desire for stability. You approach life more conservatively than usual — you are in no hurry to disrupt what is already working, and you are sceptical of change for its own sake. This can be a strength, providing a steadiness and persistence that allows you to build something durable, or it can become resistance that keeps you stuck in circumstances that genuinely need to shift. Financial matters and material security are prominent in your thinking, and you may work with particular intention to strengthen your income or protect what you have built. Your aesthetic sensibility is heightened — you may feel a stronger-than-usual desire for beauty in your surroundings, your appearance, and your daily experience. There is a quality of attraction to this Ascendant: you draw things toward you through patience and presence rather than aggressive pursuit. The risk is inertia and over-indulgence — Taurus rising can tip into comfort-seeking and resistance to necessary effort. Venus, as ruler of Taurus, indicates in its house position where the year's resources, pleasures, and values will be most engaged.`,

  Gemini: `With Gemini rising in your solar return, the year promises to be busy, varied, and mentally stimulating — possibly to the point of overwhelm. You approach life with heightened curiosity and a desire to sample widely, which opens many doors but can make it difficult to commit fully to any one path. Your attention span may be shorter than usual; projects begun with enthusiasm in the first months of the year may lose their appeal before they reach completion. Communication is central to the year's themes: you are more talkative, more socially engaged, more active in your local environment, and more interested in learning. Short trips, frequent errands, new contacts, and a full schedule of varied activities characterise many Gemini rising solar return years. The nervous system is under more strain than usual, and the risk of anxiety or scattered thinking is real if you do not build in enough rest. In relationships, there may be a quality of instability or indecision — too many options, too much weighing. Mercury's house position reveals which area of life demands the most mental engagement and communication this year.`,

  Cancer: `With Cancer rising in your solar return, your emotional life moves to the foreground. You are more sensitive than usual, more attuned to the moods of those around you, and more invested in the security of your home and family. The year asks you to pay attention to what you feel — not to suppress or analyse emotions before they are even recognised, but to allow them to inform your understanding of what you need and where you belong. Home may become a more significant physical and psychological focus: you may move, renovate, or simply find that the quality of your domestic environment matters more than it has in previous years. Family relationships — with parents, children, or your chosen family — become central. The Moon, ruling Cancer, carries enormous weight as the Ascendant ruler this year; its sign, house, and aspects in the solar return chart will colour the emotional texture of the entire year more specifically. The risk of this Ascendant is excessive defensiveness and a tendency to cling to emotional security at the expense of necessary change. You may also be more susceptible to the moods of those around you and need to be mindful of boundaries. At its best, a Cancer rising year deepens your capacity for care and self-knowledge.`,

  Leo: `With Leo rising in your solar return, you step into the year with a stronger-than-usual desire for recognition, creative expression, and the freedom to be fully yourself. There is a natural magnetism to Leo rising — you are more visible, more dramatic, and more invested in how you present yourself to the world. This can manifest as genuine creative flourishing, a deepening of romantic life, or a leadership role that allows you to express your individual gifts. At its best, a Leo rising year is one in which you make your mark — you create something, lead something, or love something with your whole heart. The risk is ego inflation: the Leo Ascendant craves approval, and if that need goes unexamined, it can push you toward domineering behaviour or an oversensitivity to criticism that makes honest feedback feel like a personal attack. Physical vitality is generally high. Children and romance are often highlighted. The Sun — Leo's ruler and the most significant planet in any solar return chart — holds double importance this year; its house position reveals exactly where you are most called to shine and lead.`,

  Virgo: `With Virgo rising in your solar return, the year is characterised by a strong focus on the practical dimensions of life — work, health, improvement, and a careful attention to how things actually function. You approach the year with more analytical precision than usual, a heightened desire to be useful, and a tendency to notice what needs to be fixed or refined. This can be an extremely productive year for those who are willing to do meticulous, unglamorous work — Virgo rising rewards effort, attention to detail, and genuine service. Health often comes into focus: this is a natural year to establish better daily routines, attend to medical matters, or seriously improve your diet and exercise habits. The risk of this Ascendant is over-analysis and self-criticism — a Virgo rising year can tip into worry, perfectionism, or a tendency to nitpick yourself and others rather than accepting what cannot be controlled. Social life may quiet down as you focus on what needs doing. Mercury's house position points to the area of life receiving the most detailed attention and adjustment this year.`,

  Libra: `With Libra rising in your solar return, relationships, balance, and the need for harmony become the year's defining concerns. You approach life with a stronger-than-usual desire to accommodate, to find the middle ground, and to resolve tensions before they escalate into open conflict. Your social life is likely to be active, and you may find yourself in contexts — personal or professional — that require you to negotiate, mediate, or represent others. A significant partnership of some kind frequently comes into focus with Libra rising, whether through the beginning of a committed relationship, a formal business arrangement, or the deepening or testing of an existing bond. Legal documents and formal agreements may also need attention. The risk of this Ascendant is over-accommodation — the Libra drive for harmony can lead you to avoid necessary confrontation, to give more than is sustainable, or to sacrifice your own position for the sake of keeping the peace. Decision-making may feel more difficult than usual, as you find yourself genuinely weighing competing considerations. Venus's house position reveals where the year's relational energy is most concentrated.`,

  Scorpio: `With Scorpio rising in your solar return, the year takes on an intensity and depth that may feel quite different from your recent experience. You approach life with greater emotional seriousness, a heightened awareness of what is hidden or unspoken, and a willingness to go to places — psychologically, relationally, or professionally — that you might have avoided in gentler years. This is not typically a superficial or easy Ascendant: Scorpio rising years tend to involve confrontations with complexity, power dynamics, and the need for genuine transformation. Psychological work, therapy, and honest self-examination are well-supported. Financial matters involving shared resources — inheritances, joint accounts, debt, taxes, or a partner's finances — may require significant attention. Your perceptions are sharper than usual, and you may find yourself seeing beneath the surface of people and situations with uncomfortable clarity. The risk is that the Scorpio intensity becomes destructive rather than transformative — through jealousy, obsessive thinking, the wielding of power without compassion, or a refusal to release what needs to be let go. Mars or Pluto, as co-rulers of Scorpio, indicate through their house positions where the year's most concentrated power and transformation will be working.`,

  Sagittarius: `With Sagittarius rising in your solar return, the year opens with an expansive, optimistic, and adventurous energy. You approach life with more enthusiasm and a broader perspective than in other years — you are less interested in the details and more interested in the horizon. Travel, whether literal or intellectual, is a recurring theme. You may feel a strong pull toward higher education, philosophical study, religious or spiritual exploration, or encounters with people and cultures quite different from your own. There is a genuine quality of good fortune to Sagittarius rising years: opportunities tend to present themselves, and your natural enthusiasm helps you take advantage of them. Legal matters may require attention and often resolve favourably. The risks are overconfidence, over-commitment, and a tendency to gloss over important practical details in the excitement of the larger vision. You may also feel restless with your existing responsibilities, particularly if they feel limiting. Jupiter's house position tells you specifically where the year's expansion, opportunity, and growth are centred.`,

  Capricorn: `With Capricorn rising in your solar return, the year is defined by seriousness, ambition, and a heightened awareness of responsibility. You approach life with more pragmatism than usual, a strong concern for your professional standing, and a willingness to put in the disciplined effort required to move forward. This is a year to build — to work methodically toward goals that matter, to establish your credibility, and to take on the kind of responsibility that leads to lasting advancement. Authority figures play a significant role in the year's events, either as allies or as sources of friction. The career and public reputation are frequently focal points. The risk of Capricorn rising is an over-identification with achievement — becoming so focused on work and status that emotional life, relationships, and personal pleasure are neglected. You may also be harder on yourself than is warranted, applying Saturn's demanding standards in ways that breed frustration rather than progress. Saturn's house position reveals where the year's most significant tests, lessons, and disciplines are being applied.`,

  Aquarius: `With Aquarius rising in your solar return, the year brings a strong desire for freedom, originality, and a break from whatever has felt constraining about your recent life. You approach the year with more independence and eccentricity than usual — you are less concerned with what others expect of you and more interested in what you genuinely think and want. This can manifest as an exciting year of intellectual liberation and social expansion, with new friendships, group affiliations, and unconventional experiences. Alternatively, it can feel disruptive — a restlessness that makes it difficult to settle, or an impulse to cut ties without fully understanding why. Change is the Aquarius rising constant. The need for personal space is strong, and you may find that close relationships require renegotiation to accommodate the unusual degree of independence you need this year. Humanitarian concerns, technology, and progressive ideas are natural areas of engagement. Uranus's house position identifies where the year's most unexpected changes and breakthroughs will occur.`,

  Pisces: `With Pisces rising in your solar return, the year takes on a more fluid, introspective, and spiritually receptive quality. You approach life with greater sensitivity and a heightened permeability to the emotional atmosphere around you — you pick up on subtleties that others miss, and you may find yourself drawn toward solitude, creative work, and inner life more than outward achievement. This is a year when what happens internally is often more significant than what is visible externally. Spiritual practice, artistic creation, charitable work, and psychological exploration are all supported. A quality of uncertainty or indefiniteness may characterise the year — directions that seemed clear become less so, and it may be difficult to know exactly where you are headed. Some individuals with Pisces rising experience a year of genuine retreat, either chosen or circumstantial. The risks include escapism, difficulty with practical decisions, excessive self-sacrifice, and confusion about what is real. Hidden matters may require attention. Neptune's house position indicates where the year's most subtle, spiritually significant, or potentially confusing energies are operating.`,
};
