// src/content/aspects_mercury.ts
// Solar Return: SR Mercury aspects to other SR planets and Ascendant
// Key format: "mercury_aspect_planet" — all lowercase, e.g. "mercury_conjunction_venus"
// Aspects covered: conjunction, sextile, square, trine, opposition (5 major)
// Planets aspected: Venus, Mars, Jupiter, Saturn, Uranus, Neptune, Pluto, Ascendant
// (Sun–Mercury in aspects_sun.ts, Moon–Mercury in aspects_moon.ts)
// Sources: Mary Fortier Shea "Planets in Solar Returns" (3rd ed.) — primary;
// Cafe Astrology SR series; Robert Hand "Planets in Transit"
// Entries: 3-4 sentences

export const ASPECTS_MERCURY: Record<string, string> = {

  // MERCURY–VENUS
  mercury_conjunction_venus: `The solar return Mercury conjunct Venus marks a year in which thinking and aesthetic sensibility are in natural alignment — ideas arrive with an instinctive sense of how they should be expressed, and communication carries a quality of genuine elegance and genuine warmth. Writing, speaking, and the articulation of personal vision are supported by a natural grace that makes the work both more pleasurable and more genuinely effective. Social and professional communications tend to go well, and the year favours any endeavour that benefits from the capacity to communicate in ways that are both intellectually clear and genuinely appealing. Creative and artistic projects benefit from the easy cooperation between analytical intelligence and aesthetic instinct.`,

  mercury_sextile_venus: `The solar return Mercury sextile Venus brings a quality of easy communicative warmth, diplomatic grace, and natural aesthetic sensibility to the year's intellectual and social life. Conversations and written communications carry a quality of genuine pleasantness and genuine effectiveness, and the year tends to support social and professional interactions with a quality of natural goodwill. Creative projects benefit from the easy cooperation between thinking and aesthetic feeling, and the year favours any work that requires the capacity to make ideas both clear and genuinely appealing.`,

  mercury_square_venus: `The solar return Mercury square Venus marks a year in which thinking and aesthetic sensibility are in productive but sometimes frustrating tension — the desire to communicate with elegance and warmth may conflict with the analytical precision the situation requires, or the impulse toward diplomatic smoothing may work against the honest intellectual engagement that genuine discourse demands. Creative work may involve the same tension between what is intellectually true and what is aesthetically pleasing. The year benefits from deliberate attention to where honesty and grace are genuinely compatible and where one must take precedence over the other.`,

  mercury_trine_venus: `The solar return Mercury trine Venus brings a quality of natural communicative grace, easy aesthetic intelligence, and genuine warmth in intellectual exchange to the year. Writing and speaking carry a quality of both precision and genuine appeal, and the year tends to support creative, social, and professional communications with a quality of natural effectiveness and genuine pleasantness. Artistic and creative projects benefit from the easy cooperation between analytical intelligence and aesthetic sensibility that this aspect consistently provides. The year is well-suited to any work that requires the capacity to make complex ideas both clear and genuinely beautiful.`,

  mercury_opposition_venus: `The solar return Mercury opposite Venus marks a year in which the demands of honest intellectual communication and the desire for social warmth and aesthetic grace are in visible tension — saying what is actually true and saying it in a way that preserves harmony and aesthetic quality may feel genuinely incompatible at times. The year may involve situations in which intellectual honesty and relational diplomacy pull in different directions, requiring conscious choice about which to honour in any given context. Creative work benefits from the recognition that genuine tension between truth and beauty can produce more interesting results than either comfort alone.`,

  // MERCURY–MARS
  mercury_conjunction_mars: `The solar return Mercury conjunct Mars marks a year of sharp, assertive, and sometimes combative intellectual energy — the mind moves quickly, arguments are made with force and conviction, and the impulse to defend a position or challenge an opposing one is unusually strong. Writing and speaking carry more urgency and more edge than in other years, and the year favours work that benefits from genuine intellectual courage and the willingness to say what is true without excessive diplomatic softening. The risk is the tendency to think and speak more sharply than the situation requires, generating unnecessary opposition through the force of communication rather than the quality of the ideas being communicated.`,

  mercury_sextile_mars: `The solar return Mercury sextile Mars brings a quality of sharp intellectual confidence, productive assertiveness in communication, and genuine mental energy and drive to the year. Ideas are pursued with more conviction and more effective force than in other years, and the year tends to support any work requiring both analytical intelligence and the willingness to act decisively on what the mind concludes. Writing and speaking are more energised and more genuinely persuasive, and debates and intellectual negotiations tend to go well when engaged with both confidence and genuine preparation.`,

  mercury_square_mars: `The solar return Mercury square Mars marks a year of genuine tension between thinking and action — the mind and the drive are in conflict in ways that can produce both exceptional intellectual urgency and a tendency toward argumentativeness, impulsive communication, and the premature assertion of positions that would benefit from more careful development. Debates and negotiations may be more confrontational than productive, and the impulse to communicate with force may generate opposition that the quality of the underlying ideas would not have produced. The year benefits most from deliberate slowing of the impulse from thought to speech.`,

  mercury_trine_mars: `The solar return Mercury trine Mars brings a quality of sharp, well-directed intellectual energy, confident and effective communication, and genuine productive alignment between thinking and action to the year. Ideas are pursued with conviction and executed with decisiveness, and the year tends to support any work requiring both analytical precision and the courage to act on what the mind concludes without excessive second-guessing. Writing and speaking are energised and genuinely persuasive, and the year is well-suited to intellectual work that requires both careful thinking and the willingness to defend its conclusions.`,

  mercury_opposition_mars: `The solar return Mercury opposite Mars marks a year in which the most forceful intellectual challenges and the sharpest arguments arrive through others — debates, negotiations, and the intellectual opposition of significant colleagues, partners, or institutions require genuine mental agility and genuine willingness to stand behind what you actually think. The year tends to sharpen intellectual clarity through genuine opposition rather than through comfortable agreement, and the positions that survive the year's debates tend to be more genuinely solid than those that were never seriously challenged. The risk is reactive argumentativeness that substitutes heat for genuine intellectual engagement.`,

  // MERCURY–JUPITER
  mercury_conjunction_jupiter: `The solar return Mercury conjunct Jupiter marks a year of exceptional intellectual expansiveness, philosophical breadth, and a genuine quality of wide-ranging curiosity and optimistic intellectual confidence. The mind reaches further than usual — across more subjects, toward more ambitious intellectual projects, and with more genuine conviction in the significance of what is being thought and communicated. Writing and publishing benefit from a quality of genuine vision and broad appeal. The risk is the overconfidence and the tendency toward overpromising that Jupiter always introduces — the year is most productive when expansive intellectual ambition is paired with honest attention to the accuracy of the supporting details.`,

  mercury_sextile_jupiter: `The solar return Mercury sextile Jupiter brings a quality of easy intellectual expansiveness, philosophical warmth, and genuine optimism in thinking and communication to the year. The mind is broader and more generously engaged than in more narrowly focused years, and the year tends to support intellectual projects and communications with a quality of natural forward momentum and genuine appeal. Writing benefits from a quality of both clarity and genuine aspiration, and the year favours any intellectual work that benefits from the willingness to think and communicate on a genuinely significant scale.`,

  mercury_square_jupiter: `The solar return Mercury square Jupiter marks a year in which intellectual ambition and the realistic assessment of what can actually be communicated and completed are in genuine tension — the mind reaches toward more than the year can fully deliver, and the gap between ambitious intellectual vision and disciplined execution requires honest attention. Over-promising in writing and communication, intellectual overconfidence, and the tendency to think in broad strokes while neglecting the accuracy of the underlying detail are characteristic risks. The year is most productive when genuine intellectual ambition is paired with honest and regular reality-checking.`,

  mercury_trine_jupiter: `The solar return Mercury trine Jupiter brings exceptional intellectual expansiveness, genuine philosophical confidence, and a quality of broad and genuinely appealing communication to the year. Writing and intellectual projects benefit from the natural alignment between analytical intelligence and the larger vision that Jupiter always provides, and the year tends to support any communicative endeavour that aspires to genuine significance and broad reach. The year is well-suited to publishing, teaching, and the communication of ideas that are both carefully reasoned and genuinely inspiring. What is thought and written under this aspect tends to carry more weight and more genuine reach than in more narrowly focused years.`,

  mercury_opposition_jupiter: `The solar return Mercury opposite Jupiter marks a year in which intellectual expansiveness and the broader philosophical vision that Jupiter provides arrive primarily through others — teachers, significant interlocutors, or the ideas encountered through travel and broad intellectual engagement challenge and enlarge the thinking in ways that solo intellectual effort would not produce. The year benefits from genuine openness to perspectives significantly larger than your current framework, and from the recognition that the most significant intellectual development of the year may arrive through genuine dialogue rather than through private reflection alone.`,

  // MERCURY–SATURN
  mercury_conjunction_saturn: `The solar return Mercury conjunct Saturn marks a year of serious, disciplined, and sometimes laborious intellectual work — the mind is more exacting and more self-critical than in other years, and the standard to which thinking and communication are held is unusually high. Writing proceeds more slowly and with more genuine rigour, and the critical faculty is more active than the generative one. What is produced through this year's intellectual discipline tends to be more genuinely solid and more lastingly valuable than what comes more easily in other years — Saturn in contact with Mercury always asks whether what is being thought and said is genuinely true and genuinely worth saying. The year is well-suited to serious long-term intellectual projects that benefit from sustained precision.`,

  mercury_sextile_saturn: `The solar return Mercury sextile Saturn brings a quality of disciplined intellectual focus, honest self-assessment in thinking and communication, and genuine productive rigour to the year without the heaviness and constriction of stronger Saturn contacts. The mind is more structured and more reliably precise than in other years, and any work requiring sustained analytical attention and the careful management of complex information is strongly supported. Writing and intellectual projects benefit from a quality of genuine solidity and honest self-editing that more fluent years do not always produce.`,

  mercury_square_saturn: `The solar return Mercury square Saturn marks a year of genuine tension between intellectual freedom and the demanding standards of rigour and precision that Saturn always imposes — ideas may feel blocked, communication more effortful than usual, and the critical faculty may work against productive intellectual engagement through excessive self-doubt or the premature rejection of genuinely worthwhile thinking. The year is not designed for intellectual ease — it is designed for the kind of honest reckoning with the quality and honesty of one's thinking that only Saturn's friction reliably produces. What survives the year's intellectual discipline tends to be genuinely worth keeping.`,

  mercury_trine_saturn: `The solar return Mercury trine Saturn brings a quality of disciplined intellectual authority, grounded precision, and genuine reliability in thinking and communication to the year. The mind is more carefully structured and more honestly self-critical than in other years, and the work produced under this influence carries a quality of genuine solidity and careful craftsmanship. Writing, research, and any intellectual work that requires sustained precision and honest self-assessment are strongly supported. The year is well-suited to the completion of long-term intellectual projects and to the communication of complex ideas with both genuine clarity and genuine authority.`,

  mercury_opposition_saturn: `The solar return Mercury opposite Saturn marks a year in which the most demanding intellectual standards and the most rigorous critical assessment arrive through others — editors, teachers, authority figures, or the critical reception of the world impose standards of precision and accountability that feel externally demanding but that are ultimately asking the most important question about the quality and honesty of what is being thought and communicated. The year tends to produce more genuinely solid intellectual work in those who engage honestly with the external standards being imposed rather than resisting them as unreasonable.`,

  // MERCURY–URANUS
  mercury_conjunction_uranus: `The solar return Mercury conjunct Uranus marks a year of exceptional intellectual originality, sudden brilliant insight, and a quality of electric mental speed that makes conventional or linear thinking feel genuinely insufficient. The mind operates at its most innovative and most unpredictable — ideas arrive in flashes, connections between apparently unrelated subjects become suddenly visible, and the impulse to follow a genuinely new intellectual direction wherever it leads is unusually strong and unusually productive. The risk is that the pace of ideation exceeds the capacity for careful development and clear communication — the year benefits from structures that allow Uranus's genuine brilliance to be captured before it moves on.`,

  mercury_sextile_uranus: `The solar return Mercury sextile Uranus brings a quality of productive intellectual originality, genuine openness to unconventional ideas, and creative mental flexibility to the year without the destabilising unpredictability of stronger Uranus contacts. New intellectual directions, innovative approaches to established problems, and the willingness to think in genuinely new ways are supported with a quality of easy forward momentum. The year favours any intellectual or communicative work that benefits from genuine originality and the willingness to depart from the expected without requiring the departure to be entirely comfortable.`,

  mercury_square_uranus: `The solar return Mercury square Uranus marks a year in which intellectual disruption and the demand for genuinely new thinking arrive in ways that feel less like liberation and more like genuine instability — the established frameworks through which experience has been understood are disrupted before the new ones are fully available, creating a period of genuine intellectual uncertainty. Communications may be erratic, and the tendency to announce before fully understanding, or to commit intellectually before the thinking is genuinely complete, is a characteristic risk. The year benefits from both genuine openness to the new and enough structural grounding to distinguish productive innovation from mere restlessness.`,

  mercury_trine_uranus: `The solar return Mercury trine Uranus brings a quality of genuine intellectual originality, creative mental agility, and productive openness to genuinely new thinking to the year with enough ease that innovation feels exciting rather than destabilising. The mind is at its most inventive and most genuinely interesting, and the year tends to support intellectual and communicative work that breaks new ground with a quality of natural confidence and genuine effectiveness. The year is well-suited to any intellectual endeavour that benefits from the willingness to think in ways that haven't been tried and to communicate ideas that haven't yet found their audience.`,

  mercury_opposition_uranus: `The solar return Mercury opposite Uranus marks a year in which the most disruptive and most genuinely original intellectual challenges arrive through others — conversations, debates, or the ideas encountered through significant intellectual relationships introduce thinking that is genuinely destabilising to established frameworks and that requires real intellectual flexibility to genuinely engage with rather than simply defend against. The year tends to produce more genuinely innovative thinking in those willing to allow others' ideas to actually change what they think, rather than simply sharpening existing positions through the friction of opposition.`,

  // MERCURY–NEPTUNE
  mercury_conjunction_neptune: `The solar return Mercury conjunct Neptune marks a year in which the clarity of ordinary rational thinking is dissolved in Neptune's boundary-dissolving influence — the mind becomes more imaginative, more intuitive, and more symbolically receptive, while simultaneously becoming less reliable for purely logical or factual tasks. Creative writing, poetry, and any intellectual work that proceeds through image and metaphor rather than argument and analysis are genuinely inspired and genuinely productive. The risk is the confusion of what is brilliantly imagined with what is actually true — the year benefits from both Neptune's genuine creative inspiration and a deliberate commitment to verifying what the imagination produces against external reality.`,

  mercury_sextile_neptune: `The solar return Mercury sextile Neptune brings a quality of heightened creative imagination, genuine intuitive intelligence, and poetic sensitivity to the year's intellectual life without the dissolving confusion of stronger Neptune contacts. Creative and artistic writing benefits from a genuine quality of inspiration and emotional resonance, and intuition is reliable when consulted honestly rather than wishfully. The year favours intellectual work that draws on both analytical precision and imaginative depth, and communications carry a quality of genuine resonance that purely rational approaches do not always achieve.`,

  mercury_square_neptune: `The solar return Mercury square Neptune marks a year in which intellectual clarity is genuinely difficult to maintain — the boundary between what is actually known and what is merely imagined, hoped for, or unconsciously wished for is more permeable than usual, and the tendency toward self-deception in thinking and communication is a characteristic and genuinely demanding challenge. Information received this year may be less reliable than it appears, and the impulse to communicate before the thinking is genuinely clear may produce misunderstandings with consequences that are difficult to undo. The year benefits from deliberate factual grounding and honest external verification of what the imagination is producing.`,

  mercury_trine_neptune: `The solar return Mercury trine Neptune brings a quality of genuine creative inspiration, poetic sensitivity, and intuitive intellectual depth to the year with enough ease that Neptune's gifts are more available than its risks. Creative and artistic writing is naturally inspired, intuition is reliable and genuinely productive, and the capacity to perceive and articulate what lies beneath the surface of ordinary experience is at its most fully and most naturally available. The year is well-suited to creative projects, spiritual writing, and any intellectual work that benefits from the willingness to think and communicate beyond the purely literal and the purely rational.`,

  mercury_opposition_neptune: `The solar return Mercury opposite Neptune marks a year in which the dissolving, idealising quality of Neptune arrives primarily through what others communicate — information received from significant others or from the broader environment may be less than fully honest, and the temptation to hear what you wish to hear rather than what is actually being said is unusually strong. The year benefits from deliberate factual verification of important information and from the honest recognition that the most beautiful version of what is being communicated is not necessarily the most accurate one.`,

  // MERCURY–PLUTO
  mercury_conjunction_pluto: `The solar return Mercury conjunct Pluto marks a year of penetrating, compulsive, and sometimes obsessive intellectual intensity — the mind goes deep rather than wide, pursuing the hidden structure beneath apparent surfaces with a thoroughness and a driven quality that ordinary intellectual curiosity does not produce. Research, investigation, psychological insight, and any intellectual work that requires going beneath what is conventionally acknowledged to what is actually true are all strongly supported and strongly driven. Communication carries more weight and more consequence than in other years — what is said this year tends to be said with a force and a finality that requires genuine care about what is actually being communicated.`,

  mercury_sextile_pluto: `The solar return Mercury sextile Pluto brings a quality of penetrating intellectual depth, genuine psychological insight, and productive investigative thoroughness to the year without the obsessive intensity of stronger Pluto contacts. The mind is more willing and more able to go beneath the surface of things and to engage honestly with what is actually operating rather than what is conventionally presented. Research and investigation are strongly supported, and communications carry a quality of genuine depth and genuine consequence that more surface-level intellectual years do not produce.`,

  mercury_square_pluto: `The solar return Mercury square Pluto marks a year of genuine tension between intellectual honesty and the compulsive pressure of what the mind most urgently wants to be true — the drive to investigate and to get beneath the surface is strong, but the intensity of Pluto's influence can make it difficult to distinguish genuine intellectual penetration from the compulsive pursuit of a conclusion that was determined before the investigation began. Power dynamics in communications and intellectual relationships may be more intense and more honestly demanding of attention than in other years. The year benefits most from intellectual honesty about the difference between genuine investigation and motivated reasoning.`,

  mercury_trine_pluto: `The solar return Mercury trine Pluto brings a quality of genuine intellectual depth, penetrating analytical power, and natural investigative thoroughness to the year. The mind is most productive when engaged with what is genuinely complex, genuinely hidden, or genuinely important rather than what is merely interesting, and the year tends to support research, psychological insight, and any intellectual work requiring the willingness to go all the way down with a quality of natural effectiveness and genuine authority. Communications carry more weight and more genuine consequence than in more intellectually comfortable years.`,

  mercury_opposition_pluto: `The solar return Mercury opposite Pluto marks a year in which the most intense and most penetrating intellectual challenges arrive through others — significant interlocutors, authority figures, or the intellectual opposition of the broader world force a confrontation with the depth and the honesty of what you actually think and actually know. The year tends to strip away the comfortable intellectual positions that have not been genuinely tested and to reveal what is more deeply and more honestly held. Power dynamics in communications and intellectual relationships require honest attention rather than defensive management.`,

  // MERCURY–ASCENDANT
  mercury_conjunction_ascendant: `The solar return Mercury conjunct the Ascendant places the year's intellectual energy and communicative drive directly on the surface of how you meet the world — you are more verbally present, more intellectually engaged in every situation, and more naturally inclined to think and communicate in real time than in years when Mercury is more withdrawn. Others experience you as sharper, more articulate, and more intellectually alive than usual, and the year tends to bring intellectual themes directly into the foreground of personal and professional life. Writing, teaching, and any work that benefits from genuine communicative presence are strongly supported.`,

  mercury_sextile_ascendant: `The solar return Mercury sextile the Ascendant brings a quality of easy communicative confidence, natural intellectual presence, and genuine effectiveness in how you think and express yourself in the world. Others tend to find you more articulate and more genuinely interesting than usual, and the year tends to support intellectual and communicative work with a quality of easy natural effectiveness. The year favours any endeavour that benefits from the capacity to think clearly in real-time social and professional situations and to communicate what you think with both precision and genuine appeal.`,

  mercury_square_ascendant: `The solar return Mercury square the Ascendant marks a year in which there is genuine tension between your intellectual life and the way you are perceived and received in the world — what you are thinking and what is being heard may be in more significant misalignment than in other years, and the effort to communicate clearly across that gap is more demanding than Mercury's natural fluency usually requires. The year benefits from deliberate attention to how ideas are being received rather than simply how they are being expressed, and from the willingness to revise the approach when the gap between intention and reception becomes genuinely consequential.`,

  mercury_trine_ascendant: `The solar return Mercury trine the Ascendant brings a quality of natural communicative authority, easy intellectual presence, and genuine effectiveness in how thinking and self-expression meet the world to the year. What you think and how you come across are in natural alignment, and the year tends to support intellectual and communicative work with a quality of ease and genuine impact. Writing, teaching, public speaking, and any work that requires the capacity to think clearly and communicate effectively in the full presence of others are particularly well-supported and genuinely rewarding.`,

  mercury_opposition_ascendant: `The solar return Mercury opposite the Ascendant — conjunct the Descendant — marks a year in which intellectual life and communicative development proceed primarily through significant one-to-one relationships rather than through private reflection or solo intellectual effort. The most productive thinking of the year tends to happen in genuine dialogue — through conversations with significant others that challenge, enlarge, and honestly refine what you think. The year strongly favours intellectual partnerships, mentorship relationships, and any collaborative intellectual endeavour that benefits from the productive friction of genuine dialogue.`,
};
