// src/content/aspects_venus.ts
// Solar Return: SR Venus aspects to other SR planets and Ascendant
// Key format: "venus_aspect_planet" — all lowercase, e.g. "venus_conjunction_mars"
// Aspects covered: conjunction, sextile, square, trine, opposition (5 major)
// Planets aspected: Mars, Jupiter, Saturn, Uranus, Neptune, Pluto, Ascendant
// (Sun–Venus in aspects_sun.ts, Moon–Venus in aspects_moon.ts,
//  Mercury–Venus in aspects_mercury.ts)
// Sources: Mary Fortier Shea "Planets in Solar Returns" (3rd ed.) — primary;
// Cafe Astrology SR series; Robert Hand "Planets in Transit"
// Entries: 3-4 sentences

export const ASPECTS_VENUS: Record<string, string> = {

  // VENUS–MARS
  venus_conjunction_mars: `The solar return Venus conjunct Mars marks a year of exceptional romantic and creative vitality — the desire for genuine connection, pleasure, and beauty is fused with the drive to pursue and act on what is wanted, producing a quality of passionate engagement with both relationships and creative work that is genuinely alive and genuinely compelling. Romantic life is intensified, and the line between attraction and pursuit is unusually short. Creative work benefits from the fusion of aesthetic sensitivity and the drive to make rather than merely appreciate. The risk is impulsiveness in romantic and creative choices — the intensity of this aspect is most productively directed when paired with enough self-awareness to distinguish genuine passion from mere urgency.`,

  venus_sextile_mars: `The solar return Venus sextile Mars brings a quality of easy creative vitality, warm personal confidence, and productive alignment between the desire for beauty and connection and the drive to pursue what is genuinely wanted. Romantic life is more energised and more genuinely alive than in more passive years, and creative work benefits from the easy cooperation between aesthetic sensitivity and the motivated drive to actually make something. The year tends to reward those who act on genuine attraction and genuine creative inspiration with enough confidence to follow through without excessive hedging.`,

  venus_square_mars: `The solar return Venus square Mars marks a year of genuine tension between the desire for harmony, beauty, and genuine connection and the drive to assert, pursue, and compete — what you want from relationships and what your personal drive is pushing you toward may be genuinely at odds in ways that produce both passionate creative and romantic energy and genuine friction in the most significant relationships. The impulse to pursue what is wanted may override the relational sensitivity that genuine connection requires, or the desire for harmony may suppress the honest assertion that genuine intimacy demands. The year benefits from honest attention to where these competing impulses are actually in conflict.`,

  venus_trine_mars: `The solar return Venus trine Mars is one of the most creatively and romantically vital aspect patterns in a solar return, bringing a quality of passionate engagement, genuine creative drive, and warm personal confidence to the year with enough ease that the energy is more naturally productive than in more contentious years. Romantic life is genuinely alive and genuinely rewarding for those who engage actively with what the year makes available. Creative work benefits from the natural alignment between aesthetic sensitivity and the motivated drive to bring what is envisioned into actual existence. Physical vitality and personal magnetism are both heightened.`,

  venus_opposition_mars: `The solar return Venus opposite Mars marks a year in which the tension between the desire for harmony and connection and the drive to assert and pursue arrives primarily through significant others — partners, collaborators, or the romantic world in general may push against the boundaries of what is comfortable in ways that require genuine negotiation between personal desire and relational sensitivity. Creative partnerships may involve the same productive friction. The year tends to produce more genuinely honest and more genuinely passionate relationships in those willing to engage with the tension directly rather than simply managing it from a comfortable distance.`,

  // VENUS–JUPITER
  venus_conjunction_jupiter: `The solar return Venus conjunct Jupiter is one of the most personally pleasant and broadly fortunate aspect patterns in a solar return, bringing genuine warmth, expansive goodwill, and a quality of easy social and romantic grace to the year that tends to attract genuinely good things and genuinely good people. Relationships benefit from a quality of generous mutual appreciation, and the year has an overall quality of ease and genuine good fortune in the personal and creative domains. The risk — as with all Venus–Jupiter contacts — is excess and overindulgence: the warmth and abundance of this aspect can shade into over-commitment, over-spending, and the comfortable avoidance of necessary limits.`,

  venus_sextile_jupiter: `The solar return Venus sextile Jupiter brings a quality of easy social warmth, genuine good fortune in relationships, and productive expansiveness in creative and aesthetic life to the year. The year tends to bring pleasant and sometimes genuinely rewarding social, romantic, and creative developments without the dramatic intensity of the conjunction, and has an overall quality of genuine goodwill and easy abundance. Creative projects benefit from a quality of natural confidence and genuine appeal, and relationships benefit from the warmth and generosity that Jupiter always brings to Venus's domain.`,

  venus_square_jupiter: `The solar return Venus square Jupiter marks a year in which the desire for abundance in relationships, pleasure, and creative life exceeds what is actually sustainable — the generous impulse toward more beauty, more connection, more creative expansiveness runs ahead of what the practical circumstances of the year can actually support. Over-spending on aesthetic pleasures, over-commitment in relationships, and the tendency to promise more warmth and more generosity than can be consistently delivered are characteristic risks. The year is most rewarding when Jupiter's genuine expansiveness is paired with honest assessment of what is actually available to give.`,

  venus_trine_jupiter: `The solar return Venus trine Jupiter brings genuine warmth, social grace, and easy creative abundance to the year with a quality of natural good fortune that makes the personal and creative domains more rewarding than in most years. Relationships are more harmonious and more genuinely pleasurable, creative and aesthetic work comes more easily and is more genuinely appealing, and the year has an overall quality of comfortable abundance and genuine goodwill. The risk — as with all easy Jupiter aspects — is that comfort shades into complacency and the year's considerable gifts go undeveloped for want of the urgency that more challenging years provide.`,

  venus_opposition_jupiter: `The solar return Venus opposite Jupiter marks a year in which the most generous and most expansive relational and creative opportunities arrive primarily through others — partners, collaborators, or the broader social world bring the abundance and genuine good fortune that Jupiter promises, but the opposition means those gifts require genuine reciprocal engagement rather than passive reception. Over-reliance on others' generosity, or over-extension in response to others' enthusiasm for what you can offer, are the characteristic risks to navigate honestly.`,

  // VENUS–SATURN
  venus_conjunction_saturn: `The solar return Venus conjunct Saturn marks a year in which relationships and creative work are under Saturn's full disciplinary weight — love must be earned rather than simply felt, beauty must be achieved through genuine discipline rather than natural grace, and the most significant relationships of the year carry a quality of weight and obligation that warmer years do not produce. New relationships formed under this aspect tend to be serious and deliberately chosen, often involving age difference or significant practical considerations. What is built in relationships and creative work under this influence tends to be more genuinely solid and more lastingly real than what comes more easily — Saturn always asks whether what is being valued is genuinely worth valuing.`,

  venus_sextile_saturn: `The solar return Venus sextile Saturn brings a quality of genuine loyalty, patient relational commitment, and honest aesthetic discipline to the year without the austerity and constriction of stronger Saturn contacts. Relationships benefit from a quality of honest and patient engagement that is more reliably sustaining than warmer but less grounded relational styles, and creative work benefits from the willingness to apply genuine discipline to the pursuit of genuine quality. The year rewards those who bring both genuine feeling and genuine commitment to what they are building in their relational and creative lives.`,

  venus_square_saturn: `The solar return Venus square Saturn marks a year of genuine tension between the desire for warmth, connection, and creative pleasure and Saturn's demands for discipline, limitation, and honest reckoning with what is genuinely sustainable and genuinely real. Relationships may feel more demanding and less effortlessly rewarding than in other years, and creative work may require more sustained effort and more honest self-criticism than comes naturally. The year is not designed for relational or creative ease — it is designed for the kind of honest assessment of what is genuinely worth building that only Saturn's friction reliably produces.`,

  venus_trine_saturn: `The solar return Venus trine Saturn brings a quality of genuine relational loyalty, disciplined creative commitment, and the particular warmth that comes from feeling genuinely grounded and genuinely accountable in both love and creative work. Relationships benefit from a quality of honest and patient engagement that is more sustainably nourishing than the warmer but less tested relational styles of other years. Creative and aesthetic work benefits from the genuine discipline and honest self-assessment that this aspect brings, producing work of genuine solidity and lasting quality rather than charming but ephemeral brilliance.`,

  venus_opposition_saturn: `The solar return Venus opposite Saturn marks a year in which the most demanding relational and creative standards arrive through others — significant partners, critics, or the practical demands of the external world impose constraints and expectations that feel cold and limiting but that are ultimately asking the most honest questions about the depth and genuineness of what you are offering in your relationships and your creative work. What survives Saturn's opposition in the relational and creative life tends to be what is most genuinely solid — both in the quality of your love and in the quality of what you are making.`,

  // VENUS–URANUS
  venus_conjunction_uranus: `The solar return Venus conjunct Uranus marks a year of sudden, electric, and sometimes destabilising change in relationships and creative life — attractions arrive unexpectedly and are often genuinely unconventional, the need for personal freedom within relationships is at its most urgent, and the established aesthetic and relational patterns of the life are disrupted by the impulse toward something more authentic and more genuinely alive. New relationships formed under this aspect tend to be exciting and unconventional, beginning suddenly and sometimes ending with equal suddenness. Creative work benefits from a quality of genuine originality and the willingness to depart from established aesthetic frameworks in ways that produce genuinely new results.`,

  venus_sextile_uranus: `The solar return Venus sextile Uranus brings a quality of creative originality, productive openness to new relational experiences, and genuine freshness in both aesthetic sensibility and the way connection is approached to the year without the destabilising intensity of stronger Uranus contacts. New and unconventional connections may arrive pleasantly, and existing relationships benefit from a quality of renewed interest and genuine freshness. Creative and aesthetic work is more innovative and more genuinely interesting than in more settled years, and the year favours those willing to depart from the established in favour of the genuinely new.`,

  venus_square_uranus: `The solar return Venus square Uranus marks a year of genuine tension between the desire for relational stability and the impulse toward personal freedom and unexpected change — what you want from relationships and what Uranus is insisting on in terms of liberation and authenticity are pulling in directions that cannot easily be reconciled without disruption to what is currently settled. Existing relationships may be subject to unexpected strain, and new attractions may arrive in inconvenient forms. Creative work benefits from the productive friction between established aesthetic preference and the impulse toward genuine departure from it.`,

  venus_trine_uranus: `The solar return Venus trine Uranus brings a quality of creative originality, genuine relational freshness, and productive openness to the new and unconventional to the year with enough ease that the departures from established relational and aesthetic patterns feel exciting rather than destabilising. New connections may arrive unexpectedly and prove genuinely significant, and existing relationships benefit from the willingness to engage with each other in genuinely new ways rather than defaulting to the comfortable and familiar. Creative and aesthetic work is at its most inventive and most genuinely alive.`,

  venus_opposition_uranus: `The solar return Venus opposite Uranus marks a year in which the demand for relational freedom and creative originality arrives primarily through others — partners, collaborators, or the unexpected developments that significant relationships produce disrupt the established patterns of connection and aesthetic preference in ways that require genuine flexibility and genuine openness to change. The year tends to surface what in the relational and creative life has been maintained through habit rather than genuine choice, and what follows the disruption tends to be more authentically and more freely chosen than what preceded it.`,

  // VENUS–NEPTUNE
  venus_conjunction_neptune: `The solar return Venus conjunct Neptune marks a year of exceptional romantic idealism, creative inspiration, and the beautiful but potentially deceptive enchantment that Neptune brings to all it touches in Venus's domain. The capacity for deep compassionate love and genuinely inspired aesthetic creation is at its most fully alive, and the year may produce creative and romantic experiences of genuine beauty and genuine significance. The risk is the same idealisation that Neptune always brings to relationship — seeing partners through a lens that emphasises the luminous and dissolves the actual, setting up a disillusionment that is as inevitable as the enchantment that preceded it. The year is most rewarding when genuine spiritual love and honest perception of what is actually there are held together rather than offered as alternatives.`,

  venus_sextile_neptune: `The solar return Venus sextile Neptune brings a quality of heightened aesthetic sensitivity, genuine creative inspiration, and compassionate relational warmth to the year without the overwhelming idealisation of stronger Neptune contacts. Creative and artistic work benefits from a genuine quality of inspiration and emotional depth, and the capacity for compassionate engagement with others is heightened in ways that are genuinely nourishing rather than self-dissolving. Intuition in romantic and aesthetic matters is reliable when consulted honestly, and the year favours creative work of genuine emotional and spiritual resonance.`,

  venus_square_neptune: `The solar return Venus square Neptune marks a year in which clarity about what is actually present in the most significant relationships and creative projects is harder to maintain than usual — the tendency to see what is wished for rather than what is actually there, to hear what is most beautiful rather than what is most true, and to invest more emotional and creative energy than the actual situation warrants are all characteristic and genuinely demanding challenges. The year benefits from grounded external perspective in both romantic and creative matters and from the honest willingness to verify that what appears beautiful is also genuinely real.`,

  venus_trine_neptune: `The solar return Venus trine Neptune brings a quality of genuine creative inspiration, compassionate relational depth, and aesthetic sensitivity to the year with enough ease that Neptune's gifts are more available than its risks. Creative and artistic work is naturally inspired and genuinely moving, the capacity for compassionate love is at its most fully and most generously available, and the year strongly supports any creative or relational endeavour that aspires to genuine beauty and genuine emotional depth. Intuition in aesthetic and romantic matters is reliably productive when followed honestly.`,

  venus_opposition_neptune: `The solar return Venus opposite Neptune marks a year in which the idealising, dissolving quality of Neptune arrives primarily through significant others — partners, creative collaborators, or the broader relational world may not be fully honest about who they are or what they are offering, and the temptation to see what is most beautiful rather than what is actually present is unusually strong. Creative partnerships may involve the same quality of inspired but somewhat evasive promise. The year benefits from honest grounding in what is actually being offered and what is genuinely available rather than what the imagination most wants to find.`,

  // VENUS–PLUTO
  venus_conjunction_pluto: `The solar return Venus conjunct Pluto marks a year of deep, compulsive, and sometimes overwhelming intensity in the domains of love, creative work, and the pursuit of what is genuinely beautiful and genuinely desired. Attractions are powerful and sometimes destabilising — what draws you this year draws you with a force that is difficult to manage and ultimately unproductive to resist, and the relationships that matter carry a transformative weight that lighter years do not produce. Creative work is driven by the same compulsive intensity, and the results — when the drive is genuinely engaged — tend to carry more depth and more genuine power than what is produced in more comfortable creative years. The risk is obsessive attachment and the confusion of intensity with depth.`,

  venus_sextile_pluto: `The solar return Venus sextile Pluto brings a quality of genuine relational depth, transformative creative power, and productive engagement with the more intense dimensions of love and aesthetic experience to the year without the overwhelming compulsiveness of stronger Pluto contacts. Relationships carry more genuine depth and more honest psychological transparency than in other years, and creative work benefits from the willingness to engage with what is genuinely intense and genuinely true rather than what is merely pretty or pleasant. The year rewards those willing to bring real depth to both their loving and their making.`,

  venus_square_pluto: `The solar return Venus square Pluto marks a year of genuine tension between the desire for relational warmth and beauty and the compulsive pressure of Pluto's transformative intensity — power dynamics in significant relationships may be more intense and more honestly demanding of attention than in other years, and the line between genuine passionate engagement and compulsive attachment is more difficult to maintain clearly. Creative work involves the same tension between what is aesthetically pleasing and what is genuinely, sometimes uncomfortably true. The year benefits from honest attention to where intensity is serving genuine depth and where it is simply serving compulsion.`,

  venus_trine_pluto: `The solar return Venus trine Pluto brings a quality of genuine relational depth, transformative creative power, and the particular authority that comes from engaging with love and beauty at full depth to the year. Relationships carry more genuine intimacy and more honest psychological transparency than in more surface-level years, and creative work benefits from the willingness to go beneath the merely decorative to what is genuinely and powerfully true. The year is well-suited to significant creative projects of genuine depth, the deepening of relationships that are genuinely worth deepening, and any endeavour that benefits from the capacity to operate from genuine creative and relational intensity.`,

  venus_opposition_pluto: `The solar return Venus opposite Pluto marks a year in which the most intense and most transformative relational and creative dynamics arrive through others — significant partners, collaborators, or the broader relational world impose a quality of compulsive depth and transformative pressure that requires genuine courage and genuine honesty to navigate. Power struggles in significant relationships may be unavoidable, and the year tends to surface the most honest questions about what genuine love and genuine creative investment actually require and what they are genuinely worth. What survives Pluto's opposition in the relational life tends to be more deeply and more honestly real than what preceded it.`,

  // VENUS–ASCENDANT
  venus_conjunction_ascendant: `The solar return Venus conjunct the Ascendant places the year's aesthetic sensibility, social grace, and capacity for genuine warmth and connection directly on the surface of how you meet the world — you are more personally appealing, more naturally charming, and more genuinely present to the aesthetic and relational dimensions of every situation than in years when Venus is more withdrawn. Others respond to you with more warmth and more genuine goodwill than usual, and the year tends to bring pleasant and sometimes genuinely significant social, romantic, and creative developments. The year is well-suited to any endeavour that benefits from genuine personal appeal and the capacity to make others feel genuinely seen and genuinely valued.`,

  venus_sextile_ascendant: `The solar return Venus sextile the Ascendant brings a quality of easy social grace, genuine personal warmth, and natural aesthetic appeal to the way you meet the world and the people in it. Others tend to find you more genuinely pleasant and more naturally appealing than in other years, and the year tends to support social and professional interactions with a quality of easy goodwill and genuine warmth. Creative and aesthetic sensibility is heightened in ways that are naturally productive and personally pleasing, and the year rewards those who actively appreciate and engage with what is most genuinely beautiful and most genuinely sustaining in their lives.`,

  venus_square_ascendant: `The solar return Venus square the Ascendant marks a year in which there is genuine tension between your aesthetic sensibility and relational warmth and the way you are perceived and received in the world — what you feel and what you are offering may not be landing with others in the way you intend, and the gap between the warmth and beauty you are bringing and what others are actually receiving requires honest attention. Social and creative situations may involve more friction than the genuine goodwill you are extending would seem to warrant. The year benefits from deliberate attention to the gap between intention and reception rather than simply persisting with an approach that is not quite connecting.`,

  venus_trine_ascendant: `The solar return Venus trine the Ascendant brings a quality of natural personal charm, easy aesthetic grace, and genuine warmth in the way you meet the world to the year. Who you are and how you come across are in natural alignment in the most personally appealing sense — others experience you as more genuinely warm, more naturally appealing, and more authentically present than in other years. Social, romantic, and creative opportunities arise with a quality of easy natural momentum, and the year is well-suited to any endeavour that benefits from the capacity to make genuine connection and to bring real warmth and real beauty into the situations and relationships you inhabit.`,

  venus_opposition_ascendant: `The solar return Venus opposite the Ascendant — conjunct the Descendant — marks a year in which the most significant aesthetic, romantic, and relational developments arrive through significant one-to-one partnerships rather than through solo personal initiative. Others bring beauty, warmth, and genuine connection into your life in ways that would not occur in more solitary or more inwardly directed years, and the year's most rewarding creative and romantic experiences tend to be those that arise through genuine partnership rather than through unilateral personal effort. The year strongly favours collaboration, genuine reciprocity, and the willingness to be genuinely open to what significant others are genuinely offering.`,
};
