// src/content/aspects_sun.ts
// Solar Return: SR Sun aspects to other SR planets and Ascendant
// Key format: "sun_aspect_planet" — all lowercase, e.g. "sun_conjunction_moon"
// Aspects covered: conjunction, sextile, square, trine, opposition (5 major)
// Planets aspected: Moon, Mercury, Venus, Mars, Jupiter, Saturn, Uranus, Neptune, Pluto, Ascendant
// Sources: Mary Fortier Shea "Planets in Solar Returns" (3rd ed.) — primary;
// Cafe Astrology SR series; Robert Hand "Planets in Transit"
// Entries: 3-4 sentences

export const ASPECTS_SUN: Record<string, string> = {

  // SUN–MOON
  sun_conjunction_moon: `The solar return Sun conjunct Moon marks a year in which your conscious identity and emotional instincts are unusually aligned — what you want and what you feel are pointed in the same direction, reducing the inner friction that characterises more divided years. Personal and professional life tend to converge rather than compete, and the year has a quality of integrated wholeness that supports decisive action and genuine self-expression. New beginnings of lasting personal significance are possible, particularly around the birthday itself. The year is most productive when you trust the unified signal your instincts and intentions are sending rather than second-guessing what feels unusually clear.`,

  sun_sextile_moon: `The solar return Sun sextile Moon brings a quality of easy cooperation between your sense of identity and your emotional life, creating a background harmony that supports both personal and professional endeavours with less effort than in more divided years. Relationships benefit from a natural warmth and from the sense that you are genuinely yourself in the company of others rather than performing a version of yourself. Creative work proceeds more smoothly when it draws on both personal vision and emotional resonance. The year rewards those who act on the genuine alignment between what they want and what they feel without overthinking the advantage they have been given.`,

  sun_square_moon: `The solar return Sun square Moon marks a year of genuine tension between your conscious goals and your emotional needs — what you are working toward and what you instinctively feel you need are pulling in different directions, creating a productive but sometimes exhausting inner friction. The domestic and professional spheres may compete for energy and attention, and the needs of personal relationships may work against career demands or vice versa. The year asks for honest negotiation between these competing priorities rather than the suppression of one in favour of the other. What is worked out through that negotiation tends to be a more genuinely integrated approach to the balance between inner life and outer achievement than easier years produce.`,

  sun_trine_moon: `The solar return Sun trine Moon is one of the most harmonious personal aspect patterns in a solar return, bringing a quality of natural ease between your identity and your emotional life that supports both creative expression and genuine relationship. Personal and professional matters tend to flow in the same direction rather than competing for limited energy, and the year has an overall quality of natural momentum. The risk of this harmonious aspect is that its ease can shade into complacency — the support the year provides is most fully realised by those who actively engage with the opportunities it opens rather than simply enjoying the comfortable atmosphere it creates.`,

  sun_opposition_moon: `The solar return Sun opposite Moon marks a year in which the tension between your identity and your emotional needs is most visible and most demanding — you are pulled between competing priorities in ways that require conscious management rather than easy resolution. Relationships may be a particular source of this tension, with the needs of significant others pulling against your own goals and self-expression in ways that require genuine negotiation. The professional and domestic spheres are in genuine dialogue, and the year asks that both be honoured rather than one being sacrificed to the other. The awareness that this opposition demands tends to produce a more genuinely balanced life than years in which one side of the equation goes unexamined.`,

  // SUN–MERCURY
  sun_conjunction_mercury: `The solar return Sun conjunct Mercury brings intellectual clarity, communicative confidence, and a strong alignment between your sense of identity and your way of thinking and expressing ideas to the year. Writing, speaking, and the communication of what you most centrally care about are all strongly supported, and the year favours any work that requires the clear articulation of personal vision or expertise. The mind is most alive when engaged with what genuinely matters to you rather than what is merely technically interesting. This is an excellent year for publishing, teaching, or any form of intellectual self-expression that carries genuine personal investment.`,

  sun_sextile_mercury: `The solar return Sun sextile Mercury brings a quality of easy intellectual fluency and communicative confidence to the year, supporting writing, speaking, and the clear expression of personal ideas with less effort than in other years. Conversations and professional communications tend to go well, and the ability to articulate what you mean with precision and genuine engagement is heightened. The year favours intellectual projects that draw on both analytical skill and personal conviction. Creative and professional writing benefit from the natural alignment between thinking and self-expression that this aspect provides.`,

  sun_square_mercury: `The solar return Sun square Mercury brings a quality of productive tension between your sense of identity and the way you think and communicate — ideas and self-expression are at odds in ways that require more conscious effort to resolve than easier Mercury aspects provide. Communications may be more prone to misunderstanding, and the mind may work against the very goals it is trying to serve through overthinking, second-guessing, or the tendency to articulate positions before they are fully formed. The year benefits from deliberate attention to how you are saying what you mean, and from the willingness to revise and refine rather than insisting on the first formulation.`,

  sun_trine_mercury: `The solar return Sun trine Mercury brings exceptional communicative ease, intellectual confidence, and a natural alignment between thinking and self-expression to the year. Writing and speaking feel more effortless than usual, and the ability to convey complex ideas with both precision and genuine personal engagement is at its most fully available. Professional communications, negotiations, and any work requiring clear articulation of personal expertise are strongly supported. The year is particularly productive for publishing, teaching, or any intellectual project that benefits from the sense that thinking and identity are genuinely working together.`,

  sun_opposition_mercury: `The solar return Sun opposite Mercury brings a quality of tension between your sense of self and the way your mind works — your identity and your intellectual approach are pulling in different directions, requiring more conscious effort to integrate than harmonious Mercury aspects provide. You may find yourself advocating for positions you later revise, or thinking most clearly about problems when you have stepped away from personal investment in the outcome. The year benefits from genuine openness to other perspectives and from the recognition that the most useful thinking often happens in dialogue rather than in the privacy of your own well-defended position.`,

  // SUN–VENUS
  sun_conjunction_venus: `The solar return Sun conjunct Venus brings warmth, creative confidence, and a quality of genuine personal charm and aesthetic vitality to the year's identity and self-expression. Relationships are more harmonious and more genuinely pleasurable than in other years, and the year has an overall quality of ease and attraction that supports both personal and creative endeavours. Artistic and creative work benefits from the natural alignment between your sense of self and your aesthetic sensibility. The year is well-suited to romantic developments, creative projects, and any work that requires the capacity to make what you do genuinely appealing to others.`,

  sun_sextile_venus: `The solar return Sun sextile Venus brings a quality of easy social grace, aesthetic pleasure, and genuine warmth to the year's personal life and creative work. Relationships benefit from a natural cooperative quality, and the year tends to bring pleasant and sometimes rewarding social and romantic developments without the dramatic intensity of stronger Venus aspects. Creative and artistic work is supported by a genuine sense of what is beautiful and by the easy alignment between personal vision and aesthetic execution. The year is most rewarding when you actively engage with the social and creative opportunities it opens.`,

  sun_square_venus: `The solar return Sun square Venus brings a quality of tension between your sense of identity and your need for relationship, pleasure, and aesthetic expression — what you want for yourself and what you want from others may be in genuine conflict during the year. Creative work may be frustrated by the gap between what you envision and what you can currently execute, or by the difficulty of balancing creative ambition with the demands of significant relationships. The year asks for honest negotiation between self-expression and the genuine needs of the people and projects you care about. What is worked out through that negotiation tends to produce more genuinely integrated creative and relational life.`,

  sun_trine_venus: `The solar return Sun trine Venus is one of the most personally pleasant aspect patterns in a solar return, bringing warmth, creative ease, and a quality of genuine attraction and social grace to the year's personal life. Relationships tend to be more harmonious and more genuinely enjoyable than in other years, and the year has an overall quality of aesthetic pleasure and social reward. Creative work benefits from the natural ease between personal vision and its execution, and the year is well-suited to artistic projects, romantic developments, and any endeavour that benefits from genuine personal charm and warmth.`,

  sun_opposition_venus: `The solar return Sun opposite Venus marks a year in which the needs of relationship and the demands of personal self-expression are in genuine and visible tension — you are asked to find a genuine balance between your own creative and personal goals and what your most significant relationships genuinely require of you. Creative ambitions may compete with relational responsibilities, or the desire for personal freedom may work against the genuine intimacy that the year's most important relationships are asking for. The year is most productive when you resist the temptation to resolve the tension by simply suppressing one side of it, and instead engage honestly with what both your creative life and your most significant relationships are asking.`,

  // SUN–MARS
  sun_conjunction_mars: `The solar return Sun conjunct Mars is one of the most energetically potent aspect patterns in a solar return, bringing exceptional physical vitality, competitive drive, and a quality of bold personal initiative to the year's identity and self-expression. You pursue what you want with more directness, more force, and more willingness to compete than in other years, and the year tends to reward those who act with genuine decisiveness. The risk is impulsiveness and the tendency to assert without adequate attention to the consequences for others — the energy of this aspect is most productive when directed toward genuinely worthwhile goals with enough self-awareness to avoid the aggression that untempered Mars energy can produce.`,

  sun_sextile_mars: `The solar return Sun sextile Mars brings a quality of easy, well-directed physical energy and competitive confidence to the year, supporting active pursuit of personal goals with more effectiveness and less friction than in other years. The drive to act and the sense of who you are and what you are working toward are in comfortable alignment, and the year tends to support decisive action without the impulsiveness that more intense Mars aspects can produce. Physical vitality is good, and the year is well-suited to active projects requiring sustained physical and motivational energy.`,

  sun_square_mars: `The solar return Sun square Mars is one of the more demanding personal aspect patterns in a solar return, bringing a quality of tension between your identity and your drive that can produce both exceptional productive energy and genuine conflict. Frustration, impatience, and the tendency to assert yourself in ways that create unnecessary opposition are characteristic risks — the energy of this aspect is powerful but not always well-directed. The year tends to involve situations that require you to stand your ground, and benefits most from the channelling of considerable personal energy into genuinely worthwhile and clearly defined goals rather than into reactive conflict.`,

  sun_trine_mars: `The solar return Sun trine Mars brings a quality of easy, well-sustained physical energy, productive confidence, and effective personal drive to the year. The will to act and the sense of personal identity are in natural alignment, producing a year in which personal initiatives tend to go well and in which the energy to pursue what you want is reliably available. Physical vitality is strong, competitive situations tend to resolve in your favour, and the year rewards active engagement with the opportunities it presents. Leadership and personal initiative are particularly well-supported.`,

  sun_opposition_mars: `The solar return Sun opposite Mars marks a year in which your identity and your drive are in genuine and sometimes confrontational tension — personal goals may be opposed by others with equal determination, and the year may involve more conflict, competition, and the need to actively defend your position than in other years. The risk is the escalation of necessary self-assertion into genuine aggression, or the reactive engagement with opposition that drains energy better directed elsewhere. The year is most productive when you maintain clear awareness of what you are actually fighting for and direct your considerable energy toward what is genuinely worth the effort.`,

  // SUN–JUPITER
  sun_conjunction_jupiter: `The solar return Sun conjunct Jupiter is one of the most broadly fortunate personal aspect patterns in a solar return, bringing expanded confidence, genuine opportunity, and a quality of optimistic forward momentum to the year's identity and personal life. The sense of what is possible is enlarged, and the year tends to deliver genuine rewards to those who act on Jupiter's expanded sense of personal potential with real commitment rather than merely basking in the optimistic glow. Overconfidence and over-extension are the characteristic risks — the year is most productive when Jupiter's genuine expansion is matched by honest assessment of what is actually being taken on.`,

  sun_sextile_jupiter: `The solar return Sun sextile Jupiter brings a quality of easy expansiveness, genuine good humour, and productive optimism to the year's personal and professional life. Opportunities arise without excessive drama, and the year tends to reward those who act on the genuine openings it provides with enough confidence and enough follow-through to develop them to their potential. Relationships benefit from a quality of warmth and generosity, and the year has an overall quality of ease and genuine good fortune. The sextile requires active engagement — its gifts are available but not automatically delivered.`,

  sun_square_jupiter: `The solar return Sun square Jupiter brings the tension of overextension — the sense of expanded possibility that Jupiter always provides is present, but the square means that personal goals and the circumstances that would support them are not yet fully aligned, requiring more effort to bridge the gap than easier Jupiter aspects demand. The risk is promising more than can be delivered, taking on more than can be sustained, or allowing optimism to substitute for the disciplined work that actual achievement requires. The year is most productive when Jupiter's genuine confidence is paired with honest assessment of what the square's friction is asking you to actually build or resolve.`,

  sun_trine_jupiter: `The solar return Sun trine Jupiter is among the most supportive and genuinely fortunate aspect patterns in a solar return, bringing a quality of natural confidence, expansive opportunity, and genuine good fortune to the year's personal life and identity. Things tend to go well, opportunities materialise with less friction than usual, and the year has an overall quality of ease and genuine reward for those who engage actively with what it offers. The risk — as with all easy Jupiter aspects — is that comfort shades into complacency, and the considerable gifts of this aspect go undeveloped for lack of the urgency that more challenging years provide.`,

  sun_opposition_jupiter: `The solar return Sun opposite Jupiter marks a year in which expanded opportunity and genuine good fortune are present but arrive primarily through other people, significant relationships, and the engagements between your goals and the world outside yourself rather than through solo effort. You may find that others open doors, provide resources, or bring the expansive opportunities that Jupiter promises — but the opposition means those gifts require genuine reciprocal engagement rather than passive reception. The risk is over-reliance on others' generosity or over-extension in response to others' enthusiasm. The year is most productive when you meet Jupiter's genuine gifts with genuine personal investment.`,

  // SUN–SATURN
  sun_conjunction_saturn: `The solar return Sun conjunct Saturn marks a year of serious personal discipline, heightened self-assessment, and a quality of weight and responsibility in the domain of personal identity and self-expression. The year demands more of you than most — more honest self-evaluation, more sustained effort, and more genuine accountability for the gap between who you intend to be and who you are actually being. Physical vitality may be lower than usual, and the year can feel heavy and constraining. What is built through this year's discipline tends to be among the most genuinely solid personal achievements of the decade — Saturn in contact with the Sun always asks the question of what is genuinely worth becoming, and rewards those who answer honestly.`,

  sun_sextile_saturn: `The solar return Sun sextile Saturn brings a quality of productive discipline, grounded ambition, and honest self-assessment to the year's personal life without the weight and constriction of stronger Saturn aspects. You are more serious and more sustainably focused than in other years, and the year rewards the kind of patient, disciplined effort that Saturn always recognises. Personal projects and professional ambitions that require sustained commitment over time are particularly well-supported. The year has a quality of sober forward progress — less exciting than Jupiter years, more genuinely productive than the appearance suggests.`,

  sun_square_saturn: `The solar return Sun square Saturn marks a year of genuine personal challenge — the sense of identity and purpose is under pressure from Saturn's demand for honest accountability, and the gap between who you intend to be and what you are actually demonstrating may be impossible to ignore. Obstacles arise in personal and professional life that require genuine patience and genuine effort to navigate rather than charm or optimism. The year is not designed for ease — it is designed for the kind of honest reckoning with personal limitations and genuine strengths that only Saturn's friction reliably produces. What is earned through the year's effort tends to be permanently and honestly yours.`,

  sun_trine_saturn: `The solar return Sun trine Saturn brings a quality of grounded personal authority, disciplined self-expression, and the genuine confidence that comes from honest self-knowledge to the year. You are more reliably effective than in years when personal identity is untested by Saturn's demands, and the year tends to reward sustained and genuinely disciplined effort with recognition and advancement that feels genuinely merited. Personal authority is at its most natural and most commanding. The year is well-suited to long-term projects, professional advancement, and any endeavour that requires the capacity to be both confident and genuinely accountable.`,

  sun_opposition_saturn: `The solar return Sun opposite Saturn marks a year in which the demands of discipline, limitation, and honest accountability arrive primarily through others — authority figures, significant partners, or the institutional structures of professional and public life impose constraints and demands that feel external but that are ultimately asking questions about personal integrity and genuine substance. The year tends to reveal what you are actually made of when tested by genuine external pressure rather than internal aspiration alone. What survives Saturn's opposition tends to be what is genuinely solid — both in your sense of self and in your relationship with the world that is assessing you.`,

  // SUN–URANUS
  sun_conjunction_uranus: `The solar return Sun conjunct Uranus marks a year of sudden, electric, and sometimes dramatic personal change — your sense of identity is being disrupted and liberated simultaneously, and the version of yourself that emerges from the year may be genuinely surprising to those who thought they knew you. The impulse toward personal authenticity is at its most urgent and most uncompromising, and compromises in how you live and express yourself that have been tolerable in other years may suddenly feel genuinely impossible. The year is most productive when you allow the genuine liberation of this aspect to guide real change rather than simply enjoying the excitement of disruption for its own sake.`,

  sun_sextile_uranus: `The solar return Sun sextile Uranus brings a quality of creative originality, productive independence, and genuine openness to change and experimentation to the year's personal life without the destabilising intensity of stronger Uranus aspects. New approaches, unconventional ideas, and the willingness to depart from established patterns in genuinely productive ways are supported with more ease than friction. The year favours originality in personal expression and professional approach, and tends to reward those who bring genuine innovation to what they do rather than repeating what has already worked.`,

  sun_square_uranus: `The solar return Sun square Uranus marks a year of genuine tension between the need for stability and the impulse toward personal freedom and radical change — what you are and what you feel you must become are pulling in directions that cannot easily be reconciled without disruption to what is currently settled. Unexpected developments may force changes that were not planned and are not entirely welcome. The year tends to surface the authenticity question in its sharpest form: what in your current life is genuinely yours, and what has been maintained because changing it felt too disruptive? The disruption itself is usually pointing toward something more genuinely authentic.`,

  sun_trine_uranus: `The solar return Sun trine Uranus brings a quality of creative originality, productive independence, and genuine personal freedom to the year with enough ease that change feels exciting rather than destabilising. New directions, innovative approaches, and the willingness to depart from what has been established in favour of what is more genuinely authentic are supported with a quality of forward momentum and natural confidence. The year is well-suited to personal reinvention, creative experimentation, and any endeavour that benefits from the willingness to be genuinely and consequentially different. Leadership through originality rather than authority is particularly well-supported.`,

  sun_opposition_uranus: `The solar return Sun opposite Uranus marks a year in which the demand for personal freedom, authenticity, and radical change arrives primarily through others — significant people in your life, or the unexpected developments that external circumstances produce, are disrupting the settled patterns of your identity in ways that feel externally imposed but that are ultimately liberating. Partners, colleagues, or institutions may behave in unpredictable ways that force a reassessment of what you have taken for granted about yourself and your life. The year's disruptions, however unwelcome, consistently point toward what was never as settled as it appeared.`,

  // SUN–NEPTUNE
  sun_conjunction_neptune: `The solar return Sun conjunct Neptune marks a year in which the clear outlines of personal identity are dissolved in Neptune's boundary-dissolving fog — who you are feels less fixed and less certain than usual, and the year may proceed through intuition, creative inspiration, and spiritual sensitivity more than through deliberate self-directed effort. Imagination and artistic inspiration are at their most alive, and the year strongly supports creative work of genuine emotional and spiritual depth. The risk is the loss of personal direction in the beautiful but evasive territory that Neptune always inhabits — the year benefits from both Neptune's genuine openness and enough grounded structure to give that openness somewhere real to go.`,

  sun_sextile_neptune: `The solar return Sun sextile Neptune brings a quality of heightened creative sensitivity, spiritual openness, and imaginative richness to the year's personal life without the disorienting dissolution of stronger Neptune aspects. Artistic and creative work benefits from a genuine quality of inspiration and emotional resonance, and the capacity for compassionate engagement with others is heightened without becoming overwhelming. The year favours creative work, spiritual practice, and any engagement that benefits from the willingness to perceive beyond the merely literal. Intuition is reliable when consulted honestly.`,

  sun_square_neptune: `The solar return Sun square Neptune marks a year in which clarity about personal identity, direction, and purpose is harder to maintain than usual — Neptune's dissolving influence is in genuine tension with the Sun's need for clear self-expression and deliberate personal direction, producing a year in which confusion, self-deception, and the substitution of idealised self-image for honest self-knowledge are characteristic risks. Creative and spiritual work may be genuinely inspired, but practical endeavours benefit from more external accountability and more careful factual grounding than Neptune naturally provides. The year asks for both genuine openness and deliberate honesty about what is actually being perceived.`,

  sun_trine_neptune: `The solar return Sun trine Neptune brings a quality of genuine creative inspiration, spiritual sensitivity, and compassionate personal warmth to the year with enough ease that Neptune's gifts are more available than its risks. Artistic and imaginative work is naturally inspired, intuition is reliable, and the capacity for empathy and compassionate engagement with others is at its most fully and most generously available. The year is well-suited to creative projects, spiritual practice, and any endeavour that benefits from the ability to perceive and respond to what lies beneath the surface of ordinary appearances.`,

  sun_opposition_neptune: `The solar return Sun opposite Neptune marks a year in which the dissolving, idealising quality of Neptune arrives primarily through significant others and external circumstances — others may not be fully honest about who they are or what they want, and the temptation to see what you wish to see in your most important relationships is unusually strong. Creative inspiration and spiritual sensitivity remain real gifts of this aspect, but the clarity of self-perception and the honest assessment of others both benefit from more deliberate grounding than Neptune's opposition naturally encourages. The year asks for the willingness to see what is actually there.`,

  // SUN–PLUTO
  sun_conjunction_pluto: `The solar return Sun conjunct Pluto marks a year of deep, irreversible personal transformation — who you are at the beginning of the year and who you are at its end are genuinely different, and the process of revision operates at a depth and with a force that cannot be fully managed or controlled. Power dynamics in personal and professional life are highlighted with unusual intensity, and the year may involve significant encounters with the question of where genuine personal power lies and how it is being used or surrendered. What is stripped away during this year was already dying — what remains and what is rebuilt tends to be more genuinely and more powerfully authentic than what preceded it.`,

  sun_sextile_pluto: `The solar return Sun sextile Pluto brings a quality of focused personal power, penetrating self-awareness, and productive engagement with the deeper dimensions of personal transformation to the year without the overwhelming intensity of stronger Pluto aspects. The year tends to support genuine personal depth — research, psychological insight, the honest investigation of what is operating beneath the surface — with a quality of natural effectiveness rather than compulsive urgency. Personal authority is deepened by the honest engagement this aspect supports, and the year rewards those willing to look clearly at what others prefer to leave unexamined.`,

  sun_square_pluto: `The solar return Sun square Pluto marks a year of genuine and sometimes difficult confrontation with personal power, transformation, and the question of what in your current life is genuinely alive and what needs to be released. Power struggles in personal and professional life may be unavoidable, and the year tends to surface the most difficult questions about personal integrity, genuine authority, and the gap between the power you project and the power you actually hold. The year does not permit the comfortable avoidance of these questions — it rewards those who engage with them honestly, and tends to force engagement on those who resist.`,

  sun_trine_pluto: `The solar return Sun trine Pluto brings a quality of deep personal power, natural authority, and genuine transformative effectiveness to the year with enough ease that the year's most significant personal developments proceed through insight and purposeful action rather than through crisis and compulsion. The capacity for profound self-understanding and for influencing the situations and people around you from a position of genuine personal depth is at its most naturally available. The year is well-suited to significant personal projects, leadership in consequential situations, and any endeavour that benefits from the capacity to operate from genuine depth rather than surface competence.`,

  sun_opposition_pluto: `The solar return Sun opposite Pluto marks a year in which the most intense and most transformative power dynamics arrive through others — significant people or institutions in your life hold power that you must genuinely reckon with, or external circumstances force a confrontation with the question of where genuine personal power lies and what it is actually worth defending. The year tends to involve situations that are not fully within your control and that require both genuine personal courage and the honest willingness to release what cannot be held. What survives Pluto's opposition tends to be what was genuinely and irreversibly yours to begin with.`,

  // SUN–ASCENDANT
  sun_conjunction_ascendant: `The solar return Sun conjunct the Ascendant places the year's central identity themes directly on the horizon of self-presentation and the way you meet the world — you are more visible, more personally impactful, and more genuinely yourself in your external presentation than in other years. The year tends to bring you forward in your personal and professional world in ways that are both more exposed and more genuinely rewarding than years when the Sun is more withdrawn. Leadership, personal initiative, and the courage to be fully seen are all strongly supported, and the year rewards those who show up as completely and as authentically as they are capable of being.`,

  sun_sextile_ascendant: `The solar return Sun sextile the Ascendant brings a quality of easy personal confidence, natural self-presentation, and genuine effectiveness in how you engage with the world and the people in it. The year tends to support personal and professional initiatives with a quality of natural forward momentum, and the ability to present yourself and your work in ways that genuinely land with others is heightened. Social and professional situations tend to go well, and the year rewards active engagement with the opportunities its easy confidence makes available.`,

  sun_square_ascendant: `The solar return Sun square the Ascendant marks a year in which there is genuine tension between your sense of inner identity and the way you are perceived and received by the world — who you are and how you come across are in productive but sometimes frustrating misalignment, and the year may involve situations in which your self-presentation is less effective than your actual capabilities and intentions would deserve. The year benefits from honest attention to the gap between what you intend to convey and what others are actually receiving, and from the willingness to revise your approach rather than insisting that the world is simply failing to see you clearly.`,

  sun_trine_ascendant: `The solar return Sun trine the Ascendant brings a quality of natural personal authority, easy self-presentation, and genuine effectiveness in how you engage with the world to the year. Who you are and how you come across are in natural alignment, and the year tends to support personal and professional initiatives with a quality of ease and genuine confidence that makes leadership, visibility, and the direct pursuit of personal goals more naturally rewarding than in other years. The year is well-suited to any endeavour that benefits from the capacity to be genuinely and effectively yourself in the presence of others.`,

  sun_opposition_ascendant: `The solar return Sun opposite the Ascendant — conjunct the Descendant — marks a year in which the central themes of identity and self-expression are worked out primarily through significant relationships rather than through solo personal initiative. Others hold a mirror to who you are in ways that are both illuminating and sometimes uncomfortable, and the year's most significant personal developments tend to arrive through what your most important relationships ask of you. Partnership, collaboration, and the honest engagement with what others genuinely need from you are the year's primary vehicles for personal growth.`,
};
