// src/content/aspects_outer.ts
// Solar Return: SR outer planet mutual aspects
// Key format: "planet1_aspect_planet2" — all lowercase, slower planet first
// e.g. "jupiter_conjunction_saturn"
// Aspects covered: conjunction, sextile, square, trine, opposition (5 major)
// Combinations covered:
//   Jupiter–Saturn, Jupiter–Uranus, Jupiter–Neptune, Jupiter–Pluto
//   Saturn–Uranus, Saturn–Neptune, Saturn–Pluto
//   Uranus–Neptune, Uranus–Pluto
//   Neptune–Pluto
// Sources: Mary Fortier Shea "Planets in Solar Returns" (3rd ed.) — primary;
// Robert Hand "Planets in Transit"; Liz Greene "The Outer Planets and Their Cycles"
// NOTE: Because outer planets move slowly, many of these aspects are
// generational — they persist across many SR charts in the same years.
// In a SR context the house positions of the aspecting planets carry
// more individual significance than the aspect itself. Entries reflect
// this by focusing on the quality of tension or cooperation between
// the two principles rather than specific individual prediction.
// Entries: 3-4 sentences

export const ASPECTS_OUTER: Record<string, string> = {

  // JUPITER–SATURN
  jupiter_conjunction_saturn: `The solar return Jupiter conjunct Saturn — the great conjunction — marks a year in which the principles of expansion and contraction, opportunity and limitation, are fused into a single demanding but genuinely productive tension. The year tends to bring both genuine opportunity and genuine obstacles in the same domain, requiring the discipline to build what Jupiter opens and the confidence to keep going when Saturn inevitably applies its weight to what has been begun. Neither planet operates freely — Jupiter's optimism is disciplined by Saturn's realism, and Saturn's constriction is periodically lifted by Jupiter's genuine confidence. What is built under this conjunction tends to be among the most solid and most genuinely lasting achievements of any year.`,

  jupiter_sextile_saturn: `The solar return Jupiter sextile Saturn brings a quality of productive balance between expansion and discipline — opportunity and structure cooperate in ways that allow genuine growth to be consolidated rather than simply initiated and abandoned. The year tends to support sustained, realistic progress toward significant goals with a quality of natural forward momentum that neither planet achieves as effectively alone. New ventures are well-supported when they combine Jupiter's genuine confidence with Saturn's honest structural planning, and what is built tends to be both genuinely ambitious and genuinely solid.`,

  jupiter_square_saturn: `The solar return Jupiter square Saturn marks a year of genuine tension between expansion and consolidation — the impulse to grow, to reach, and to pursue genuine opportunity is persistently in conflict with the demand for discipline, realistic assessment, and the honest acknowledgment of limitation. Progress feels halting — genuine opportunity appears but is hedged by genuine obstacles, and the gap between what is possible and what is practical requires constant honest negotiation. The year is most productive when you resist both the temptation to abandon genuine ambition under Saturn's pressure and the temptation to over-extend past Saturn's honest limits under Jupiter's influence.`,

  jupiter_trine_saturn: `The solar return Jupiter trine Saturn brings one of the most sustainably productive combinations in a solar return — expansion and discipline in natural cooperation, producing a year of genuine forward progress that is both ambitious and honest, both optimistic and realistically grounded. What is begun under this aspect tends to be both genuinely worthwhile and genuinely achievable, and the year tends to support significant personal and professional development with a quality of natural effectiveness and genuine lasting consequence. The balance between confidence and discipline is more naturally available than in years when these principles operate in opposition.`,

  jupiter_opposition_saturn: `The solar return Jupiter opposite Saturn marks a year in which the tension between expansion and limitation is most visible and most externally mediated — the principles of growth and consolidation arrive through different people, different circumstances, and different dimensions of the year's experience rather than operating in unified internal tension. One significant relationship or domain of life may embody Jupiter's expansive opportunity while another embodies Saturn's demanding limitation, and the year asks for the capacity to hold both honestly rather than resolving the tension by simply surrendering to one and abandoning the other.`,

  // JUPITER–URANUS
  jupiter_conjunction_uranus: `The solar return Jupiter conjunct Uranus marks a year of sudden, electric, and genuinely expansive breakthrough — the combination of Jupiter's optimism and Uranus's disruptive originality produces unexpected opportunities, sudden positive developments, and a quality of genuine forward leap that more gradual years cannot match. What arrives tends to arrive suddenly and with a quality of genuine surprise, and the year strongly rewards those who are ready to act on unexpected openings with enough confidence to move before conditions are fully established. The risk is the instability of what is built on sudden inspiration — the breakthrough energy of this aspect benefits from enough structural follow-through to give what it initiates genuine lasting form.`,

  jupiter_sextile_uranus: `The solar return Jupiter sextile Uranus brings a quality of productive originality, easy openness to unexpected opportunity, and genuine forward momentum in innovative directions to the year. New and unconventional approaches to genuine opportunity are supported with a quality of natural effectiveness, and the year tends to reward those who combine genuine confidence with genuine willingness to depart from established methods in directions that are both new and genuinely promising. The year favours creative and professional innovation that draws on both expansive ambition and genuine original thinking.`,

  jupiter_square_uranus: `The solar return Jupiter square Uranus marks a year of genuine tension between the desire for expansive opportunity and the disruptive, unpredictable energy of Uranus — growth and liberation are both present but are not easily reconciled with the stability and consolidation that genuine opportunity usually requires. Sudden developments may open doors that close with equal suddenness, or the pursuit of innovative approaches may generate instability that outpaces the genuine opportunity being pursued. The year benefits from the willingness to act on genuine opportunity without over-committing to the stability of what is inherently unpredictable.`,

  jupiter_trine_uranus: `The solar return Jupiter trine Uranus brings a quality of genuine forward leap, creative breakthrough, and expansive innovative energy to the year with enough ease that sudden positive developments feel exciting rather than destabilising. Unexpected opportunities tend to arrive at genuinely propitious moments, and the year rewards those who act on genuine inspiration with a quality of natural effectiveness and genuine forward momentum. The combination of expansive confidence and creative originality is at its most naturally productive, and the year is well-suited to any endeavour that benefits from both genuine ambition and genuine departure from established approaches.`,

  jupiter_opposition_uranus: `The solar return Jupiter opposite Uranus marks a year in which the tension between expansive opportunity and disruptive change arrives primarily through significant others and external circumstances — the world around you is both opening doors and disrupting stability in ways that require genuine flexibility and genuine confidence to navigate productively. The year tends to produce unexpected developments in the domains where Jupiter and Uranus are respectively placed, requiring the capacity to respond to genuine opportunity and genuine disruption with approximately equal composure.`,

  // JUPITER–NEPTUNE
  jupiter_conjunction_neptune: `The solar return Jupiter conjunct Neptune marks a year of exceptional spiritual expansiveness, creative inspiration, and a quality of idealistic vision that is both genuinely inspiring and genuinely susceptible to the inflation and self-deception that both planets can produce when operating together without grounding. Spiritual practice, creative work of genuine depth, and compassionate service are powerfully supported. The risk is the substitution of inspired vision for honest practical engagement — the year can produce beautiful beliefs, beautiful plans, and beautiful promises that exceed what the actual circumstances can support. What is most productively pursued under this aspect is what remains genuinely meaningful when the initial inspiration has subsided.`,

  jupiter_sextile_neptune: `The solar return Jupiter sextile Neptune brings a quality of easy spiritual openness, genuine creative inspiration, and compassionate expansiveness to the year without the inflationary excess of stronger combinations. Spiritual practice, creative work, and compassionate engagement with others are all supported with a quality of natural grace and genuine productive depth. Intuition is reliably informative when consulted honestly, and the year tends to support any endeavour that aspires to something genuinely larger and more meaningful than purely personal ambition.`,

  jupiter_square_neptune: `The solar return Jupiter square Neptune marks a year of genuine tension between expansive ambition and the dissolving, idealising influence of Neptune — goals may be set at a scale that exceeds what the actual circumstances can support, and the line between genuine inspired vision and the comfortable substitution of beautiful possibility for honest engagement with difficult reality is characteristically difficult to maintain. Financial and practical decisions benefit from more sceptical external assessment than Jupiter's optimism and Neptune's inspiring haze naturally encourages. The year is most productive when genuine aspiration is regularly grounded in honest factual assessment.`,

  jupiter_trine_neptune: `The solar return Jupiter trine Neptune brings a quality of genuine spiritual grace, creative abundance, and expansive compassionate engagement with the larger dimensions of life to the year. Spiritual practice, creative work aspiring to genuine beauty and depth, and the compassionate service of what is most genuinely in need are all strongly supported with a quality of natural effectiveness and genuine inner alignment. The year carries a quality of quiet but genuine good fortune in the domains where these principles are most alive, and tends to reward those who engage with genuine sincerity rather than strategic calculation.`,

  jupiter_opposition_neptune: `The solar return Jupiter opposite Neptune marks a year in which the tension between expansive opportunity and idealising dissolution arrives primarily through significant others — the world and the people in it may appear more promising, more spiritually significant, or more genuinely aligned with your deepest aspirations than honest assessment would support, and the temptation to pursue what is most inspiring rather than what is most real is unusually strong. The year benefits from genuine grounding in what is actually available and what is actually being offered rather than what the imagination most generously projects.`,

  // JUPITER–PLUTO
  jupiter_conjunction_pluto: `The solar return Jupiter conjunct Pluto marks a year of exceptional ambition, transformative power, and the kind of deep, driven pursuit of significant goals that can produce genuine and lasting achievement or — if untempered by honest values — the ruthless pursuit of power and expansion for their own sake. The combination of Jupiter's confidence and Pluto's compulsive depth produces a quality of focused, expansive intensity that is among the most powerful in a solar return. Significant personal and professional transformation is possible, and the year tends to reward those who direct this exceptional energy toward goals that are genuinely worth the force they are pursuing with — and who are honest about the means they are using to pursue them.`,

  jupiter_sextile_pluto: `The solar return Jupiter sextile Pluto brings a quality of focused ambitious drive, transformative confidence, and productive engagement with the deeper dimensions of significant personal and professional goals to the year. Expansion and transformation work in comfortable cooperation, and the year tends to support genuine progress toward significant and lasting goals with a quality of natural effectiveness and genuine depth. The year favours any endeavour that requires both genuine ambition and the willingness to go beneath the surface of things to engage honestly with what is actually driving and actually sustaining the pursuit.`,

  jupiter_square_pluto: `The solar return Jupiter square Pluto marks a year of genuine tension between expansive ambition and the compulsive, sometimes ruthless intensity of Pluto — the drive to grow and the drive to transform are both powerful but not easily reconciled, and the gap between what is genuinely worth pursuing and the means being used to pursue it requires honest and regular attention. Power struggles in professional and public life may be more intense and more consequential than in other years. The year is most productive when the genuine ambition of Jupiter is consistently held to the honest standard of values that Pluto's confrontational intensity consistently demands.`,

  jupiter_trine_pluto: `The solar return Jupiter trine Pluto brings a quality of exceptional transformative ambition, focused expansive power, and genuine effectiveness in the pursuit of significant and lasting personal and professional goals to the year. Expansion and transformation are in natural alignment, and the year tends to reward those who pursue genuinely significant goals with the full depth of commitment they require with a quality of natural effectiveness and genuine lasting impact. Leadership in consequential situations, significant creative projects, and any endeavour that requires both genuine ambition and genuine depth are particularly well-supported.`,

  jupiter_opposition_pluto: `The solar return Jupiter opposite Pluto marks a year in which the most significant expressions of transformative power and ambitious expansion arrive through others — significant partners, authority figures, or the broader world exert a quality of compulsive, powerful influence that challenges personal ambition and requires genuine strategic intelligence to navigate rather than simply oppose or simply accommodate. The year tends to clarify what genuine personal ambition is actually made of when it is required to engage with something genuinely more powerful than itself.`,

  // SATURN–URANUS
  saturn_conjunction_uranus: `The solar return Saturn conjunct Uranus marks a year of genuine and sometimes seriously demanding tension between the principles of structure and disruption, discipline and liberation, consolidation and radical change — both operating simultaneously in the same domain rather than in alternation. The year tends to produce situations in which established structures are genuinely disrupted and new structures are genuinely demanded, requiring the capacity to release what is no longer viable while building what will actually sustain the life going forward. What is most productively navigated is the honest question of which existing structures deserve to be retained and strengthened and which have already outlived their genuine usefulness.`,

  saturn_sextile_uranus: `The solar return Saturn sextile Uranus brings a quality of productive structural innovation — the willingness to reform and improve established structures rather than simply disrupting or simply preserving them. Genuine change is made possible by the cooperation between Uranus's liberating energy and Saturn's structural discipline, and the year tends to support the kind of gradual but genuine reform that is more lastingly productive than either radical disruption or rigid conservation alone. New approaches can be tested against established standards, and what survives that testing tends to be both genuinely new and genuinely solid.`,

  saturn_square_uranus: `The solar return Saturn square Uranus marks a year of persistent tension between the need to maintain established structures and the insistent pressure toward liberation and genuine change — neither principle is able to fully prevail, and the friction between them can produce both genuine reform and genuine instability depending on how honestly and how flexibly the tension is engaged. The year tends to surface the most honest questions about which structures in the life are genuinely load-bearing and deserve to be preserved, and which are simply familiar and deserve to be released.`,

  saturn_trine_uranus: `The solar return Saturn trine Uranus brings a quality of productive structural reform — the capacity to innovate within established frameworks and to build new structures that are both genuinely original and genuinely solid. Change is made possible without disruption, and new approaches can be implemented with enough structural grounding to give them genuine lasting form. The year favours any endeavour that requires both genuine creative departure from established methods and the structural discipline to give what is genuinely new a form that will actually sustain it.`,

  saturn_opposition_uranus: `The solar return Saturn opposite Uranus marks a year in which the tension between structure and liberation, discipline and disruption, is most externally visible and most demanding of active management — the different dimensions of the year's experience embody these opposing principles in ways that require the capacity to hold structure and change in genuine productive tension rather than simply surrendering to one at the expense of the other. What is most productively navigated is the honest question of where genuine stability and genuine liberation are both genuinely needed.`,

  // SATURN–NEPTUNE
  saturn_conjunction_neptune: `The solar return Saturn conjunct Neptune marks a year of genuine and sometimes disorienting tension between the demands of reality and the allure of ideal — Saturn's unflinching insistence on what is actually true and actually achievable is in direct contact with Neptune's dissolving, idealising, and spiritually expansive influence. Spiritual practice and creative work of genuine depth are supported by the structural discipline Saturn provides for Neptune's inspiration. The risk is either the dissolution of necessary structures under Neptune's influence or the suppression of genuine spiritual and creative vision under Saturn's demands for practical accountability — the year is most productive when both are held as genuinely necessary.`,

  saturn_sextile_neptune: `The solar return Saturn sextile Neptune brings a quality of productive integration between spiritual aspiration and practical reality — the capacity to pursue what is genuinely meaningful and genuinely inspiring within the constraints of what is actually possible. Spiritual practice, creative work, and compassionate service are all supported by enough structural discipline to give genuine inspiration actual form and genuine vision actual consequence. The year favours any endeavour that requires both genuine inner depth and the practical discipline to bring what is inwardly known into actual productive expression.`,

  saturn_square_neptune: `The solar return Saturn square Neptune marks a year of genuine tension between the demands of practical reality and the aspirations of genuine spiritual and creative vision — what is most beautifully imagined and most deeply felt may be in persistent conflict with what is actually achievable and actually real. Self-deception about practical matters, or the suppression of genuine spiritual and creative needs in the name of practical responsibility, are both characteristic risks. The year benefits from the honest willingness to submit both the spiritual and the practical dimensions of the year's demands to genuine scrutiny rather than allowing either to simply override the other.`,

  saturn_trine_neptune: `The solar return Saturn trine Neptune brings a quality of genuine integration between spiritual depth and practical effectiveness — the capacity to pursue what is most genuinely meaningful within real-world constraints, and to give genuine inner vision the structural form it requires to become actual rather than simply aspired to. Creative and spiritual work is supported by both genuine inspiration and genuine discipline, and the year tends to produce work of both genuine depth and genuine lasting form. What is built under this aspect tends to be both genuinely beautiful and genuinely solid.`,

  saturn_opposition_neptune: `The solar return Saturn opposite Neptune marks a year in which the tension between practical demands and spiritual aspiration arrives primarily through the different dimensions of the year's experience rather than through unified internal conflict — the practical world insists on accountability and limitation in ways that feel opposed to the genuine spiritual and creative needs that are simultaneously alive and demanding expression. The year asks for the capacity to honour both dimensions honestly rather than allowing practical pressure to suppress genuine inner life or allowing spiritual aspiration to evade genuine practical responsibility.`,

  // SATURN–PLUTO
  saturn_conjunction_pluto: `The solar return Saturn conjunct Pluto is one of the most seriously demanding aspect patterns in a solar return — the full weight of Saturn's disciplinary limitation and Pluto's compulsive transformative intensity are fused in the same domain, producing a year of genuine and sometimes severely demanding reckoning with the most fundamental structures of the life. What cannot be sustained is stripped away with a force that exceeds ordinary Saturnian discipline, and what is being asked to be rebuilt is required to be built on a more genuinely solid and more genuinely honest foundation than what preceded it. The year tends to produce genuine and lasting structural transformation in those who engage with what it demands with both courage and honesty.`,

  saturn_sextile_pluto: `The solar return Saturn sextile Pluto brings a quality of disciplined transformative power — the capacity to pursue genuine and lasting structural change with both the strategic patience of Saturn and the focused depth of Pluto working in comfortable cooperation. Significant and lasting reform of structures that are ready to be changed is supported with a quality of natural effectiveness, and the year tends to reward those who pursue genuine transformation with both genuine discipline and genuine depth. What is restructured under this aspect tends to be both genuinely different and genuinely solid.`,

  saturn_square_pluto: `The solar return Saturn square Pluto marks a year of genuine and sometimes seriously demanding tension between the need to maintain necessary structures and the compulsive, sometimes ruthless pressure toward transformation and the stripping away of what is no longer viable — neither principle yields easily, and the friction between them tends to produce genuine crisis points in the domains where both are operating. The year asks for genuine courage in the honest assessment of what must be changed and what must be preserved, and for the genuine strategic intelligence to navigate between Pluto's compulsive intensity and Saturn's structural demands without simply surrendering to either.`,

  saturn_trine_pluto: `The solar return Saturn trine Pluto brings a quality of exceptional structural authority, disciplined transformative power, and genuine effectiveness in the pursuit of significant and lasting structural change to the year. Discipline and transformation are in natural alignment, and the year tends to support genuine reform of what is most fundamentally important with both the strategic patience to build well and the transformative depth to go all the way down to what actually needs to change. What is built under this aspect tends to be more genuinely solid and more genuinely transformed than what more comfortable years produce.`,

  saturn_opposition_pluto: `The solar return Saturn opposite Pluto marks a year in which the most serious structural demands and the most compulsive transformative pressure arrive from different and apparently opposing directions — the weight of established responsibility and the force of necessary change are both operating with full intensity but are not easily reconciled, requiring genuine courage and genuine strategic intelligence to navigate without being simply crushed between them. The year tends to reveal what the most fundamental structures of the life are actually made of when subjected simultaneously to the full demands of Saturn's accountability and Pluto's transformative force.`,

  // URANUS–NEPTUNE
  uranus_conjunction_neptune: `The solar return Uranus conjunct Neptune — a generational aspect recurring approximately every 170 years — marks a year in which the principles of radical liberation and spiritual dissolution operate together in the same domain, producing a quality of visionary, sometimes destabilising spiritual and creative intensity that is both genuinely inspiring and genuinely difficult to ground in practical form. The imagination and the impulse toward radical authentic change are fused in ways that can produce genuine creative and spiritual breakthrough when given enough structural support to become actual rather than simply visionary.`,

  uranus_sextile_neptune: `The solar return Uranus sextile Neptune brings a quality of productive integration between the impulse toward genuine liberation and the sensitivity of genuine spiritual openness — innovation and inspiration work in comfortable cooperation, and the year tends to support any endeavour that requires both genuine creative originality and genuine inner depth. The capacity to pursue what is authentically new while remaining genuinely open to what is most spiritually real is more naturally available than in years when these principles operate in tension.`,

  uranus_square_neptune: `The solar return Uranus square Neptune marks a year of genuine tension between the impulse toward radical change and liberation and the dissolving, idealising influence of spiritual and creative sensitivity — disruption and inspiration are both present but are not easily reconciled, and the line between genuine inspired liberation and the chaotic dissolution of necessary structure is characteristically difficult to maintain. The year benefits from honest grounding in what is actually being pursued and what is actually achievable alongside the genuine creative and spiritual openness this aspect makes available.`,

  uranus_trine_neptune: `The solar return Uranus trine Neptune brings a quality of inspired liberation, genuine creative originality, and productive integration between the impulse toward authentic change and genuine spiritual openness to the year. Innovation and inspiration work in natural cooperation, and the year tends to support genuine creative and spiritual development with a quality of natural forward momentum and genuine depth. The capacity to depart from established patterns in ways that are both genuinely original and genuinely spiritually informed is more naturally available than in most years.`,

  uranus_opposition_neptune: `The solar return Uranus opposite Neptune marks a year in which the tension between radical liberation and spiritual dissolution arrives from different and apparently opposing directions — the impulse toward genuine disruptive change and the sensitivity of genuine spiritual openness are pulling in different directions rather than operating in unified cooperation. The year asks for the capacity to honour both the genuine need for authentic change and the genuine need for spiritual depth and openness without allowing either to simply override the other.`,

  // NEPTUNE–PLUTO
  neptune_conjunction_pluto: `The solar return Neptune conjunct Pluto — an extremely rare generational aspect — marks a year in which the deepest spiritual dissolution and the most compulsive transformative intensity are fused in the same domain, producing a quality of profound, sometimes overwhelming depth that operates at the very foundation of the inner life. The year tends to support the most fundamental and most lasting inner transformation in those who engage with what it demands with both genuine spiritual openness and genuine psychological courage.`,

  neptune_sextile_pluto: `The solar return Neptune sextile Pluto — a long-lasting generational aspect — brings a quality of productive integration between spiritual depth and transformative intensity, supporting genuine inner development with both the sensitivity of genuine spiritual openness and the focused depth of genuine psychological engagement. Creative, spiritual, and inner work benefit from the natural cooperation between these principles, and the year tends to support genuine depth of inner development with a quality of natural effectiveness.`,

  neptune_square_pluto: `The solar return Neptune square Pluto marks a year of genuine tension between the dissolving, idealising influence of spiritual sensitivity and the compulsive, transformative intensity of Pluto — what is most spiritually beautiful and what is most psychologically true may be in genuine conflict, and the year asks for the honesty to engage with both rather than allowing the comfort of the spiritual to evade the demands of the psychological or the force of the psychological to suppress the genuine needs of the spiritual.`,

  neptune_trine_pluto: `The solar return Neptune trine Pluto — a long-lasting generational aspect — brings a quality of genuine integration between spiritual depth and transformative psychological intensity, supporting inner development with both genuine openness and genuine depth. Creative and spiritual work benefits from the natural cooperation between inspiration and genuine psychological honesty, and the year tends to support profound inner development with a quality of natural grace and genuine lasting consequence.`,

  neptune_opposition_pluto: `The solar return Neptune opposite Pluto marks a year in which the tension between spiritual idealism and the compulsive demands of genuine psychological transformation is most externally visible — the beautiful and the genuinely true are pulling in different directions, and the year asks for the courage to honour both rather than allowing the comfort of spiritual aspiration to evade the genuine demands of what Pluto is insisting upon.`,
};
