// src/content/aspects_mars.ts
// Solar Return: SR Mars aspects to other SR planets and Ascendant
// Key format: "mars_aspect_planet" — all lowercase, e.g. "mars_conjunction_jupiter"
// Aspects covered: conjunction, sextile, square, trine, opposition (5 major)
// Planets aspected: Jupiter, Saturn, Uranus, Neptune, Pluto, Ascendant
// (Sun–Mars in aspects_sun.ts, Moon–Mars in aspects_moon.ts,
//  Mercury–Mars in aspects_mercury.ts, Venus–Mars in aspects_venus.ts)
// Sources: Mary Fortier Shea "Planets in Solar Returns" (3rd ed.) — primary;
// Cafe Astrology SR series; Robert Hand "Planets in Transit"
// Entries: 3-4 sentences

export const ASPECTS_MARS: Record<string, string> = {

  // MARS–JUPITER
  mars_conjunction_jupiter: `The solar return Mars conjunct Jupiter is one of the most energetically expansive and broadly fortunate aspect patterns in a solar return, combining Jupiter's genuine opportunity and optimistic confidence with Mars's drive, physical vitality, and willingness to act decisively on what is wanted. The year tends to bring genuine forward momentum to personal and professional goals, and the combination of confidence and action produces results that more timid or more passive years do not. Physical energy is exceptional and benefits from deliberate direction toward genuinely worthwhile goals. The risk is the overextension that this aspect consistently produces — the confidence to take on more than is sustainable and the drive to pursue it past the point of honest assessment.`,

  mars_sextile_jupiter: `The solar return Mars sextile Jupiter brings a quality of easy productive confidence, well-directed physical energy, and genuine optimism in personal and professional initiative to the year. The drive to act and the sense of genuine opportunity are in comfortable alignment, and the year tends to reward decisive action with genuine results without the overextension and impulsiveness of stronger Mars–Jupiter contacts. Physical vitality is good and sustained, and the year is well-suited to active pursuit of significant goals with a quality of natural forward momentum and genuine confidence.`,

  mars_square_jupiter: `The solar return Mars square Jupiter marks a year of genuine tension between personal drive and the expansive opportunities that Jupiter promises — the impulse to act is strong, the sense of possibility is genuinely large, but the square means that energy and opportunity are not yet fully aligned, requiring more honest effort to bridge the gap than easier aspects provide. Over-extension, impulsive action driven by optimism rather than honest assessment, and the tendency to commit to more than can be genuinely sustained are characteristic risks. The year is most productive when Jupiter's genuine confidence is disciplined by honest assessment of what Mars can actually deliver.`,

  mars_trine_jupiter: `The solar return Mars trine Jupiter brings a quality of easy, well-directed physical energy, genuine productive confidence, and natural forward momentum to the year's personal and professional initiatives. Drive and opportunity are in natural alignment, and the year tends to reward decisive action with genuine results and the sense that the world is genuinely cooperating with what you are working toward. Physical vitality is strong and sustainable, competitive situations tend to resolve favourably, and the year is well-suited to significant personal and professional initiatives that require both genuine confidence and genuine sustained effort.`,

  mars_opposition_jupiter: `The solar return Mars opposite Jupiter marks a year in which the most expansive opportunities and the most genuine forward momentum arrive primarily through engagement with others — partners, competitors, or the broader world provide the openings and the opposition that drives genuine productive effort. The risk is over-extension in response to others' enthusiasm or confidence, or the dissipation of real personal energy in reactive pursuit of what others have initiated rather than what you have genuinely chosen. The year is most productive when the genuine confidence Jupiter provides is directed by honest personal choice rather than simply animated by the energy of significant others.`,

  // MARS–SATURN
  mars_conjunction_saturn: `The solar return Mars conjunct Saturn is one of the most demanding aspect patterns in a solar return, placing the full weight of Saturn's discipline and limitation directly on the drive and physical vitality that Mars governs — action is slowed, frustrated, and subjected to a quality of resistance and scrutiny that can feel genuinely debilitating in the short term. The year asks that every action be genuinely considered, every expenditure of energy honestly assessed against what it is actually worth, and every goal subjected to the hard question of whether it is genuinely achievable and genuinely worth the effort. What is accomplished through this year's disciplined effort tends to be more genuinely solid and more lastingly meaningful than what is produced in years when drive meets less resistance.`,

  mars_sextile_saturn: `The solar return Mars sextile Saturn brings a quality of disciplined productive energy, patient strategic drive, and genuine effectiveness in the sustained pursuit of significant goals to the year without the frustration and constriction of stronger Saturn contacts. Action is more carefully considered and more honestly directed than in more impulsive years, and the year tends to reward sustained, strategic effort with genuine results that are built to last. Physical energy is reliable and well-directed, and the year is well-suited to long-term projects requiring the combination of genuine drive and genuine patience.`,

  mars_square_saturn: `The solar return Mars square Saturn marks a year of genuine and sometimes seriously demanding tension between the drive to act and the limiting, disciplining weight of Saturn's demands — frustration, blocked initiative, and the sense that effort is consistently meeting resistance that exceeds what the situation requires are characteristic experiences. The year asks for genuine patience and genuine strategic intelligence — the willingness to work around obstacles rather than simply driving harder into them, and to find the productive channel for genuine drive within the constraints Saturn is imposing. What is accomplished through honest engagement with the year's resistance tends to be more genuinely earned than what comes more easily.`,

  mars_trine_saturn: `The solar return Mars trine Saturn brings a quality of disciplined productive drive, strategic patience, and genuine effectiveness in the sustained pursuit of significant and lasting goals to the year. Action is well-directed and genuinely sustained, and the combination of Mars's energy and Saturn's structural discipline produces a quality of productive effort that neither planet achieves as effectively alone. Physical energy is reliable and honestly directed, and the year is well-suited to the most demanding long-term personal and professional projects — those that require both genuine drive and genuine patience to bring to completion.`,

  mars_opposition_saturn: `The solar return Mars opposite Saturn marks a year in which the most demanding disciplinary constraints and the most significant resistance to personal initiative arrive through others — authority figures, institutions, or significant partners impose limitations on personal drive and action that feel externally generated but that are ultimately asking the most honest questions about where genuine effort is actually directed and whether it is genuinely worthy of the energy being expended. The year tends to sharpen strategic intelligence and genuine discipline in those who engage honestly with the external resistance rather than simply resenting it.`,

  // MARS–URANUS
  mars_conjunction_uranus: `The solar return Mars conjunct Uranus marks a year of electric, unpredictable, and sometimes explosive personal energy — the drive to act is fused with Uranus's sudden, disruptive, and liberating impulse in ways that produce both exceptional creative and physical energy and a quality of impulsiveness that can generate genuine consequences before reflection is possible. The year tends to bring sudden bursts of decisive action, unexpected physical events requiring rapid response, and a quality of urgent aliveness that is both compelling and genuinely demanding of conscious management. The energy of this aspect is most productively directed when you maintain enough self-awareness to choose where it goes rather than simply riding it wherever it leads.`,

  mars_sextile_uranus: `The solar return Mars sextile Uranus brings a quality of creative physical energy, productive independence, and genuine openness to innovative approaches to getting things done to the year without the impulsive unpredictability of stronger Uranus contacts. The drive to act and the impulse toward genuine originality and independence are in comfortable alignment, and the year tends to reward those who bring both decisive action and genuine creative departure from established methods to what they are pursuing. Physical energy is more alive and more inventive than in more settled years.`,

  mars_square_uranus: `The solar return Mars square Uranus marks a year of genuine tension between the drive to act and the disruptive, liberating impulse of Uranus — the impulse to act decisively and the impulse to break free from established patterns are both strong, and neither is reliably subject to the other's constraints, producing a quality of erratic, sometimes explosive, and genuinely unpredictable energy. Accidents, unexpected physical events, and situations requiring rapid adaptation are more characteristic of this year than of others. The year benefits most from deliberate attention to where and how energy is being directed, and from the recognition that the disruptions it produces are consistently pointing toward something more genuinely authentic.`,

  mars_trine_uranus: `The solar return Mars trine Uranus brings a quality of electric creative energy, productive independence, and genuine effectiveness in innovative and unconventional approaches to action and initiative to the year. Drive and originality are in natural alignment, and the year tends to reward those who act with both genuine confidence and genuine departure from established methods with a quality of forward momentum and natural effectiveness that more conventional years do not produce. Physical energy is inventive and alive, and the year is well-suited to any endeavour that benefits from the combination of decisive action and genuine creative originality.`,

  mars_opposition_uranus: `The solar return Mars opposite Uranus marks a year in which the most disruptive, liberating, and genuinely unpredictable challenges to personal initiative arrive through others — partners, competitors, or unexpected external events disrupt established action plans and force rapid adaptation in ways that cannot be anticipated or managed through ordinary strategic planning. The year tends to reveal what genuine personal drive is actually made of when it is required to operate in conditions of genuine uncertainty and genuine external disruption rather than in the more controlled conditions that careful planning provides.`,

  // MARS–NEPTUNE
  mars_conjunction_neptune: `The solar return Mars conjunct Neptune marks a year in which personal drive and action are dissolved in Neptune's boundary-dissolving influence — the clarity of direction and purpose that Mars requires for genuine effectiveness is softened, redirected toward the spiritual and the imaginative, and sometimes simply confused in ways that make decisive action more difficult than in other years. Creative, healing, and spiritually motivated action are strongly supported — the fusion of drive and imagination can produce genuinely inspired work when the direction is genuinely aligned with inner calling. The risk is the dissipation of genuine energy in the pursuit of goals that are more beautiful than achievable, or in service of others' needs at the expense of honest self-direction.`,

  mars_sextile_neptune: `The solar return Mars sextile Neptune brings a quality of inspired motivation, compassionate personal drive, and genuine creative energy that is aligned with something larger than purely personal ambition to the year. The drive to act and the inspiration of Neptune's imaginative and spiritual influence work in comfortable cooperation, and the year tends to support creative, healing, and spiritually motivated action with a quality of genuine effectiveness and genuine inner alignment. Physical energy is most reliably sustained when directed toward what feels genuinely meaningful rather than merely achievable.`,

  mars_square_neptune: `The solar return Mars square Neptune marks a year of genuine tension between the drive to act decisively and Neptune's dissolving, confusing influence on the clarity of direction and purpose — energy may be misdirected, goals may prove less achievable than they initially appeared, and the line between genuine inspired motivation and the self-deceptive pursuit of goals that serve the imagination more than the actual circumstances is characteristically difficult to maintain. The year benefits from grounded external perspective on the direction of personal effort and from the honest willingness to verify that what is being pursued is actually achievable and actually real.`,

  mars_trine_neptune: `The solar return Mars trine Neptune brings a quality of inspired creative energy, compassionate motivated drive, and genuine alignment between action and something larger than purely personal ambition to the year with enough ease that Neptune's gifts are more available than its risks. Creative and spiritually motivated action are naturally effective and genuinely sustained, and the year tends to support any endeavour that requires both the willingness to act decisively and the capacity to be guided by genuine inner inspiration rather than external expectation alone. Physical energy is most productive when directed toward what is genuinely meaningful.`,

  mars_opposition_neptune: `The solar return Mars opposite Neptune marks a year in which the dissolving, confusing quality of Neptune arrives primarily through others — partners, competitors, or the broader circumstances of the year may not be fully honest about their intentions or capabilities, and the temptation to direct genuine personal energy toward goals or relationships that are not what they appear is unusually strong. The year benefits from grounded honest assessment of where personal effort is actually going and what it is actually producing, and from the recognition that the most inspired-seeming directions are not always the most genuinely fruitful.`,

  // MARS–PLUTO
  mars_conjunction_pluto: `The solar return Mars conjunct Pluto is one of the most intensely powerful and most demanding aspect patterns in a solar return, fusing Mars's drive and physical vitality with Pluto's compulsive, transformative, and sometimes ruthless intensity in ways that produce both exceptional focused power and genuine risk of coercion, obsession, and the kind of driven pursuit that exceeds what honest values would sanction. When directed toward genuinely worthwhile goals, the focused intensity of this aspect produces results that more diffuse years cannot approach. Power dynamics in personal and professional life are highlighted with unusual force, and the year asks for genuine honesty about where personal power is being directed and whether the means being used are genuinely justified by the ends being pursued.`,

  mars_sextile_pluto: `The solar return Mars sextile Pluto brings a quality of focused personal power, penetrating strategic intelligence, and genuine effectiveness in the pursuit of significant and transformative goals to the year without the obsessive intensity of stronger Pluto contacts. Drive is concentrated rather than scattered, and the year tends to reward those who direct genuine personal energy toward genuinely significant goals with a quality of natural effectiveness and genuine transformative impact. Physical vitality is strong and strategically directed, and the year is well-suited to significant personal and professional initiatives that require sustained focused power.`,

  mars_square_pluto: `The solar return Mars square Pluto marks a year of genuine and sometimes seriously demanding tension between personal drive and the compulsive, transformative pressure of Pluto's intensity — the impulse to pursue what is wanted with full force meets a quality of resistance and depth that ordinary assertion cannot simply override. Power struggles in personal and professional life may be more intense and more consequential than in other years, and the year tends to surface the most honest questions about where genuine personal power lies and whether the methods being used to exercise it are genuinely aligned with honest values. The year rewards genuine strategic intelligence and honest self-assessment over sheer force.`,

  mars_trine_pluto: `The solar return Mars trine Pluto brings a quality of exceptional focused power, strategic depth, and genuine transformative effectiveness in the pursuit of significant personal and professional goals to the year. Drive and the capacity for profound, irreversible impact are in natural alignment, and the year tends to reward those who direct genuine personal energy toward genuinely significant goals with a quality of focused effectiveness and genuine authority that more diffuse years cannot produce. The year is well-suited to the most demanding and most consequential personal and professional initiatives — those that require both sustained drive and genuine depth to bring to meaningful completion.`,

  mars_opposition_pluto: `The solar return Mars opposite Pluto marks a year in which the most intense and most transformative power dynamics arrive through others — significant competitors, authority figures, or the compulsive pressure of external circumstances impose challenges to personal drive and initiative that require genuine courage, genuine strategic intelligence, and the honest willingness to engage with genuine opposition rather than simply asserting past it. Power struggles in personal and professional life may be unavoidable, and the year tends to reveal what genuine personal power is actually made of when it is required to operate in the presence of something genuinely more powerful.`,

  // MARS–ASCENDANT
  mars_conjunction_ascendant: `The solar return Mars conjunct the Ascendant places the year's drive, physical vitality, and assertive energy directly on the surface of how you meet the world — you are more physically present, more assertive, and more energetically compelling than in years when Mars is more withdrawn, and others tend to experience you as more forceful and more personally directed than usual. The year strongly supports decisive personal initiative, competitive situations, and any endeavour that requires the willingness to go first and the physical and personal energy to sustain the effort. The risk is the tendency to assert more forcefully than situations require, generating unnecessary opposition through energy that would be more productively directed elsewhere.`,

  mars_sextile_ascendant: `The solar return Mars sextile the Ascendant brings a quality of easy personal confidence, productive physical energy, and natural assertiveness in the way you meet the world and the people in it to the year. Others tend to experience you as more energised and more decisively engaged than in more passive years, and the year tends to support personal and professional initiatives with a quality of natural forward momentum and genuine physical confidence. The year favours any endeavour that benefits from the willingness to act decisively and to bring genuine personal energy to what is being pursued.`,

  mars_square_ascendant: `The solar return Mars square the Ascendant marks a year in which there is genuine tension between personal drive and the way that drive is received and responded to in the world — the energy and assertion you are bringing may be landing with more friction than you intend, generating opposition or resistance that redirects genuine effort into the management of conflict rather than the pursuit of chosen goals. The year benefits from honest attention to how personal assertion is being received and from the willingness to modulate the force of approach when the situation genuinely calls for engagement rather than confrontation.`,

  mars_trine_ascendant: `The solar return Mars trine the Ascendant brings a quality of natural personal authority, easy physical confidence, and genuine assertive effectiveness in the way you meet the world to the year. Personal drive and the way you come across are in natural alignment — others experience you as more energised, more decisively present, and more genuinely compelling than in other years, and the year tends to reward active personal initiative with a quality of natural effectiveness and genuine forward momentum. Leadership through personal energy and genuine commitment rather than through authority alone is particularly well-supported.`,

  mars_opposition_ascendant: `The solar return Mars opposite the Ascendant — conjunct the Descendant — marks a year in which the most significant expressions of personal drive and the most demanding competitive dynamics arrive through significant one-to-one relationships rather than through solo personal initiative. Partners, competitors, or significant others in your personal and professional life bring both the energy and the opposition that drives genuine personal development, and the year's most significant achievements tend to arise through the productive friction of genuine engagement with others rather than through unilateral personal effort. The year strongly favours active competitive and collaborative engagement rather than the avoidance of genuine relational and professional challenge.`,
};
