// src/content/aspects_moon.ts
// Solar Return: SR Moon aspects to other SR planets and Ascendant
// Key format: "moon_aspect_planet" — all lowercase, e.g. "moon_conjunction_venus"
// Aspects covered: conjunction, sextile, square, trine, opposition (5 major)
// Planets aspected: Mercury, Venus, Mars, Jupiter, Saturn, Uranus, Neptune, Pluto, Ascendant
// (Sun–Moon aspects are stored in aspects_sun.ts)
// Sources: Mary Fortier Shea "Planets in Solar Returns" (3rd ed.) — primary;
// Cafe Astrology SR series; Robert Hand "Planets in Transit"
// Entries: 3-4 sentences

export const ASPECTS_MOON: Record<string, string> = {

  // MOON–MERCURY
  moon_conjunction_mercury: `The solar return Moon conjunct Mercury marks a year in which feeling and thinking are unusually intertwined — you process experience through a simultaneous emotional and intellectual lens, and what you think and what you feel about any situation arrive together rather than in sequence. Communication is more emotionally alive and more personally invested than in years when the mind and heart operate at greater distance from each other. Writing, journaling, and the verbal articulation of inner experience are particularly productive and sometimes revelatory. The year favours work that draws on both analytical intelligence and genuine emotional resonance.`,

  moon_sextile_mercury: `The solar return Moon sextile Mercury brings a quality of easy communication between the emotional and intellectual dimensions of experience — feelings can be articulated clearly, and thinking is naturally informed by emotional attunement without being overwhelmed by it. Conversations and written communications benefit from a quality of genuine warmth and intellectual clarity working in natural cooperation. The year favours any work that requires both emotional sensitivity and analytical precision, and relationships are nourished by the ease with which genuine feeling can be expressed and genuinely received.`,

  moon_square_mercury: `The solar return Moon square Mercury marks a year in which feelings and thoughts are in genuine tension — what you feel and what you think may be pointing in different directions, and the attempt to communicate inner experience clearly is more demanding than in years when heart and mind are in closer alignment. Misunderstandings in communication are more likely, and the tendency to intellectualise what would benefit from being simply felt — or to be flooded by emotion when clear thinking is required — is a characteristic challenge. The year benefits from deliberate attention to which mode of processing is actually needed in any given situation.`,

  moon_trine_mercury: `The solar return Moon trine Mercury brings exceptional ease in communicating emotional experience — feelings can be articulated with both clarity and genuine resonance, and the intellectual and emotional dimensions of experience inform each other with a quality of natural cooperation. Writing, teaching, counselling, and any work that requires the capacity to make inner experience both intelligible and genuinely felt are particularly well-supported. The year favours creative and communicative projects that draw equally on personal feeling and analytical intelligence.`,

  moon_opposition_mercury: `The solar return Moon opposite Mercury marks a year in which the emotional and intellectual dimensions of experience are in visible and sometimes demanding tension — what you feel and what you think about any situation are pulling in different directions, and the attempt to hold both honestly requires more conscious effort than harmonious Moon–Mercury contacts provide. Public communication may be at odds with private feeling, or the need for emotional honesty may conflict with the more measured approach that effective intellectual communication requires. The year is most productive when you resist the temptation to resolve the tension by simply suppressing one dimension in favour of the other.`,

  // MOON–VENUS
  moon_conjunction_venus: `The solar return Moon conjunct Venus marks a year of exceptional emotional warmth, relational ease, and genuine pleasure in the company of people you care about. The emotional and aesthetic dimensions of experience are in natural alignment — you feel most yourself when surrounded by beauty, by genuine connection, and by the particular quality of warmth that this aspect consistently provides. Creative work benefits from a natural integration of emotional sensitivity and aesthetic sensibility. The year is well-suited to the deepening of significant relationships, artistic projects, and any endeavour that requires the capacity to make others genuinely feel seen and genuinely valued.`,

  moon_sextile_venus: `The solar return Moon sextile Venus brings a quality of easy emotional warmth, relational grace, and genuine pleasure in the texture of daily life and significant relationships. The year tends to be personally pleasant and relationally harmonious without the intensity of stronger Venus contacts — people around you tend to be more cooperative and more genuinely kind, and the emotional environment has an overall quality of comfort and genuine goodwill. Creative and aesthetic sensibility is heightened in a way that is productive and pleasurable rather than demanding. The year rewards those who actively appreciate and engage with what is genuinely good in their lives.`,

  moon_square_venus: `The solar return Moon square Venus marks a year of genuine tension between emotional needs and the desire for relationship, beauty, and pleasure — what you need to feel emotionally secure and what you want from your closest relationships may be in conflict in ways that require honest negotiation rather than comfortable assumption. Creative work may be frustrated by the gap between emotional vision and aesthetic execution. Relationships benefit from the willingness to express emotional needs directly rather than expecting them to be met through the indirect route of simply providing more warmth and hoping for reciprocity.`,

  moon_trine_venus: `The solar return Moon trine Venus is one of the most personally pleasant aspect patterns in a solar return, bringing emotional warmth, relational ease, and genuine aesthetic pleasure to the year with a quality of natural grace. Significant relationships are more harmonious and more genuinely nourishing than in other years, and the emotional environment has an overall quality of ease and genuine goodwill. Creative work benefits from the natural integration of emotional sensitivity and aesthetic sensibility that this aspect provides. The year is well-suited to artistic projects, the deepening of meaningful relationships, and the genuine enjoyment of what is beautiful and sustaining.`,

  moon_opposition_venus: `The solar return Moon opposite Venus marks a year in which emotional needs and the demands of relationship are in visible tension — the need for genuine security and emotional depth may conflict with the pleasures and social demands of the relational world, or the desire for closeness and beauty may work against the more private emotional needs that the year is also asking to be honoured. Creative work may involve the same tension between what is emotionally true and what is aesthetically pleasing. The year is most productive when both dimensions are engaged honestly rather than one being sacrificed to the other.`,

  // MOON–MARS
  moon_conjunction_mars: `The solar return Moon conjunct Mars marks a year in which emotional life and personal drive are intensely intertwined — feelings arrive with more urgency and more force than in other years, and the impulse to act on what is felt is unusually strong and unusually immediate. Emotional reactivity is heightened, and the line between genuine passionate engagement and impulsive emotional action can be difficult to maintain. The year tends to bring situations that require both emotional courage and the capacity to act decisively rather than simply react to what is being felt. Physical energy is high and benefits from deliberate direction.`,

  moon_sextile_mars: `The solar return Moon sextile Mars brings a quality of emotional confidence, energetic personal warmth, and productive alignment between feeling and action to the year. The impulse to act on what you genuinely feel is present without the reactivity and impulsiveness of stronger Moon–Mars contacts, and the year tends to support decisive personal action that is informed by genuine emotional attunement rather than driven by emotional urgency. Physical vitality is good, and the year rewards those who bring both genuine feeling and genuine initiative to what they pursue.`,

  moon_square_mars: `The solar return Moon square Mars marks a year of genuine tension between emotional life and personal drive — feelings and the impulse to act are in conflict in ways that can produce both exceptional passionate energy and genuine difficulty with emotional reactivity and impulsive action. The frustration of emotional needs can translate quickly into anger or confrontational behaviour, and relationships may carry more friction and more heat than in other years. The year benefits most from the deliberate channelling of the considerable energy this aspect generates into productive and genuinely chosen action rather than reactive engagement with provocation.`,

  moon_trine_mars: `The solar return Moon trine Mars brings a quality of easy, well-directed emotional energy and personal courage to the year — feelings and the drive to act on them are in natural alignment, and the year tends to support decisive, emotionally genuine action with a quality of forward momentum and natural effectiveness. Physical vitality is strong and sustainable, and the year rewards those who bring both genuine passion and genuine initiative to what matters most to them. Leadership that draws on personal warmth and genuine conviction rather than authority alone is particularly well-supported.`,

  moon_opposition_mars: `The solar return Moon opposite Mars marks a year in which the tension between emotional needs and the drive to act arrives primarily through conflict with significant others — partners, colleagues, or family members may push against your emotional boundaries or compete with your personal goals in ways that require genuine and sustained engagement rather than simple assertion or withdrawal. The year tends to surface the most honest questions about what you are actually feeling and what you are actually willing to fight for. What is worked out through the year's friction tends to be more genuinely and more honestly owned than what is simply assumed in more comfortable years.`,

  // MOON–JUPITER
  moon_conjunction_jupiter: `The solar return Moon conjunct Jupiter marks a year of genuine emotional expansiveness, warmth, and a quality of inner abundance that supports both personal wellbeing and the generous engagement with others that Jupiter always encourages. The emotional world feels more spacious than in other years, and the year tends to bring genuine good fortune in domestic, family, and personal life alongside the broader optimism and opportunity that Jupiter's presence always signals. The risk is the same as all Moon–Jupiter contacts — emotional excess, over-extension in the service of others' needs, or a tendency to feel so expansive that the honest limits of what is sustainable are exceeded.`,

  moon_sextile_jupiter: `The solar return Moon sextile Jupiter brings a quality of easy emotional warmth, genuine generosity, and productive optimism to the year's personal and domestic life. Family relationships and the domestic sphere tend to be more harmonious and more genuinely rewarding than in other years, and the year has an overall quality of emotional ease and genuine good fortune. The impulse toward generosity and toward the broad engagement with life that Jupiter always encourages is present without the excess and over-extension of stronger Jupiter contacts. The year is most rewarding when you actively engage with the genuine goodwill and opportunity it makes available.`,

  moon_square_jupiter: `The solar return Moon square Jupiter brings the tension of emotional overextension — the desire for emotional abundance, domestic expansion, or generous engagement with others exceeds what is actually sustainable or practically available, and the gap between what is wished for and what is genuinely possible requires honest reckoning. The impulse toward excess in emotional and domestic life — overspending on the home, over-committing to family or community obligations, or indulging emotional needs beyond what is genuinely good for you — is a characteristic risk. The year is most productive when Jupiter's genuine expansiveness is paired with honest assessment of actual limits.`,

  moon_trine_jupiter: `The solar return Moon trine Jupiter brings genuine emotional abundance, domestic harmony, and a quality of inner expansiveness and warmth that supports both personal wellbeing and the generous engagement with others that makes life genuinely rewarding. Family relationships tend to be more harmonious and more genuinely nourishing than in other years, and the domestic sphere has an overall quality of ease and genuine good fortune. Creative and personal projects benefit from the natural alignment between emotional generosity and the broader optimism that Jupiter always provides. The year is well-suited to family expansion, domestic improvement, and the deepening of the relationships that matter most.`,

  moon_opposition_jupiter: `The solar return Moon opposite Jupiter marks a year in which emotional abundance and genuine good fortune arrive primarily through others and through the domestic and relational world rather than through solo effort or inner expansion alone. Partners, family members, or the broader social world may provide the expansive opportunities and genuine warmth that Jupiter promises — but the opposition means those gifts require genuine reciprocal engagement and honest relationship rather than passive reception. Over-reliance on others' generosity, or over-extension in emotional response to others' enthusiasm, are the characteristic risks to navigate.`,

  // MOON–SATURN
  moon_conjunction_saturn: `The solar return Moon conjunct Saturn marks a year in which emotional life is under Saturn's full disciplinary weight — feelings must be earned rather than simply felt, emotional needs may go unmet in ways that require genuine patience and genuine self-sufficiency, and the year may carry a quality of emotional austerity that is demanding but ultimately productive of genuine emotional maturity. Family and domestic responsibilities weigh more heavily, and the relationship with a parent or significant elder may be more demanding or more sobering than in other years. What is built in the emotional life under this aspect tends to be genuinely solid — less warm and less comfortable than Jupiter years, more honestly and more lastingly yours.`,

  moon_sextile_saturn: `The solar return Moon sextile Saturn brings a quality of emotional maturity, disciplined feeling, and genuine reliability in the emotional life without the austerity and constriction of stronger Saturn contacts. You are more emotionally steady and more genuinely self-sufficient than in other years, and the relationships that matter most benefit from a quality of honest, patient engagement that is more reliably sustaining than warmer but less grounded emotional styles. Domestic responsibilities are managed with more genuine care and competence, and the year rewards those who bring both genuine feeling and genuine discipline to what they are building.`,

  moon_square_saturn: `The solar return Moon square Saturn marks a year of genuine emotional difficulty — the need for warmth, security, and genuine emotional connection is in tension with Saturn's demands for self-sufficiency, discipline, and the honest acknowledgment of limitation. Emotional needs may be frustrated or go unmet in ways that require more inner resource than is comfortably available, and the year may carry a quality of emotional isolation or heaviness that benefits from deliberate and honest attention rather than stoic endurance. The year tends to produce genuine emotional maturity in those willing to engage honestly with what it is actually asking, rather than simply waiting for the difficulty to pass.`,

  moon_trine_saturn: `The solar return Moon trine Saturn brings a quality of emotional steadiness, genuine reliability, and the particular warmth that comes from feeling genuinely grounded and genuinely accountable in the emotional life. Relationships benefit from a quality of honest and patient engagement that is more sustainably nourishing than the warmer but less grounded emotional styles of other years. Domestic and family responsibilities are managed with genuine competence and care. The year is well-suited to the building of emotional foundations that are genuinely solid — less exciting than Jupiter years, more reliably supportive of what is actually being constructed for the long term.`,

  moon_opposition_saturn: `The solar return Moon opposite Saturn marks a year in which the demands of emotional discipline, limitation, and honest self-sufficiency arrive primarily through significant others — partners, authority figures, or family members who are less emotionally available than you need, or who impose constraints and expectations that feel cold and demanding. The year tends to surface the most honest questions about where genuine emotional support actually comes from and what it genuinely costs to maintain. What is worked out through the year's emotional restraint tends to be more genuinely and more honestly earned than the warmer but less tested emotional security of other years.`,

  // MOON–URANUS
  moon_conjunction_uranus: `The solar return Moon conjunct Uranus marks a year of electric emotional unpredictability — moods shift suddenly and without warning, the domestic and emotional sphere is subject to unexpected disruption, and the need for personal freedom within emotional life is at its most urgent and least negotiable. The year may bring sudden changes to living arrangements, family circumstances, or significant emotional relationships that were not planned and cannot easily be reversed. What the disruption is consistently pointing toward is a more authentic and more genuinely chosen emotional life — one that has been cleared of the accumulated habit that passes for security in less disrupted years.`,

  moon_sextile_uranus: `The solar return Moon sextile Uranus brings a quality of productive emotional originality, genuine openness to change, and the capacity for creative departure from established emotional patterns without the destabilising intensity of stronger Uranus contacts. The emotional life is more alive and more genuinely interesting than in more settled years, and the year tends to support the kind of gradual but genuine emotional evolution that feels liberating rather than threatening. New domestic arrangements, creative departures, and the willingness to feel in genuinely new ways are supported with a quality of easy forward momentum.`,

  moon_square_uranus: `The solar return Moon square Uranus marks a year of genuine tension between the need for emotional security and the impulse toward personal freedom and radical departure from established patterns — the emotional life is being disrupted in ways that feel destabilising rather than liberating, at least in the short term. Unexpected developments in home, family, or significant emotional relationships may force rapid adaptation. The year benefits from the recognition that what is being disrupted in the emotional life was often less genuinely secure than it appeared, and that what follows the disruption tends to be more honestly chosen.`,

  moon_trine_uranus: `The solar return Moon trine Uranus brings a quality of productive emotional originality, genuine openness to change, and the capacity to depart from established emotional patterns in ways that feel liberating rather than threatening. The emotional life is more alive and more genuinely interesting than in more settled years, and the year supports creative experimentation in domestic arrangements, emotional expression, and the genuinely new ways of feeling and relating that Uranus always makes available. The year is well-suited to those willing to embrace authentic emotional change without requiring the transition to be entirely comfortable.`,

  moon_opposition_uranus: `The solar return Moon opposite Uranus marks a year in which sudden emotional disruption arrives primarily through others — partners, family members, or unexpected external developments disrupt the emotional patterns and domestic arrangements that had seemed settled, in ways that require rapid adaptation and genuine emotional flexibility. The year tends to surface what in your emotional life and domestic circumstances was maintained through habit rather than genuine choice. What follows the disruption tends to be more authentically and more freely chosen than what preceded it, even when the disruption itself is genuinely unwelcome.`,

  // MOON–NEPTUNE
  moon_conjunction_neptune: `The solar return Moon conjunct Neptune marks a year of exceptional emotional sensitivity, highly permeable emotional boundaries, and a quality of compassionate attunement that is genuinely beautiful and genuinely demanding in equal measure. The capacity for empathy and for the direct experience of others' emotional states is at its most fully open, and the year may involve the kind of genuine emotional dissolution — the loss of the protective distance between your feelings and the world's — that is both creatively inspiring and genuinely exhausting. The year strongly supports creative work of emotional depth, spiritual practice, and compassionate service, while requiring deliberate attention to the maintenance of the emotional boundaries that make genuine presence possible.`,

  moon_sextile_neptune: `The solar return Moon sextile Neptune brings a quality of heightened emotional sensitivity, creative imagination, and genuine spiritual openness to the year's emotional life without the overwhelming permeability of stronger Neptune contacts. Intuition is reliable and creative inspiration is genuine, and the year tends to support artistic work, spiritual practice, and compassionate engagement with others with a quality of easy grace rather than demanding dissolution. The emotional life is more richly textured and more genuinely resonant than in more defended years, and the capacity for genuine empathy is a real and productive gift.`,

  moon_square_neptune: `The solar return Moon square Neptune marks a year in which emotional clarity is harder to maintain than usual — feelings are more easily confused with what is wished for, and the boundary between genuine emotional attunement and the projection of what you most need to find onto the people and situations around you is more difficult to hold. Self-deception in emotional life, idealisation of significant others, and a quality of emotional confusion that is difficult to resolve through ordinary means are characteristic challenges. The year benefits from grounded external perspective and from the honest willingness to distinguish between what is genuinely being felt and what is simply being imagined.`,

  moon_trine_neptune: `The solar return Moon trine Neptune brings a quality of genuine emotional depth, creative inspiration, and spiritual sensitivity to the year with enough ease that Neptune's gifts are more available than its risks. Intuition is reliable, the capacity for compassionate engagement with others is at its most fully available, and creative work of genuine emotional and spiritual resonance is strongly supported. The year is well-suited to artistic projects, spiritual practice, and any endeavour that benefits from the willingness to feel at full depth and to perceive what lies beneath the surface of ordinary experience.`,

  moon_opposition_neptune: `The solar return Moon opposite Neptune marks a year in which the dissolving, idealising quality of Neptune arrives primarily through significant others — people in your emotional life may not be fully honest about who they are or what they need, and the temptation to see what you most wish to find rather than what is actually present in your closest relationships is unusually strong. The year benefits from grounded honesty about what others are actually offering and from the deliberate maintenance of enough emotional clarity to distinguish genuine connection from the projection of need onto whoever happens to be available.`,

  // MOON–PLUTO
  moon_conjunction_pluto: `The solar return Moon conjunct Pluto marks a year of deep, compulsive, and sometimes overwhelming emotional intensity — feelings arrive with a force and a depth that ordinary emotional life rarely produces, and the year may involve genuine encounters with what has been most carefully repressed or avoided in the emotional life. Family dynamics may surface long-buried patterns with an urgency that demands honest engagement, and domestic circumstances may undergo significant and irreversible change. The year strongly supports genuine psychological depth work and the honest confrontation with whatever has been operating most powerfully below the threshold of conscious emotional life.`,

  moon_sextile_pluto: `The solar return Moon sextile Pluto brings a quality of emotional depth, psychological insight, and productive engagement with the deeper dimensions of feeling and inner life to the year without the overwhelming intensity of stronger Pluto contacts. The capacity for genuine psychological honesty — the willingness to look clearly at what is actually being felt and what is actually driving emotional responses — is heightened and genuinely productive. Significant emotional and domestic matters can be engaged with more depth and more genuine effectiveness than in years when the emotional life remains at the surface.`,

  moon_square_pluto: `The solar return Moon square Pluto marks a year of genuine tension between the need for emotional security and the compulsive pressure of Pluto's transformative intensity — feelings that have been suppressed or carefully managed surface with a force that disrupts the domestic and emotional patterns that had seemed settled. Power dynamics in family and domestic life may be more intense and more honestly demanding of attention than in other years. The year does not permit comfortable emotional avoidance — it rewards those who engage honestly with what is surfacing, and tends to force engagement on those who resist.`,

  moon_trine_pluto: `The solar return Moon trine Pluto brings a quality of genuine emotional depth, transformative psychological insight, and the particular authority that comes from feeling and knowing at full depth to the year. Significant emotional and domestic matters can be engaged with unusual effectiveness and genuine transformative power, and the capacity for honest psychological self-understanding is at its most naturally and most productively available. The year is well-suited to deep inner work, significant domestic or family transformation, and any endeavour that benefits from the willingness to operate from genuine emotional depth rather than managed surface.`,

  moon_opposition_pluto: `The solar return Moon opposite Pluto marks a year in which the most intense and most transformative emotional dynamics arrive through others — family members, significant partners, or external circumstances impose a quality of compulsive emotional pressure that requires genuine courage and genuine honesty to navigate rather than simply endure. Power struggles in domestic and family life may be unavoidable, and the year tends to surface the most honest questions about where genuine emotional power lies and what it is actually worth defending. What survives Pluto's opposition in the emotional life tends to be what is most genuinely and most irreversibly yours.`,

  // MOON–ASCENDANT
  moon_conjunction_ascendant: `The solar return Moon conjunct the Ascendant places the year's emotional life and instinctive responses directly on the surface of how you meet the world — you are more emotionally visible, more instinctively present, and more genuinely responsive to the emotional atmosphere of every situation than in years when the Moon is more withdrawn. Others read your emotional state more easily than usual, and the year tends to bring emotional themes directly into the foreground of personal and professional life rather than allowing them to remain private. The year strongly supports emotional honesty and the willingness to be genuinely seen.`,

  moon_sextile_ascendant: `The solar return Moon sextile the Ascendant brings a quality of easy emotional warmth, natural responsiveness, and genuine personal attunement to the way you meet the world and the people in it. Others tend to find you more approachable and more genuinely engaging than usual, and the emotional dimension of personal and professional interactions is more naturally and more productively available. The year favours any work that benefits from the capacity to make genuine emotional contact with others, and personal relationships benefit from the easy natural warmth this aspect consistently provides.`,

  moon_square_ascendant: `The solar return Moon square the Ascendant marks a year in which there is genuine tension between your emotional life and the way you present yourself to the world — what you feel privately and what you are able or willing to convey in your external presentation are in productive but sometimes frustrating misalignment. The emotional dimension of experience may feel harder to integrate into professional and public contexts, and the year may involve situations in which your emotional responses are at odds with the composed presentation that external circumstances seem to require. The year benefits from honest attention to this gap rather than simply managing it.`,

  moon_trine_ascendant: `The solar return Moon trine the Ascendant brings a quality of natural emotional warmth, genuine personal presence, and easy integration of feeling and self-presentation to the year. Your emotional life and the way you meet the world are in natural alignment, and others tend to experience you as more genuinely present and more authentically warm than in other years. Work that requires genuine emotional attunement — counselling, teaching, creative performance, leadership through genuine personal presence — is particularly well-supported. The year rewards those who allow their emotional intelligence to operate visibly rather than keeping it carefully private.`,

  moon_opposition_ascendant: `The solar return Moon opposite the Ascendant — conjunct the Descendant — marks a year in which the emotional life is most fully expressed and most productively engaged through significant relationships rather than through private inner experience alone. Others bring out your emotional depth in ways that would not occur in more solitary or more inwardly directed years, and the year's most significant emotional developments tend to arrive through what your closest relationships ask of you. Partnership, genuine emotional reciprocity, and the honest engagement with what others are genuinely feeling are the year's primary vehicles for emotional growth.`,
};
