// src/content/jupiter_in_houses.ts
// Solar Return: Jupiter in each of the 12 houses
// Sources: Mary Fortier Shea "Planets in Solar Returns" (3rd ed.) — primary;
// Cafe Astrology Solar Return series; Journeys Yearly Solar Return Report;
// Robert Hand "Planets in Transit" (for Jupiter house themes)
// NOTE: Jupiter's house position shows where expansion, opportunity, growth,
// and good fortune are most available for the year. It also shows where
// excess, overconfidence, and over-extension are the primary risks.
// Jupiter moves through approximately one sign per year, so its house
// placement shifts significantly from year to year based on SR location.

export const JUPITER_IN_HOUSES: Record<number, string> = {

  1: `Solar Return Jupiter in the first house is one of the most broadly fortunate placements in a solar return, bringing expansion, optimism, and a genuine quality of opportunity to your personal life and self-expression for the year. You approach the year with more confidence, more enthusiasm, and a broader sense of what is possible than in other years. Others respond to this quality — there is something genuinely compelling about a person who moves through the world with Jupiter's natural generosity and openness, and you are likely to attract support, goodwill, and helpful people more easily than usual. New personal initiatives are well-supported, and the year tends to bring tangible rewards for those who act on the confidence Jupiter provides. Physical vitality and general wellbeing are enhanced. The risk of Jupiter in the first house is expansion without discipline — the optimism of this placement can tip into overconfidence, overcommitment, and a tendency to take on more than can realistically be sustained. Weight gain is a common physical manifestation of Jupiter's excess in the first house. The year is most productive when you use Jupiter's expanded sense of possibility to pursue genuinely worthwhile goals with real follow-through, rather than simply feeling good about what might be possible.`,

  2: `Solar Return Jupiter in the second house brings expansion and opportunity to your financial life, your sense of personal value, and your relationship with what you own and enjoy. This is one of the most financially supportive Jupiter placements — income may increase, opportunities for financial gain present themselves, and the general material circumstances of your life are more expansive than in years when Jupiter is elsewhere. Business ventures, investments, and income-generating activities undertaken this year benefit from Jupiter's generous influence, though they require realistic planning to realise their potential. Your sense of self-worth expands alongside your financial circumstances — you may feel more confident in what you have to offer and more willing to ask for what you are genuinely worth. The desire for comfort, pleasure, and material enjoyment is strong. The risk is financial overextension — Jupiter's optimism in the second house can lead to overspending, over-borrowing, or investment decisions based on enthusiasm rather than sound assessment. The feeling of abundance can make the future seem more financially certain than it is. Generosity is genuine but needs to be balanced with prudence.`,

  3: `Solar Return Jupiter in the third house expands your intellectual world, your communication, and your local environment for the year. Your mind reaches further than usual — you are interested in more subjects, reading more widely, engaging with more ideas, and communicating with more people across a broader range. Writing and publishing projects benefit from Jupiter's expansive influence, particularly those aimed at a wider audience than you have previously reached. Teaching, lecturing, and sharing your knowledge in accessible ways are well-supported. Short trips are more frequent and often more rewarding. Relationships with siblings and those in your immediate community may be more generous and harmonious. The desire to learn and to share what you know is genuine and productive. The risk is intellectual overextension — too many subjects pursued without sufficient depth, too many writing or communication projects begun without adequate follow-through, or an overconfidence in your own expertise that closes you to what others have to teach you. The year is most productive when the genuine intellectual enthusiasm of Jupiter in the third is paired with the discipline to go deep rather than simply wide.`,

  4: `Solar Return Jupiter in the fourth house brings expansion and a quality of genuine fortunateness to your home, family, and private life for the year. Domestic circumstances tend to improve — you may move to a larger or more beautiful home, expand your living space, or find that your family life takes on a warmer and more abundant quality. Family relationships generally benefit from Jupiter's generosity and goodwill, and gatherings or family events may be more joyful and expansive than usual. Real estate matters tend to go well. Your inner life and sense of emotional security expand alongside your outer circumstances — this is a good year for therapy, inner work, or any form of personal development that builds genuine psychological foundations. The private, interior dimensions of your life feel more spacious and supported. The risk is over-investment in the domestic sphere at the expense of the outer world — Jupiter in the fourth can make home so comfortable and expansive that it becomes a retreat from necessary engagement with professional and social life. Family members may also make demands that exceed what is reasonable to provide, particularly if Jupiter receives challenging aspects.`,

  5: `Solar Return Jupiter in the fifth house is one of the most joyful and creative placements in a solar return, expanding the domains of pleasure, romance, creative expression, and self-enjoyment with genuine generosity. Creative work flourishes — whatever your medium of expression, Jupiter brings more ideas, more confidence, and a larger audience for what you produce. Romantic life is highlighted in a positive way: if you are single, this is a year in which a meaningful new connection is more likely; if partnered, the relationship benefits from a quality of warmth, generosity, and playful engagement. Children bring particular joy, and if you are considering starting or expanding a family, Jupiter in the fifth is a supportive indication. Leisure, recreation, and the genuine enjoyment of life are not just permitted but encouraged. The risk is excess in all fifth house domains — overindulgence in pleasure, financial recklessness through speculation or gambling, romantic overconfidence, or creative projects taken on at a scale that exceeds what can realistically be sustained. The year is most rewarding when you allow yourself genuine joy without losing the prudence that makes joy sustainable.`,

  6: `Solar Return Jupiter in the sixth house brings expansion and opportunity to your work, health, and daily routines for the year. Professional opportunities may arise through the quality and quantity of work you produce — Jupiter in the sixth rewards genuine effort with genuine recognition, and this is a good year to take on additional responsibilities, develop new professional skills, or push the boundaries of what you can accomplish in your day-to-day professional life. Working conditions may improve, and relationships with colleagues tend to be more harmonious and mutually supportive. Health generally benefits from Jupiter's expansive energy — this is a good year to establish genuinely sustainable health habits, to explore healing modalities that interest you, and to invest in your physical wellbeing with real commitment. The risk is overwork and the physical toll that comes with it — Jupiter in the sixth can generate so much productive energy that the natural limits of the body are exceeded. Weight gain and over-indulgence in comfort foods are also characteristic risks. Service to others, when engaged with genuine care and enthusiasm rather than anxious obligation, is deeply satisfying and often returns unexpected rewards.`,

  7: `Solar Return Jupiter in the seventh house brings expansion, goodwill, and a quality of genuine fortune to your closest relationships for the year. This is one of the most supportive placements for significant relationship developments — marriage, the beginning of a committed partnership, or the deepening of an existing relationship into something more formally acknowledged are all well-supported by Jupiter's presence in the house of partnership. Professional relationships and collaborative ventures also benefit: business partnerships begun or developed this year tend to be expansive and mutually rewarding. You attract more generous and broad-minded people into your close circle, and relationships in general have a warmer, more generous quality. Legal matters tend to resolve favourably. Your own capacity for generosity and understanding in relationships is enhanced. The risk is over-idealisation of partners — Jupiter in the seventh can see partners through an unrealistically flattering lens, and commitments made under the influence of this optimism may eventually require a more sober reassessment. Over-accommodation and excessive generosity in relationships can also create imbalances that are difficult to correct later.`,

  8: `Solar Return Jupiter in the eighth house brings expansion and opportunity to the domain of shared resources, transformation, deep intimacy, and the hidden dimensions of your life. Financial matters involving other people's money — inheritance, insurance settlements, investments managed by others, or financial arrangements with a partner — tend to develop more favourably than expected. Debts may be resolved or restructured more easily. Research, investigation, and any intellectual work that requires going beneath the surface of things benefits from Jupiter's expansive curiosity. Psychological and spiritual exploration are well-supported — this is an excellent year for therapy, for serious engagement with shadow material, or for any practice that facilitates genuine inner transformation. The quality of intimacy in close relationships may deepen significantly. The risk is excess in eighth house domains — financial over-extension through other people's resources, obsessive preoccupation with power or hidden matters, or a tendency to pursue transformation for its own sake rather than in service of genuine growth. At its best, Jupiter in the eighth is a year of profound inner expansion and unexpected material benefit through others.`,

  9: `Solar Return Jupiter in the ninth house is Jupiter in its home territory — the ninth house is ruled by Sagittarius and associated with the same themes of expansion, philosophy, higher learning, and broad horizon that Jupiter naturally governs. The result is a year of considerable expansiveness in the domains of higher education, long-distance travel, philosophical development, publishing, and the pursuit of meaning. This is an excellent year for advanced study, for completing or beginning a significant writing or publishing project, for meaningful long-distance travel, or for any engagement with religious, philosophical, or ethical questions that genuinely matters to you. Legal matters tend to resolve favourably. Your worldview expands — you encounter ideas, people, and experiences that genuinely change the way you understand yourself and the world. The risk of Jupiter in its own house is the same as always — excess and overconfidence — but now applied to the domain of beliefs and ideology. Philosophical dogmatism, overconfidence in one's own rightness, or an expansion of one's educational or publishing ambitions beyond what is realistic are the specific risks. The year is most productive when genuine intellectual humility accompanies the genuine intellectual expansion.`,

  10: `Solar Return Jupiter in the tenth house is one of the most professionally fortunate placements in a solar return, expanding your career prospects, public reputation, and worldly standing with genuine generosity. Professional opportunities arise, advancement is supported, and the world tends to see you in a more favourable and expansive light than in other years. Recognition for past effort is possible, and new professional roles or responsibilities may arrive that reflect a genuine increase in your status and influence. Relationships with authority figures tend to be more supportive and mutually beneficial. Your ambitions are larger than usual, and the year provides real opportunities to act on them. The risk is overextension of professional ambition — taking on more than can be sustained, making public commitments that exceed realistic capacity, or allowing professional expansion to dominate life at the expense of everything else. Reputation can also be over-inflated under Jupiter in the tenth, creating expectations that are difficult to consistently meet. The year is most productive when expanded professional opportunity is met with both genuine ambition and the discipline to deliver on what you promise.`,

  11: `Solar Return Jupiter in the eleventh house brings expansion, opportunity, and genuine good fortune to your social world, friendships, group involvements, and long-range aspirations. Your social circle expands in meaningful ways — new friendships formed this year may be genuinely significant, and existing friendships benefit from Jupiter's warm and generous influence. Group activities, collaborative projects, and community involvement all carry a quality of expansiveness and reward. Long-range goals that have been building receive support and forward movement — this is a year in which what you have been working toward begins to feel genuinely achievable. Financial gains through your professional network or reputation are possible. Involvement with groups, organisations, or movements that align with your values is particularly rewarding. The risk is over-commitment to social and collective activities at the expense of individual focus, or an excessive optimism about what can be achieved through group effort without adequate attention to the practical groundwork. Friends may also make demands that exceed what is reasonable to provide. At its best, a Jupiter in the eleventh year is one of genuine social abundance and meaningful progress toward what you are building for the future.`,

  12: `Solar Return Jupiter in the twelfth house is one of the most spiritually and psychologically supportive Jupiter placements, though its gifts are largely invisible from the outside. Jupiter operates here as a hidden protector — many people with this placement report a sense of being quietly supported, of things working out in ways they cannot fully explain, and of a quality of grace operating beneath the surface of their visible circumstances. Spiritual practice, inner work, therapy, charitable engagement, and any form of retreat or solitary reflection are genuinely rewarding and productive. Creative work done in private — writing, art, research — benefits from Jupiter's expansive curiosity and generous inner resources. The unconscious mind is more accessible, and what you discover in dreams, contemplation, and honest self-examination can be genuinely illuminating. The risk is that the hidden nature of this Jupiter leads to a sense of invisibility or disappointment when the year's gains do not manifest in obvious, external ways — Jupiter in the twelfth works on an inner timeline that does not always produce visible results within the year itself. Self-deception and an over-optimistic reading of situations that deserve more careful scrutiny are also risks. What is built inwardly this year, however, tends to become the foundation for more visible expansion in subsequent years.`,
};
