// src/content/mars_in_houses.ts
// Solar Return: Mars in each of the 12 houses
// Sources: Mary Fortier Shea "Planets in Solar Returns" (3rd ed.) — primary;
// Cafe Astrology Solar Return series; Journeys Yearly Solar Return Report
// NOTE: Mars's house position shows where your energy, drive, initiative,
// and assertiveness are most concentrated for the year. It also shows where
// conflict, impatience, and the risk of accidents or confrontation are highest.
// Check Mars's sign and aspects for HOW this energy expresses.
// Mars retrograde in the SR significantly changes the dynamic — see note below.

export const MARS_IN_HOUSES: Record<number, string> = {

  1: `Solar Return Mars in the first house is one of the most physically energising and personally assertive placements in a solar return. You approach the year with more drive, more competitive energy, and a stronger-than-usual need to act on your own initiative. Physical vitality is high — this is an excellent year to begin a fitness programme, take on physically demanding work, or pursue goals that require sustained personal effort and courage. You are less willing to wait, less inclined to defer, and more ready to push forward when others might hesitate. Leadership and independent action come naturally. The risk of this placement is considerable: Mars in the first house can express as impatience, aggression, or a self-centred drive that damages relationships and creates unnecessary opposition. Accidents and physical injuries are more likely when you act too quickly without sufficient awareness of your surroundings — the first house Mars year requires you to direct your energy consciously rather than letting it erupt reactively. Conflicts with others arise more readily. The year is most productive when the considerable energy of this placement is channelled into purposeful effort rather than reactive assertion.`,

  2: `Solar Return Mars in the second house directs your drive and energy toward financial matters, income generation, and the acquisition or protection of what you value. You are more motivated than usual to earn, to increase your income, or to take active steps to improve your financial situation. Work that requires direct effort, physical engagement, or competitive drive may generate financial rewards. You may also find yourself spending more energetically than usual — impulsive purchases or aggressive financial decisions are a risk when Mars activates the second house. Conflicts over money, possessions, or shared resources are possible. The values dimension of the second house becomes charged under Mars: you may feel strongly about what you believe is right and be willing to fight for it. Financially, the year rewards those who take initiative and pursue income actively rather than waiting for it to arrive. The risk is financial impulsiveness — spending or investing on the basis of enthusiasm rather than careful assessment. Major financial commitments made in anger or under pressure are likely to require significant correction later.`,

  3: `Solar Return Mars in the third house charges your communication, thinking, and local environment with energy, directness, and a degree of friction for the year. You say what you think with less filtering than usual, which can be refreshingly honest or abrasively blunt depending on the situation. Arguments with siblings, neighbours, or those in your immediate community are more likely. Written and spoken communications carry more force and urgency — this can make you a compelling advocate when the cause is right, but it can also create conflict when the directness exceeds what the relationship can absorb. Mental energy is high and can be productively channelled into research, debate, writing projects that require persistence, or any intellectual work that benefits from drive and determination. Short trips may be more numerous and occasionally stressful. Driving requires particular care — Mars in the third house is one of the indicators of traffic incidents or accidents in transit. The year rewards those who use their mental sharpness and communicative directness for purposeful goals rather than reactive arguments.`,

  4: `Solar Return Mars in the fourth house brings energy, tension, and drive into the private domain of home, family, and emotional life. There is likely to be more activity — and more conflict — on the domestic front than in other years. Home renovation and improvement projects are characteristic: you have the energy and motivation to tackle physical work around the home, and this can be productive if managed well. Family relationships may be more tense, with more open disagreement or confrontation than usual. If family dynamics have underlying tensions that have been avoided, this is the year they are likely to surface and demand direct engagement. You may feel less able to truly rest at home — the fourth house Mars year often has a quality of emotional intensity in the domestic space that makes it hard to completely switch off. Moving house is common, often with a degree of urgency or under pressure. The risk is that the home becomes a battleground rather than a sanctuary. The year is most productive when you channel the Mars energy into genuine improvement of your domestic situation rather than reactive conflict with those you live with.`,

  5: `Solar Return Mars in the fifth house brings energy, passion, and competitive drive into the domains of creativity, romance, pleasure, and self-expression. Romantic relationships have a strong physical and passionate dimension — new attractions are intense and compelling, and existing relationships benefit from renewed erotic energy and a willingness to pursue what you want directly. Creative work is energised and productive, particularly work that requires sustained effort, physical engagement, or a degree of competitive edge. Sports, physical recreation, and any pursuit that combines enjoyment with challenge are well-supported. If you have children, your interactions with them may be more energised and occasionally more fraught — patience may be in shorter supply than usual. Speculative ventures carry risk: the Mars enthusiasm for the fifth house can generate exciting ideas and overconfident financial decisions. The risk overall is impulsiveness in pursuit of pleasure — acting on desire without adequate consideration of consequences. At its best, a fifth house Mars year is one of passionate creative output and genuine romantic vitality.`,

  6: `Solar Return Mars in the sixth house directs your drive and energy toward work, health, and daily routines with considerable intensity for the year. You are highly productive in terms of sheer output — the capacity for sustained hard work is strong, and you may accomplish more in terms of professional tasks and daily responsibilities than in other years. This is an excellent year for disciplined physical training, for tackling a demanding work project, or for any goal that requires you to push through difficulty with persistence. However, the sixth house Mars also carries real health risks: overwork, exhaustion, and physical injury through over-exertion are all characteristic. Inflammation, fever, accidents involving tools or equipment, and conditions brought on by chronic stress are possibilities — attending to your physical limits is important. Conflict with colleagues or those you work alongside is more likely than usual. The working environment may feel tense or competitive. The year is most productive when you use the considerable work energy of this placement deliberately and sustainably, rather than burning yourself out in a burst of activity followed by collapse.`,

  7: `Solar Return Mars in the seventh house places the year's drive, conflict, and assertive energy squarely in the domain of your closest relationships. This is one of the more challenging Mars placements for relational harmony — disagreements, power struggles, and open conflict with partners, both romantic and professional, are more likely than in other years. If underlying tensions exist in a significant relationship, this is the year they are likely to come to open confrontation. This is not necessarily destructive: Mars in the seventh can clear the air, force honest engagement with what has been avoided, and ultimately produce more honest and sustainable relationships. Legal disputes and formal opposition are also possible — an adversary or opponent may become more significant this year. You may attract people who are themselves more assertive, aggressive, or Mars-ruled in their temperament. Alternatively, you may find yourself playing the more assertive role in relationships where you have previously been more accommodating. The year is most productive when you use the energy for honest, direct communication in relationships rather than reactive conflict.`,

  8: `Solar Return Mars in the eighth house is one of the more intense placements in a solar return, directing energy and drive into the domain of transformation, shared resources, deep intimacy, and the less comfortable dimensions of power and control. Financial matters involving other people's money — debt, taxes, insurance, inheritance, or a partner's financial situation — may require direct action and assertive engagement. Power dynamics in close relationships are heightened, and you may find yourself in situations where questions of control, dominance, or psychological pressure require careful navigation. Sexual energy is strong. Psychological investigation and the willingness to go to uncomfortable inner territory are supported by Mars's presence here — this is a good year for therapy, for honestly confronting self-defeating patterns, or for research into difficult subjects. The risks are significant: obsessive thinking, jealousy, manipulation in close relationships, and financial decisions made on impulse in areas of genuine complexity. Physical risks associated with surgery, extreme activities, or carelessness in high-stakes situations require attention. The transformation this placement can catalyse, when engaged honestly, is genuine and lasting.`,

  9: `Solar Return Mars in the ninth house directs your energy and drive toward the broader horizons of life — higher education, long-distance travel, philosophical conviction, publishing, and the pursuit of meaning beyond your immediate world. You are more passionate than usual about your beliefs and more willing to defend them actively — Mars in the ninth house can produce the crusader, the passionate teacher, the committed advocate for a cause. Academic work, publishing, and broadcasting benefit from the drive and determination Mars brings. Long-distance travel may be more physically demanding or involve a degree of urgency. Legal matters require active engagement and direct assertion of your position. The risk is dogmatism and self-righteousness — the ninth house Mars can become convinced of its own philosophical correctness and less open to the genuine learning that requires humility. Arguments about religion, ethics, or the law may become more heated than is useful. At its best, this is a year of passionate, purposeful engagement with the ideas and experiences that expand your world.`,

  10: `Solar Return Mars in the tenth house is one of the most career-activating placements in a solar return, directing your drive, ambition, and assertive energy toward your professional life and public reputation with considerable force. You are more ambitious than usual, more willing to compete openly for advancement, and more determined to make your mark professionally. Career initiatives taken this year have energy and momentum behind them, and significant professional moves — a new role, a promotion, a business launch, a public assertion of your position — are all supported by Mars's drive. You are more visible professionally, and your actions are more likely to attract attention — for better and worse. Conflict with authority figures, employers, or those above you in professional hierarchies is possible and may need to be navigated with more care than the Mars energy naturally suggests. The public may see a more assertive, driven version of you this year. The risk is professional aggression that creates enemies or damages a reputation that has taken years to build. Direct, purposeful professional effort produces the best results; reactive conflict with authority rarely does.`,

  11: `Solar Return Mars in the eleventh house brings energy, drive, and occasional friction into your friendships, group involvements, and long-range plans for the year. You are more active and assertive within the social and collective dimensions of your life — taking leadership roles in groups, pushing hard for goals you share with others, and pursuing your long-range aspirations with more determination than in previous years. This can be a productive year for collaborative projects that require someone willing to drive the work forward. However, conflicts within groups and friendships are more likely — you may find yourself disagreeing more openly with friends or colleagues, or finding that group dynamics carry more tension and competitiveness than is comfortable. Financial gains through your network or professional reputation are possible, but financial decisions made on impulse through social connections require scrutiny. The long-range goals you are pursuing may become a source of stress if the drive to achieve them outpaces the realistic timeline for their development. At its best, this is a year of energised, purposeful social engagement and genuine progress toward what you are building for the future.`,

  12: `Solar Return Mars in the twelfth house is one of the more psychologically complex Mars placements — the drive, assertiveness, and energy of Mars are operating largely beneath the surface of your conscious life, in the private and hidden domain of the twelfth house. You may find it difficult to assert yourself directly this year, or you may feel that your energy is being drained by circumstances that are not fully visible or understood. Self-defeating behaviour — patterns in which you inadvertently create the very difficulties you are trying to avoid — is a genuine risk when Mars operates in this house. The energy may also manifest as frustration without clear object, or as a tendency to work very hard in private on projects or goals that the world does not yet see. Solitary effort, behind-the-scenes work, and any project that benefits from sustained private effort are well-supported. Unconscious anger that has not been acknowledged can emerge in indirect or self-destructive ways. This is an important year for honest self-examination of your own role in the difficulties you encounter. Therapy, journaling, and any practice that brings unconscious material into the light is valuable. The year works best when hidden motivations are examined rather than acted upon blindly.`,
};
