// src/content/mc_signs.ts
// Solar Return: Midheaven (MC) in each of the 12 signs
// Sources: Cafe Astrology Solar Return series; Journeys Yearly Solar Return Report;
// Mary Fortier Shea "Planets in Solar Returns" (3rd ed.);
// James Eshelman "Interpreting Solar Returns"
// NOTE: The SR Midheaven describes the tone of your career, public life, reputation,
// and relationship with authority figures for the year. Its ruling planet's house
// position provides the specific arena of professional focus.

export const MC_SIGNS: Record<string, string> = {

  Aries: `With Aries on the Midheaven of your solar return, the year's professional and public life is charged with initiative, urgency, and a drive to take the lead. You are less willing than usual to wait for permission or the right moment — if something needs doing in your career or public life, your instinct is to act now and adjust later. New professional ventures begun under an Aries MC often move quickly and attract attention precisely because of the boldness with which they are pursued. Leadership roles and independent work are well-supported. The risk is impulsiveness: career decisions made too quickly, without adequate planning, can create problems that require significant energy to resolve later in the year. Conflicts with authority figures or colleagues who move at a different pace are possible. Physical energy is high and can be productively channelled into ambitious professional effort. Mars's house position in the solar return reveals the specific arena where your professional drive is most concentrated this year.`,

  Taurus: `With Taurus on the Midheaven of your solar return, career and public life take on a more deliberate, steady, and materially oriented quality. You are less interested in dramatic professional moves and more focused on building something durable — consolidating your position, increasing your income, or developing your skills and resources in ways that will sustain you long-term. Financial rewards from professional effort are possible, particularly if the year's work involves a practical skill, a creative talent, or the careful stewardship of resources. Your professional reputation benefits from a quality of reliability and groundedness. The risk is an over-conservative approach that causes you to miss opportunities requiring a degree of risk or flexibility, or a stubbornness in professional dealings that creates unnecessary friction. Venus's house position indicates where the year's professional pleasures, values, and financial rewards are most likely to emerge.`,

  Gemini: `With Gemini on the Midheaven of your solar return, the year's professional and public life is characterised by variety, communication, and a multiplicity of directions. You may be juggling several professional projects simultaneously, or working in a role that requires constant communication, writing, or movement between different people and contexts. Networking is favoured, and new professional contacts made this year can open significant doors. Publicity of some kind is possible — being written about, interviewed, or finding a larger audience for your ideas. The risk is scattered professional effort: too many directions pursued without sufficient depth or follow-through. Decision-making about career direction may be difficult when too many options seem equally viable. Mercury's house position reveals which area of life is generating the most professional communication and mental activity this year.`,

  Cancer: `With Cancer on the Midheaven of your solar return, your professional and public identity is more emotionally inflected than usual. Your reputation may be shaped by qualities of care, sensitivity, and attentiveness to others' needs — you are seen as nurturing, protective, or deeply invested in the wellbeing of those you work with. Work involving the public, women, families, or domestic concerns is particularly well-suited to this Midheaven. Home-based work or a shift in the relationship between your professional and domestic life is possible. The emotional stakes of your career feel higher this year — professional setbacks are taken more personally, and professional successes feel deeply satisfying. The Moon's sign, house, and aspects become especially important as the ruler of the MC, colouring the emotional quality of your professional life in considerable detail throughout the year.`,

  Leo: `With Leo on the Midheaven of your solar return, your public life, career, and reputation are lit from within — this is a year to be seen, to lead, and to allow your individual gifts to be recognised. You may take on a more prominent or visible role than usual, or find that your professional work attracts a genuine audience. Creative work, performance, leadership, and anything requiring personal charisma are all supported. The desire for professional recognition is strong, and the year's events are likely to provide the stage — what you do with it depends on the Sun's house position, which as the ruler of Leo on the MC is doubly significant this year. The risk is an overconcern with approval and status that distorts your professional judgement. Ego confrontations with colleagues or authority figures are possible if the desire to be in charge outstrips the circumstances. At its best, a Leo MC year is one of genuine professional flourishing.`,

  Virgo: `With Virgo on the Midheaven of your solar return, your professional focus turns toward precision, service, and the refinement of your skills and methods. This is a year when the quality of your work matters more than its visibility — you are less concerned with recognition and more invested in doing things well. A technical skill, a health-related role, or any professional work requiring careful attention to detail is particularly well-supported. You may also take on a service-oriented function within your professional life — supporting others, solving practical problems, or improving systems that have been operating inefficiently. The risk is excessive self-criticism and a perfectionism that prevents you from completing and sharing work because it never feels quite finished enough. Mercury's house position indicates the specific area of life where your professional precision and analytical attention will be most productively applied.`,

  Libra: `With Libra on the Midheaven of your solar return, your professional and public life is shaped by themes of partnership, diplomacy, and the pursuit of balance and fairness. You may enter into a significant professional partnership, take on a role that requires you to represent others or mediate between competing interests, or find that your public reputation is built largely through your relational skills. Legal matters affecting your career or public standing may arise. The desire for professional harmony is strong, and you are more willing than usual to compromise and collaborate. The risk is indecisiveness — too much weighing of options without commitment — or an over-willingness to accommodate others at the expense of your own professional position. Venus's house position reveals where the year's professional relationships, negotiations, and aesthetic sensibilities are most active.`,

  Scorpio: `With Scorpio on the Midheaven of your solar return, your professional and public life takes on a more intense, strategic, and transformative quality. You may be working in contexts involving power, hidden information, financial complexity, investigation, or psychological depth. Your professional presence carries more weight than usual — you are taken more seriously, and your ability to perceive what others miss may become a genuine professional asset. Career changes that involve a significant reinvention of your professional identity are possible. Power dynamics in the workplace may require careful navigation. The risk is a tendency toward secrecy, manipulation of professional situations, or an intensity that alienates colleagues who are less comfortable with direct confrontation. Mars or Pluto as co-rulers of Scorpio indicate through their house positions where the year's most significant professional transformation is being catalysed.`,

  Sagittarius: `With Sagittarius on the Midheaven of your solar return, your professional and public life expands — literally and figuratively. Long-distance travel for work, dealings with foreign countries or cultures, publishing, broadcasting, education, law, or any field that involves promoting ideas to a wider audience are all highlighted. Your professional reputation may grow beyond its previous boundaries this year. There is an optimistic and philosophical quality to how you approach your work — you are thinking in bigger terms and pursuing goals that genuinely inspire you. The risk is overextension: too many professional projects, unrealistic timelines, or a tendency to promote ideas before they are fully developed. Legal matters may also need attention. Jupiter's house position reveals where the year's most significant professional expansion and opportunity are centred.`,

  Capricorn: `With Capricorn on the Midheaven of your solar return, the year's professional and public life is defined by discipline, ambition, and an increased awareness of long-term career strategy. This is an excellent Midheaven for sustained professional effort — you are willing to do the work, to take the slow road, and to build something that will last. Recognition from authority figures and institutions is possible, particularly if you have been consistently demonstrating competence and reliability. Career advancement through steady application rather than dramatic moves is the pattern of a Capricorn MC year. The risk is over-seriousness — becoming so focused on professional obligation that you lose touch with the pleasure and meaning that should accompany good work. You may also be harder on yourself professionally than is warranted. Saturn's house position reveals where the year's professional tests, discipline, and enduring lessons are most concentrated.`,

  Aquarius: `With Aquarius on the Midheaven of your solar return, your professional and public life takes an unexpected or unconventional turn. You may break from an established career path, introduce radical new ideas into your professional context, embrace technology in new ways, or find that your public reputation becomes associated with originality and independence of thought. Group work and collective professional endeavours may be a significant feature of the year. You are less concerned with traditional markers of career success and more interested in whether your work is genuinely innovative and aligned with your values. The risk is professional instability — changes that happen too quickly or unconventionally, leaving you without the security structures you need. Uranus's house position reveals where the year's most surprising professional developments and breakthroughs will occur.`,

  Pisces: `With Pisces on the Midheaven of your solar return, your professional and public life takes on a more fluid, compassionate, and spiritually influenced quality. Work that involves service, healing, the arts, spirituality, charitable endeavour, or any field engaging with the invisible or intangible is particularly well-supported. Your professional reputation may be shaped this year by empathy, creativity, and a quality of vision that others find inspiring. The risk is professional confusion — a lack of clear direction, a tendency to drift rather than pursue defined goals, or a susceptibility to being misled about professional opportunities. Some work done this year may be behind the scenes or difficult to define in conventional terms. Boundaries in professional relationships may need careful attention. Neptune's house position indicates where the year's most spiritually significant, creative, or potentially confusing professional energies are operating.`,
};
