// src/content/mercury_in_houses.ts
// Solar Return: Mercury in each of the 12 houses
// Sources: Mary Fortier Shea "Planets in Solar Returns" (3rd ed.) — primary;
// Cafe Astrology Solar Return series; Journeys Yearly Solar Return Report
// NOTE: Mercury's house position shows where your mind is focused, where
// communication is most active, and where thinking and information-gathering
// are central to the year's themes. Check Mercury's sign and aspects for
// additional texture on HOW the mind operates this year.

export const MERCURY_IN_HOUSES: Record<number, string> = {

  1: `Solar Return Mercury in the first house places communication, self-expression, and active thinking at the very forefront of your year. You are more verbally engaged, more intellectually assertive, and more inclined to make your opinions known than in other years. The mind is busy and close to the surface — ideas arise quickly and you want to act on them, share them, and test them against others' thinking. Writing, speaking, teaching, or any form of public self-expression through words is particularly well-supported. You may be making personal decisions that require you to articulate your position clearly, to negotiate on your own behalf, or to communicate something about yourself that you have previously left unsaid. The risk is a tendency to speak before you have thought things through fully, or to become so occupied with your own ideas and opinions that you are less receptive to others'. This is also a year when short trips, errands, and local connections feature more prominently in your daily life. Mercury's sign will indicate the style of your thinking and communication — analytical, curious, playful, or precise.`,

  2: `Solar Return Mercury in the second house focuses your thinking and communication on money, values, possessions, and the practical question of financial security. This is a year when you are actively thinking about your income — how to increase it, protect it, or use it more wisely — and making concrete plans or decisions in this area. Research into financial matters, conversations about money with advisers or partners, and the mental work of budgeting and planning are all characteristic of this placement. You may also be thinking carefully about what you truly value and whether your current life reflects those values in practical terms. Skills and talents that can generate income may receive particular attention. Mercury here does not guarantee financial improvement, but it does indicate that you are mentally engaged with the question. Business ideas conceived this year have a practical quality to them. The risk is overthinking financial matters to the point of anxiety, or making financial decisions on the basis of incomplete information. Take time to gather facts before committing.`,

  3: `Solar Return Mercury in the third house is Mercury in its natural domain, and the result is a year of heightened mental activity, communication, learning, and local movement. Your mind is at its most engaged and curious — you want to know things, to discuss them, to write about them, and to share what you are discovering. Study, reading, courses, writing projects, and intellectual engagement of all kinds are well-supported. Relationships with siblings, neighbours, and those in your immediate community carry more significance. Short trips are frequent. Media involvement — being interviewed, publishing, broadcasting — is possible. This is an excellent year for any project that requires sustained intellectual effort combined with clear communication. The sheer volume of information and communication flowing through your life may feel overwhelming at times, and learning to prioritise and organise your thinking is one of the year's practical tasks. Mercury in the third also heightens the risk of anxiety and mental restlessness if the mind is not given purposeful direction.`,

  4: `Solar Return Mercury in the fourth house turns your thinking inward — toward home, family, roots, and the deeper questions of your own psychological history. You are mentally engaged with domestic matters this year: decisions about where you live, renovations or improvements to your home, family communications, and the logistics of domestic life all require significant thought. Conversations with family members — including difficult ones about the past or about future arrangements — are characteristic of this placement. You may find yourself reflecting on your childhood, on your parents' influence, and on the emotional patterns you have inherited. Therapy or psychological self-examination goes well, as Mercury in the fourth house supports the intellectual understanding of emotional material. If you are a parent, parenting questions and communication with your children may occupy your thinking. Working from home is supported. The risk is mental preoccupation with private worries that circulate without resolution — learning to distinguish productive reflection from unproductive rumination is important this year.`,

  5: `Solar Return Mercury in the fifth house connects your mental life with creativity, pleasure, romance, and self-expression. Your thinking is more playful, more generative, and more willing to take intellectual risks than in other years. Creative writing, storytelling, brainstorming, and any form of intellectual work that allows for genuine originality are well-supported. You may be planning or thinking about leisure activities, holidays, or recreational projects with unusual care and attention. Romantic relationships may have a significant intellectual or communicative dimension — you are drawn to people you can talk to, and conversations in close relationships carry particular meaning. If you have children, communication with them and thinking about their development, education, or activities is highlighted. Speculation — intellectual or financial — requires care, as Mercury in the fifth can generate exciting ideas that outpace practical reality. At its best, this is a year of genuine creative and intellectual playfulness.`,

  6: `Solar Return Mercury in the sixth house focuses mental energy on work, health, daily routines, and the practical maintenance of everyday life. You are thinking carefully about how your daily life is organised — what is working, what needs to be improved, and what practical changes would make your life function more effectively. Work-related communication, paperwork, and the intellectual dimensions of your professional responsibilities are prominent. This is an excellent year for any task requiring methodical thinking, attention to detail, or the careful analysis of practical problems. Health matters may require research and decision-making — gathering information about a diagnosis, researching treatment options, or thinking carefully about diet and lifestyle changes. Relationships with colleagues and the daily social fabric of your work environment carry more significance. The risk of Mercury in the sixth is overthinking and worry about details that may or may not be genuinely important. Learning to distinguish between the details that deserve your attention and those that can safely be released is one of the year's useful disciplines.`,

  7: `Solar Return Mercury in the seventh house makes communication the central medium through which your key relationships are experienced and developed this year. Important conversations, negotiations, agreements, and the verbal dimensions of partnership are all highlighted. You may be entering into a formal agreement of some kind — a contract, a commitment, a legal document — or working through an existing relationship by bringing difficult topics into open discussion. Consulting, advising, or working closely with another person in an intellectual capacity is also possible. Legal matters may require your attention and active communication. You are more aware than usual of how you communicate in one-to-one relationships — whether you listen as well as you speak, whether you say what you genuinely mean, whether the communication in your close relationships is honest and complete. The risk is a tendency to intellectualise relational dynamics at the expense of emotional honesty, or to over-negotiate situations that need a simpler response.`,

  8: `Solar Return Mercury in the eighth house turns your thinking toward the deeper, less comfortable dimensions of life — shared finances, psychological complexity, research into hidden matters, and the questions that do not have easy answers. You may be dealing with tax matters, insurance, debt, estate planning, or financial arrangements involving a partner — all of which require careful thought and specific information. Research of an investigative quality is well-supported; this is an excellent year for any intellectual work that requires going beneath the surface of things. Psychological insight is sharp — you are thinking more deeply about motivation, power dynamics, and what drives behaviour in yourself and others. Conversations about taboo topics, difficult truths, or subjects that are usually kept private may be necessary and ultimately clarifying. The risk is obsessive thinking — the eighth house Mercury can get caught in a loop around anxious subjects, replaying concerns without resolution. Trust that information will emerge when it is ready, and resist the urge to force certainty where genuine uncertainty exists.`,

  9: `Solar Return Mercury in the ninth house expands your intellectual horizons for the year, connecting your thinking with higher education, philosophy, foreign cultures, publishing, broadcasting, and the pursuit of larger meaning. This is an excellent year for study at an advanced level, for writing and publishing work that reaches a wider audience, or for any intellectual engagement that takes you beyond the familiar boundaries of your existing knowledge. Travel to distant places — and the intellectual encounters that come with it — is supported. Legal matters may require thought and attention. You are more interested than usual in the big questions: what do you believe, what principles do you want to live by, and what is the larger framework of meaning that makes sense of your experience? The risk is intellectual overconfidence — the ninth house Mercury can become convinced of its own rightness and less open to the correction that genuine learning requires. Publishing or teaching projects benefit from careful preparation rather than rushing to share ideas before they are fully developed.`,

  10: `Solar Return Mercury in the tenth house connects your thinking and communication directly to your professional life and public reputation. Career decisions, professional communications, and the intellectual dimensions of your work are central. You may be more publicly visible than usual through your ideas — speaking at events, publishing professionally, managing important correspondence, or taking on a role that requires you to represent your organisation or field in some capacity. Strategic thinking about your career — where you are, where you want to go, and how you intend to get there — is a natural focus. Conversations with authority figures, employers, or mentors carry significance. Your professional reputation may be shaped in part by the quality of your thinking and communication this year. The risk is becoming so focused on career communication and professional positioning that you lose sight of the genuine substance behind the presentation. Decisions about your career direction benefit from careful information-gathering before commitment.`,

  11: `Solar Return Mercury in the eleventh house connects your thinking and communication with friendships, groups, networks, and your long-range hopes for the future. You are mentally engaged with collective projects, with the ideas and conversations that flow through your social world, and with the question of what you genuinely hope to build in the years ahead. Networking is strongly supported — conversations made through professional or social groups this year can open significant doors. You may be involved in writing, planning, or communicating on behalf of a group or organisation. Future-oriented thinking — planning, strategising, and articulating your long-range vision — is productive and well-focused. Ideas generated in collaboration with others have particular value. The risk is too much time spent in the realm of ideas and plans without sufficient action to bring them into reality. Social media, group communications, and the intellectual life of your extended network may take up more time and attention than is truly warranted.`,

  12: `Solar Return Mercury in the twelfth house turns your thinking inward and often private, operating behind the scenes rather than in open communication. You may be working on something that you are not yet ready to share — a writing project in its early stages, a plan still being formed, or a decision being quietly worked through before it becomes public. Solitary intellectual work is well-supported; research, writing, reflection, and any form of thinking that benefits from privacy and uninterrupted quiet goes well. You may also find that your communications this year are more guarded than usual — either by choice or by circumstance — and that there are things you are holding close that would previously have been more openly expressed. The unconscious and intuitive dimensions of your thinking are more active, and paying attention to dreams, symbolic thinking, and what arises in contemplation can be genuinely informative. The risk is self-deception or information withheld from you that affects your decisions. Be particularly careful about the completeness and accuracy of information before making significant commitments this year.`,
};
