// src/content/moon_in_signs.ts
// Solar Return: Moon in each of the 12 signs
// Sources: Cafe Astrology Solar Return Moon series (Annie Heese);
// Mary Fortier Shea "Planets in Solar Returns" (3rd ed.);
// Journeys Yearly Solar Return Report (Volguine method)
// NOTE: The Moon's sign describes the emotional style, tone, and quality of
// your feeling life for the year — HOW you feel and react. Read together with
// the Moon's house position (WHERE your heart is) for a complete picture.
// Cardinal signs = active, instinctive emotional responses.
// Fixed signs = emotional strength, stability, endurance.
// Mutable signs = adaptable, variable, adjusting emotional responses.

export const MOON_IN_SIGNS: Record<string, string> = {

  Aries: `The Solar Return Moon in Aries gives the year an emotionally direct, impulsive, and energetically renewed quality. Your feelings move quickly — from flat calm to strong reaction with little warning — and you are more inclined than usual to act on what you feel without waiting to process it fully. There is a genuine freshness to this emotional style: you meet each new experience without excessive baggage from the last one, and your capacity for enthusiasm and new emotional starts is high. The desire for emotional independence is strong, and you may find that you need more space than usual to feel free within your relationships. Patience with slow-moving emotional processes may be in short supply. Impulsive emotional decisions — commitments made or broken in the heat of the moment — are the primary risk. When you can channel this cardinal fire energy into purposeful new beginnings rather than reactive exits, the Aries Moon year has a quality of genuine emotional renewal.`,

  Taurus: `The Solar Return Moon in Taurus brings a quality of emotional solidity, steadiness, and a deep need for security and comfort to the year. Your feelings settle more readily than in other years, and you are less likely to be thrown by external turbulence — there is an emotional groundedness to this placement that gives you genuine resilience. Security is the emotional keynote: you need to know that what you love is safe, that your material circumstances are stable, and that the people close to you are reliably present. Beauty, sensory pleasure, and physical comfort become emotionally important in a concrete way — you find genuine emotional satisfaction in a good meal, a beautiful environment, or the simple steadiness of an established routine. The risk is emotional stubbornness — a resistance to necessary change because change feels threatening to the security you have built. When deeply hurt, you may hold on to grievances longer than is good for you. At its best, the Taurus Moon year gives you an emotional foundation that sustains you through whatever the year brings.`,

  Gemini: `The Solar Return Moon in Gemini gives the year an emotionally restless, communicative, and mentally engaged quality. Your feelings are connected closely to your thinking — you process emotions by talking about them, writing about them, or turning them over intellectually until they yield to understanding. This can make you emotionally articulate and genuinely good at helping others understand their own feelings, but it can also mean that you rationalise emotions before you have actually felt them, keeping yourself at an intellectual distance from what is genuinely moving inside you. The emotional pace of the year is quick, with moods shifting more frequently than usual. You may feel pulled in several directions at once — emotionally engaged with multiple situations or relationships simultaneously — and this can feel stimulating or scattered depending on your capacity for variety. Communication in close relationships is important and emotionally significant. The risk is emotional superficiality or an avoidance of depth in favour of the easier stimulation of novelty.`,

  Cancer: `The Solar Return Moon in Cancer is the Moon in its home sign, intensifying all of its natural qualities for the year — emotional sensitivity, attachment to family and home, a heightened need for security, and a deep responsiveness to the emotional atmosphere around you. You feel more than usual this year, and the feelings go deep. Your family of origin, your domestic life, and the people you consider home carry particular emotional weight. Memories surface readily, and the past may feel more present than it has in recent years. This is not merely nostalgia — the Cancer Moon is asking you to understand the emotional roots from which your present life has grown. Moods may fluctuate with a rhythmic regularity that mirrors the Moon's own cycles; awareness of your own emotional patterns can help you navigate rather than be swept along by them. The risks are over-sensitivity, defensiveness when you feel threatened, and a tendency to cling to emotional situations or relationships beyond their natural end. At its best, the Cancer Moon year deepens your capacity for genuine care and emotional self-knowledge.`,

  Leo: `The Solar Return Moon in Leo brings warmth, expressiveness, and a quality of emotional generosity to the year. You feel more dramatically and more openly than in some years — your joy is fuller, your hurt is sharper, and your need to be appreciated and seen in your emotional life is more pronounced. There is something genuinely theatrical about the Leo Moon: feelings want an audience, love wants to be declared, and creative or romantic expression becomes an emotional necessity rather than a luxury. You are more playful, more warm, and more capable of inspiring others with your emotional vitality. The need for recognition in close relationships is real — you give a great deal this year and you genuinely need to feel that it is valued. The risk is wounded pride: when love or appreciation is not returned in the way you hoped, the Leo Moon can feel this as a significant emotional blow and respond with drama or withdrawal. At its best, this is a year of remarkable warmth, creative flourishing, and emotional generosity.`,

  Virgo: `The Solar Return Moon in Virgo gives the year an emotionally conscientious, analytical, and service-oriented quality. Your feelings tend to be expressed through practical action rather than direct declaration — you show care by doing things, by attending to details, by making sure everything is in order for the people you love. Emotional processing happens largely through thought and analysis: you work through feelings by examining them, categorising them, and understanding their origins. This can give you a useful clarity about your own emotional life, but it can also lead to over-analysis that keeps you at a slight remove from the raw experience of what you feel. Health, daily routine, and the quality of your everyday environment have an emotional significance this year — when these are in order, you feel good; when they are chaotic or neglected, your emotional equilibrium suffers. The risk is worry and self-criticism: the Virgo Moon can apply impossibly high standards to your own emotional responses and find them wanting. Service to others, when it flows from genuine care rather than anxious obligation, is deeply satisfying.`,

  Libra: `The Solar Return Moon in Libra gives the year an emotionally relational, harmony-seeking, and aesthetically sensitive quality. Your emotional wellbeing is closely connected to the quality of your relationships — when they are in balance and genuinely reciprocal, you feel good; when they are discordant or one-sided, the disturbance affects you more than it might in other years. You are drawn toward beauty, fairness, and the pleasure of genuine connection, and you are more attuned than usual to social dynamics and the emotional needs of those around you. Your power of attraction is heightened — you draw people toward you through a quality of openness and genuine interest. The desire for emotional harmony can become problematic if it leads you to avoid necessary confrontation or to manage others' feelings at the expense of expressing your own honestly. Decision-making may feel emotionally difficult when two equally valid options point in different directions. The Libra Moon year is most rewarding when you can hold both the need for connection and the need for honest self-expression in balance.`,

  Scorpio: `The Solar Return Moon in Scorpio gives the year an emotionally intense, perceptive, and psychologically deep quality. Your feelings this year are not light or surface-level — they go to the core of what matters, and you are capable of an emotional endurance and a quality of controlled intensity that may surprise even yourself. You are more perceptive than usual about people's hidden motives, emotional undercurrents in situations, and the gap between what people say and what they actually feel. This can be genuinely useful, though it can also make you suspicious of straightforward situations that do not in fact have a hidden dimension. Emotional control is characteristic of this placement: you can sit with difficult feelings without being destroyed by them, observing and processing before reacting. The risk is emotional intensity that tips into obsession, jealousy, or a refusal to forgive. At its best, the Scorpio Moon year gives you access to a psychological depth and emotional strength that transforms you.`,

  Sagittarius: `The Solar Return Moon in Sagittarius gives the year an emotionally restless, expansive, and freedom-loving quality. Your feelings are drawn toward the wide horizon — you need emotional room to move, to explore, to experience life beyond its familiar boundaries. When you feel constrained — by circumstances, relationships, or routines — your emotional response is restlessness and a strong drive to expand your world. Travel, philosophical exploration, encounters with different cultures, and engagement with ideas that challenge and enlarge your thinking all carry genuine emotional resonance this year. There is an optimistic quality to the Sagittarius Moon: even difficult situations tend to be approached with a belief that things will ultimately work out. The risk is emotional inconsistency — a tendency to make commitments under the influence of enthusiasm and then find them feeling like constraints when the initial excitement passes. Legal matters may have an emotional dimension. The Sagittarius Moon year is most satisfying when genuine growth and new experience are a regular part of life.`,

  Capricorn: `The Solar Return Moon in Capricorn gives the year an emotionally restrained, responsible, and achievement-oriented quality. Your feelings tend to be contained rather than freely expressed — not because you do not feel, but because the Capricorn emotional style values self-control and the appropriate management of emotion in context. You may take on more emotional responsibility than usual, whether for family members, colleagues, or professional obligations, and you approach these responsibilities with seriousness and genuine commitment. Work and achievement carry emotional significance this year — professional accomplishment feels genuinely satisfying, and professional difficulty is taken to heart. The risk is emotional withdrawal — becoming so focused on external responsibilities that you neglect the needs of your own inner life, or others in your circle feel you are less emotionally available than they need. Periods of feeling lonely or unsupported are possible when the weight of responsibility is not shared. At its best, the Capricorn Moon year brings emotional maturity, a reliable inner stability, and genuine satisfaction through meaningful work.`,

  Aquarius: `The Solar Return Moon in Aquarius gives the year an emotionally curious, somewhat detached, and freedom-valuing quality. Your emotional responses this year are less predictable than usual — quirky, unconventional, and sometimes surprising even to yourself. You feel things, but with a quality of observer alongside the participant — there is an ability to step back from your own emotional reactions and regard them with a certain intellectual interest. The need for emotional space and independence is pronounced: you are less comfortable with intensity or demands for closeness than in other years, and relationships that give you room to breathe feel significantly more comfortable than those that require constant togetherness. New friendships or group connections carry emotional significance, and you may find your social world expanding in unexpected directions. The risk is emotional detachment that leaves important relationships feeling neglected. At its best, the Aquarius Moon year brings a genuine emotional clarity and an ability to feel without being overwhelmed.`,

  Pisces: `The Solar Return Moon in Pisces gives the year an emotionally sensitive, compassionate, and spiritually receptive quality. Your emotional antennae are extended further than usual — you pick up on feelings in the environment, in the people around you, and in the subtler dimensions of experience with an unusual acuity. The boundary between your own feelings and the feelings of others may feel more permeable than you would like, and learning to distinguish what is yours emotionally from what you have absorbed from your surroundings is an important practice this year. Compassion flows naturally — you feel other people's pain with genuine empathy and may find yourself drawn toward acts of service or care that cost you something. Creative and spiritual life carry deep emotional meaning. The risks are emotional confusion, a tendency toward self-pity or victimhood when the year is difficult, and a susceptibility to being misled by others who sense your openness. Some form of emotional ending or release — the completion of a chapter that has run its course — is often associated with the Pisces Moon year. Solitude, meditation, and time in nature are genuinely restorative.`,
};
