// src/content/moon_in_houses.ts
// Solar Return: Moon in each of the 12 houses
// Sources: Mary Fortier Shea "Planets in Solar Returns" (3rd ed.) — primary authority;
// Cafe Astrology Solar Return Moon series (Annie Heese);
// Journeys Yearly Solar Return Report (Volguine method)
// NOTE: The Moon's house position shows where your emotional investment lies for the year —
// where your heart is, where fluctuations occur, and where instinctive responses
// are most active. Angular houses (1,4,7,10) = reactive and exposed.
// Succedent houses (2,5,8,11) = more controlled and stable.
// Cadent houses (3,6,9,12) = quieter, preparatory, less exposed.

export const MOON_IN_HOUSES: Record<number, string> = {

  1: `The Solar Return Moon in the first house places your emotions directly on the surface — this is a year when your inner life and your outer presentation are unusually aligned, for better and worse. You are more sensitive to your environment than in other years, picking up on emotional undercurrents in rooms, in conversations, and in the behaviour of those around you. Moods shift more readily, and others notice your emotional state more easily because you are less able — or less inclined — to conceal it. This can be a deeply empathic and connective year, drawing people toward you because of the genuine feeling they sense in your presence. It can also be a year of emotional reactivity, in which you respond to circumstances before you have had time to assess them clearly. The first house Moon is an angular placement, meaning that emotional responses are instinctive, immediate, and difficult to moderate in the moment. Women, family, and the public may play a prominent role in the year's events. The month-by-month rhythm of the Moon's transits will be felt more keenly than usual, and your emotional state may be noticeably more changeable across the year than in periods when the Moon sits in less exposed positions.`,

  2: `The Solar Return Moon in the second house ties your emotional wellbeing closely to your financial security and material stability for the year. You are more attuned than usual to what you have and what you might lose — fear of financial lack can quietly shape many of your decisions, even when the actual circumstances do not warrant it. Fluctuations in income or possessions are possible, though more often it is your sensitivity to those fluctuations that is the defining feature rather than dramatic material change. Security — physical, financial, and emotional — is the Moon's deepest need, and in the second house it seeks that security through tangible means. Keeping things stable and predictable is a strong underlying motivation. This is a succedent house placement, meaning that while emotions are present, they are more contained and controlled than in angular houses — you are better able to step back from immediate reactions before acting on them. Decisions about money, possessions, and what you genuinely value are best made from a place of calm rather than anxiety.`,

  3: `The Solar Return Moon in the third house creates a year in which emotions and intellect are in constant dialogue — sometimes productively, sometimes in competition. You may find it difficult at times to know whether you are thinking or feeling, or you may experience the two as inseparably entwined. Communications carry emotional weight, and you may say things that reveal more of your inner state than you intended, or find that what others say lands more deeply than it normally would. The integration of feeling and thought is the central developmental task of this placement: neither pure rationality nor pure emotional response is adequate — the year works best when you learn to use each to illuminate the other. This is a cadent house, meaning the Moon's expression is relatively quiet and preparatory — your emotional life is active but less exposed than in angular placements, and you have more opportunity to reflect before responding. Short trips, local community involvement, and frequent communication are characteristic features. Relationships with siblings, neighbours, and those in your immediate environment carry more emotional significance.`,

  4: `The Solar Return Moon in the fourth house returns emotion to its home territory — this is the Moon's natural domain, and its placement here intensifies the focus on family, domestic life, roots, and the deep interior of your personal life. Your home environment becomes a primary emotional container for the year: what happens within it affects your wellbeing profoundly, and you may invest significant energy in creating a domestic situation that genuinely nurtures you. Family relationships — with parents, children, or your chosen family — carry unusual emotional weight. This is an angular placement, meaning emotional responses are instinctive and immediate, and you may find yourself more affected by domestic developments than you would ideally like. Memories of childhood and the emotional patterns of your family of origin may surface for examination. A change of residence is a common event in a fourth house Moon year. At its deepest, this placement asks you to build a genuine emotional foundation — to understand what truly makes you feel safe and to invest in that rather than in external substitutes.`,

  5: `The Solar Return Moon in the fifth house brings emotional life into the realm of pleasure, creativity, romance, and self-expression. Your heart is with what brings you joy this year — with play, with the people you love, with creative projects that allow you to express who you genuinely are. Romantic relationships carry strong emotional charge, whether you are beginning a new relationship, deepening an existing one, or experiencing the emotional intensity of a love affair. If you have children, your emotional investment in them is heightened and they become a central focus of your year. Creative work feels personally satisfying in a way it may not in other years — you are making things that matter to you, not just producing for external approval. This is a succedent house, so the emotional responses, while genuine and active, are more contained than in angular placements. The risk is emotional dependency on the pleasures of the fifth house — needing romance, entertainment, or creative validation to feel okay. At its best, this is a year of genuine joy.`,

  6: `The Solar Return Moon in the sixth house connects your emotional wellbeing directly to the rhythms of your daily life — your work, your health routines, and the quality of your everyday experience. You are emotionally invested in doing things well, in being useful, and in maintaining the practical structures that hold your life together. When work goes well, you feel good; when it is chaotic or unproductive, your mood follows. Health may become an emotional focus — not necessarily through illness, but through a heightened awareness of what your body needs and a genuine desire to address it. Relationships with colleagues, employees, and those you serve in daily life carry more emotional significance than usual. This is a cadent house placement, meaning the emotional life is relatively contained and inward — you are processing quietly rather than reacting dramatically. The risk is a tendency to worry about details that are not truly threatening, or to over-identify your sense of self-worth with your productivity. Service and daily discipline, when engaged with genuine care rather than anxious obligation, are the sixth house Moon's most satisfying expressions.`,

  7: `The Solar Return Moon in the seventh house places your emotional centre of gravity in your closest relationships. Your wellbeing this year is significantly tied to the quality of your one-to-one connections — in a good year, a loving partnership or deeply supportive close friendship is the source of profound emotional nourishment; in a more difficult year, relational tensions become the primary source of disturbance. You are more aware than usual of what you need from others, and more sensitive to whether those needs are being met. Significant relationship events are common with this placement — the beginning or deepening of a committed partnership, formal agreements of various kinds, or — when the chart carries difficult aspects — confrontations with relationship problems that have been building beneath the surface. This is an angular placement, meaning emotional responses in relational contexts are immediate, instinctive, and difficult to moderate. The public and women may play a prominent role in the year's events. The practice this year is learning to stay emotionally present in relationships without losing your own centre in the process.`,

  8: `The Solar Return Moon in the eighth house is one of the most psychologically intense positions in the solar return. Your emotional life goes deep this year — beneath the surface of everyday feeling into the less comfortable territory of transformation, power, loss, and the hidden dimensions of your inner life. You are more perceptive than usual about what motivates people, including yourself, and this perception may be both illuminating and difficult to live with. Shared financial matters — a partner's income, inheritance, debt, taxes, or joint resources — may become emotionally significant. Sexuality and intimacy may carry unusual weight. The emotional strength of this placement should not be underestimated: the eighth house Moon gives you a quality of psychological endurance, a capacity to sit with difficult feelings without being destroyed by them. This is a succedent house, providing more emotional stability than the angular houses, but the depth of what you encounter this year is real. Profound personal transformation is possible when you engage honestly with what the eighth house Moon asks you to face.`,

  9: `The Solar Return Moon in the ninth house gives your emotional life a restless, expansive, and philosophically searching quality for the year. Your heart is drawn toward the wide horizon — toward travel, toward ideas that enlarge your understanding, toward experiences that push you beyond the familiar. There is an emotional need for freedom and growth that may make the boundaries of your current life feel somewhat confining. Study, travel, encounters with other cultures, and engagement with religious or philosophical questions all carry genuine emotional meaning. Beliefs you have held without examination may become emotionally charged — challenged or deepened by what the year brings. Legal matters may have an emotional dimension. This is a cadent house, so the emotional life is relatively inward and preparatory — you are in a period of expanding your inner world more than your outer circumstances, laying philosophical groundwork for years to come. Restlessness that does not find a genuine outlet in growth or exploration can become dissatisfaction or aimlessness.`,

  10: `The Solar Return Moon in the tenth house brings your emotional life into the public arena — your feelings about your career, your reputation, and how you are perceived by the world are close to the surface and more influential over your actions than they are in other years. Professional successes feel deeply satisfying, and professional setbacks are taken to heart in a way that may surprise you. You may find yourself in a more public-facing role than usual, or in a position where your emotional state is more visible to others in professional contexts than you would like. The reputation is sensitive — how you are seen matters emotionally this year. Women or family may play a role in career developments. This is an angular placement, meaning emotional responses in professional contexts are instinctive and immediate. There is sometimes a quality of the mother archetype in a tenth house Moon year — either through becoming a more nurturing presence in your professional environment, or through the influence of a maternal figure on your career. Changes in public status are possible.`,

  11: `The Solar Return Moon in the eleventh house gives the year an emotionally oriented quality around friendships, group belonging, and your hopes for the future. Your emotional wellbeing is tied in significant ways to the quality of your friendships and your sense of connection to a community or collective — you need to feel that you belong to something larger than yourself, and you are more sensitive than usual to whether that need is being met. New friendships are possible, and existing ones may deepen or shift. A longing to contribute to shared goals, to collaborate on something meaningful, or to feel recognised within a group you value is characteristic of this placement. Long-range plans and future aspirations carry emotional weight — you are planting seeds this year that you genuinely care about seeing grow. This is a succedent house, providing emotional stability and a degree of objectivity — you feel things without being overwhelmed by them. The risk is an emotional dependency on group approval or social belonging that makes it difficult to hold your own position when the collective moves in a direction you do not agree with.`,

  12: `The Solar Return Moon in the twelfth house is one of the most private and inward emotional placements in the solar return. Your feeling life is largely hidden this year — not necessarily suppressed, but operating below the surface in ways that are not fully visible to others, and sometimes not fully visible to yourself. Dreams, intuitions, and unconscious material are more active and carry more information than usual. Time alone becomes an emotional necessity rather than a luxury, and when you cannot get it, your sense of inner equilibrium suffers. This is a year for solitude, reflection, and the quiet but important work of understanding what you have been carrying emotionally that needs to be released. Spiritual practice, therapy, and creative work done in private are all deeply supported. The risk is emotional isolation — withdrawing so completely that important relational needs go unmet, or avoiding difficult feelings through various forms of escape rather than engaging with them honestly. Hidden matters may surface that require emotional processing. What you work through quietly this year will not be wasted — it prepares you for a new cycle.`,
};
