// src/content/neptune_in_houses.ts
// Solar Return: Neptune in each of the 12 houses
// Sources: Mary Fortier Shea "Planets in Solar Returns" (3rd ed.) — primary;
// Cafe Astrology Solar Return series; Liz Greene "The Astrological Neptune";
// Stephen Arroyo "Astrology, Karma & Transformation"
// NOTE: Neptune's house position shows where dissolution, idealism, confusion,
// spiritual sensitivity, and the longing for transcendence are concentrated for
// the year. Neptune moves extremely slowly (~14 years per sign), so its SR house
// placement shifts almost entirely through changes in SR location.
// Neptune does not lie in the way that Mercury lies — it dissolves the boundary
// between what is true and what is wished for, making discernment the essential
// practice wherever it is placed. Its gifts are real: heightened sensitivity,
// creative inspiration, spiritual openness. Its risks are equally real:
// self-deception, evasion, and the substitution of fantasy for honest engagement.

export const NEPTUNE_IN_HOUSES: Record<number, string> = {

  1: `Solar Return Neptune in the first house places the year's themes of dissolution, heightened sensitivity, and the longing for transcendence directly in your personal identity and self-expression. The boundaries of the self feel more permeable than usual — you are more affected by the moods, needs, and energies of others, more sensitive to atmosphere and environment, and less certain about who you are and what you want in any stable, definable sense. This permeability is genuinely creative: the imagination is more alive, artistic inspiration more accessible, and the capacity for empathy and compassion more fully available. The self is less defended, and what comes through that openness can be genuinely beautiful. The risk is the loss of the very selfhood that makes that openness meaningful — Neptune in the first can produce a year of confusion about identity, of taking on others' projections as if they were your own truth, of retreating into fantasy or spiritual bypassing when the honest demands of life become uncomfortable. Physical boundaries between self and environment are also less defined: sensitivity to substances, environments, and other people's physical states is heightened. The year is most navigable when you cultivate both Neptune's genuine openness and a conscious practice of returning to your own centre.`,

  2: `Solar Return Neptune in the second house dissolves the clarity and firmness of your relationship with money, material possessions, and personal value. Financial matters may be subject to confusion, misrepresentation, or a quality of fog that makes it difficult to see your actual circumstances clearly. This is not a year for financial decisions requiring precise assessment or rigid planning — the numbers may be less reliable than they appear, and the financial picture as a whole resists the kind of clarity that sound decision-making requires. Idealism about money and material circumstances can lead to decisions based on what you wish were true rather than what is actually the case. Generosity is genuine but may exceed what is financially sustainable. At the same time, Neptune in the second can bring a genuinely more fluid and spiritually informed relationship with material circumstances — the recognition that what you value most cannot be measured in material terms, and that your sense of self-worth is better anchored in spiritual and creative identity than in financial standing. This is an excellent year for artists, healers, and others whose work lives in the space between the material and the transcendent. Financial matters benefit from more detailed and more sceptical attention than usual.`,

  3: `Solar Return Neptune in the third house brings a quality of dissolution, heightened sensitivity, and creative permeability to the domains of communication, intellectual life, and your immediate environment. The mind is less precise and more imaginative than usual — linear thinking gives way to associative, symbolic, and intuitive modes of processing that are genuinely productive for creative and artistic work while being less reliable for analytical and logical tasks. Writing takes on a more lyrical, more emotionally resonant quality. Communication with others may be subject to misunderstanding and misinterpretation — what is said and what is heard drift apart more easily than in other years, and the care required to ensure genuine clarity is greater. The local environment may feel more dreamlike and less sharply defined. Relationships with siblings or neighbours may be subject to confusion or idealisation. Information received this year may be less reliable than it appears — the year calls for more careful verification of what you are told and more honest checking of your own assumptions. At its best, Neptune in the third brings a quality of genuine poetic sensitivity to all communication, and the capacity to perceive and articulate dimensions of experience that more analytical years miss.`,

  4: `Solar Return Neptune in the fourth house dissolves the fixed outlines of home, family, and psychological foundation, replacing them with something more fluid, more spiritually sensitive, and often more confusing. The domestic environment may feel less clearly defined — boundaries between your private space and the world outside, or between your psychological interior and the emotional states of those around you, are more permeable than usual. Family relationships may be subject to confusion, idealisation, or a quality of unspoken feeling that is difficult to address directly. A family member who is in some way dissolving — through illness, addiction, spiritual crisis, or simply the losses of age — may require compassionate attention. The home may be a space of unusual spiritual or creative richness, a place where the imagination flourishes and where solitude produces genuine inner depth. Old family patterns and inherited psychological structures are more fluid and more accessible to revision — the year supports deep inner work, the healing of old wounds, and the compassionate release of what no longer serves. The risk is that the dissolution of this placement affects the very foundations of inner security, producing a year of psychological instability or evasion that prefers comfortable illusion to honest engagement with what is actually being felt.`,

  5: `Solar Return Neptune in the fifth house brings idealism, heightened creative sensitivity, and a quality of beautiful but potentially deceptive enchantment to the domains of romance, creativity, and self-expression. Creative work is genuinely inspired — the imagination is at its most fertile, the capacity for beauty and emotional resonance at its most alive, and the year supports creative projects that aspire to something genuinely transcendent rather than merely accomplished. Art, music, poetry, film, and any creative medium that works through image and feeling rather than argument and logic benefit particularly from Neptune's presence in the fifth. Romantic life is coloured by Neptune's signature quality — the tendency to see partners through an idealising lens that emphasises their most luminous qualities while dissolving the less comfortable reality. New romantic connections made under Neptune in the fifth can be genuinely magical and genuinely misleading in equal measure. The disillusionment that follows, if it comes, is not a failure but an invitation to love what is actually there rather than what was imagined. Children may have a particularly sensitive or imaginative quality this year. The year is most rewarding when you allow Neptune's genuine creative inspiration to flourish while maintaining honest discernment in your romantic choices.`,

  6: `Solar Return Neptune in the sixth house dissolves the clarity, discipline, and practicality that the sixth house normally requires, introducing confusion, sensitivity, and an idealistic relationship with work and health that has both gifts and genuine risks. The working environment may feel less clearly defined — boundaries between your responsibilities and others' are more porous, the expectations of the job may be unclear or shifting, and a quality of confusion about what is actually required of you professionally can accumulate over the year. Colleagues or employers may not be fully honest about what they want or expect. Health matters under Neptune in the sixth are subject to the same quality of dissolution — symptoms may be difficult to diagnose clearly, sensitivities to foods, environments, and substances are heightened, and the relationship between psychological and physical wellbeing is unusually close. This is an excellent year for healing practices that work with the whole person rather than isolated symptoms — bodywork, energy medicine, mindfulness-based approaches, and integrative health. The vocational dimension of the sixth house may be touched by Neptune's idealism — a deepening desire to do work that genuinely serves and heals, even when the practical circumstances make that aspiration difficult to realise.`,

  7: `Solar Return Neptune in the seventh house brings idealism, heightened sensitivity, and the risk of genuine self-deception to your closest personal and professional relationships. The tendency to see partners through an idealising lens is strong — Neptune in the seventh consistently produces years in which the people closest to you appear more luminous, more spiritually significant, and more perfectly suited to your deepest needs than any sober assessment would support. This is not always a problem: genuine soulmate connections are possible under this influence, and relationships that aspire to something spiritually meaningful rather than merely convenient can be genuinely nourishing. The risk is the more common one — that what you are seeing in a partner is a projection of what you most need to find, rather than what is actually there. Disappointment and disillusionment are possible when Neptune's veil lifts. Professional partnerships may also be subject to confusion or to partners who are not fully honest about their intentions or capacities. Legal matters benefit from more sceptical and more detailed attention than Neptune's benevolent haze normally encourages. The year is most navigable when you allow Neptune's genuine longing for deep connection to guide you toward authentic relationship while maintaining the honest discernment that love, properly understood, never abandons.`,

  8: `Solar Return Neptune in the eighth house is one of the most intensely spiritual and psychologically dissolving placements in a solar return. The eighth house governs transformation, shared resources, deep intimacy, and the boundary between the visible and invisible dimensions of life — all domains in which Neptune's dissolving, boundary-dissolving energy operates with particular power. Financial matters involving other people may be subject to confusion, misrepresentation, or a quality of fog that makes clear assessment difficult — this is not a year for casual trust in financial arrangements with others, and the careful documentation of shared financial matters is more important than usual. At the deeper level, Neptune in the eighth produces a year of genuine spiritual and psychological opening — the boundary between conscious and unconscious, between self and other, between the living and the dead, feels more permeable than usual. Dreams and intuitions carry more weight. Losses, endings, and experiences of grief may be part of the year's texture, and Neptune here can bring a quality of compassionate spiritual understanding to those losses that more defended years do not allow. Genuine mystical experience is possible. The risk is spiritual bypassing — using Neptune's transcendent orientation as a way of avoiding the genuine psychological and material demands of the eighth house.`,

  9: `Solar Return Neptune in the ninth house brings a quality of spiritual idealism, philosophical dissolution, and the longing for transcendent meaning to the domains of higher education, belief, long-distance travel, and the broad structures through which you understand the world. The philosophical and spiritual life is genuinely alive and genuinely productive this year — the desire for meaning goes beyond what conventional belief systems can satisfy, and the year may produce significant spiritual opening, mystical experience, or a genuine shift in the philosophical foundations through which you understand yourself and the world. Educational experiences that proceed through immersion, intuition, and direct experience rather than purely formal study are well-supported. Travel to places with spiritual or artistic significance may be deeply meaningful. The risk of Neptune in the ninth is the adoption of belief systems that are more consoling than true — the year's spiritual sensitivity can make it easier to adopt comforting spiritual narratives without submitting them to the genuine scrutiny that real understanding requires. Gurus, spiritual teachers, and philosophical systems should be engaged with both genuine openness and honest critical intelligence. Publishing and writing projects that aspire to transcendence are inspired; those requiring factual precision benefit from more careful attention to detail than Neptune naturally provides.`,

  10: `Solar Return Neptune in the tenth house dissolves the clarity and practical definition of your career, public identity, and professional standing. The professional life may feel less clearly defined than usual — the direction of your career may be unclear, professional goals may shift and dissolve before they can be realised, or the expectations of the public and professional world may feel difficult to read and impossible to satisfy consistently. Reputation may be subject to confusion, misrepresentation, or idealisation — others may project onto your public image qualities that have more to do with their own needs than with what you are actually offering. Professional deception — your own or others' — is a risk that requires vigilant attention. At the same time, Neptune in the tenth can produce a year of genuine vocational inspiration — the deepening of a calling toward work that serves, heals, or creates in ways that transcend ordinary professional calculation. Artists, healers, spiritual teachers, and those whose work lives in the space between the practical and the transcendent may find this placement profoundly generative. The year is most productive when the genuine inspiration of Neptune's presence in the public sphere is supported by enough practical structure to give it form.`,

  11: `Solar Return Neptune in the eleventh house brings idealism, heightened sensitivity, and the risk of self-deception to your social world, friendships, group involvements, and long-range aspirations. The social sphere may feel more spiritually alive and more emotionally resonant than usual — connections with others carry a quality of meaning and possibility that ordinary social life rarely achieves. New friendships formed under this influence may feel fated or deeply significant. Group involvements with a spiritual, artistic, or humanitarian orientation are genuinely nourishing and productive. The risk is the same idealisation that Neptune brings to all its house placements — friends and associates may appear more trustworthy, more aligned with your values, or more genuinely supportive than they actually are, and the year may require a more sober reassessment of who is genuinely in your corner. Long-range aspirations may be inspired and beautiful but may also lack the practical definition that makes them achievable. Dreams for the future are expanded under Neptune's influence but benefit from regular grounding in the specific, practical steps that genuine achievement requires. Collective involvement in creative, spiritual, or humanitarian causes is particularly rewarding and may be among the year's most meaningful experiences.`,

  12: `Solar Return Neptune in the twelfth house is Neptune in its natural domicile — the twelfth house is associated with Pisces, the sign Neptune rules — and the result is a year of unusually intense and unusually productive engagement with the spiritual, the hidden, and the transcendent dimensions of life. The boundary between the conscious and unconscious mind is at its most permeable. Dreams are vivid, symbolic, and often genuinely illuminating. Spiritual practice of any authentic kind — meditation, contemplative prayer, creative solitude, deep immersion in art or music — is more immediately rewarding and more genuinely transformative than in most years. Compassionate service, work with those who are vulnerable or suffering, and engagement with whatever is hidden or invisible in the world carry a quality of deep meaning. The twelfth house is also the house of what is released and dissolved, and Neptune here can produce a year of profound and healing letting go — the gentle dissolution of old patterns, old griefs, and old self-limiting beliefs that have been maintained past their usefulness. The risk of Neptune in its own house is the most refined form of Neptunian evasion — the genuine spiritual sensitivity of this placement can become a way of remaining beautifully above the more difficult demands of ordinary life. The year is most fully lived when spiritual depth and genuine earthly engagement are held together rather than offered as alternatives.`,
};
