// SR Planets in Signs — merged from individual planet files
// Source files:
//   - sun_in_signs.ts (Sun_Aries through Sun_Pisces)
//   - moon_in_signs_short.ts (Moon_Aries through Moon_Pisces)
//   - mercury_in_signs.ts (Mercury_Aries through Mercury_Pisces)
//   - venus_in_signs.ts (Venus_Aries through Venus_Pisces)
//   - mars_in_signs.ts (Mars_Aries through Mars_Pisces)
//   - jupiter_in_signs.ts (Jupiter_Aries through Jupiter_Pisces)
//   - saturn_in_signs.ts (Saturn_Aries through Saturn_Pisces)
//   - uranus_in_signs.ts (Uranus_Aries through Uranus_Pisces)
//   - neptune_in_signs.ts (Neptune_Aries through Neptune_Pisces)
//   - pluto_in_signs.ts (Pluto_Aries through Pluto_Pisces)
// Total: 120 entries (10 planets × 12 zodiac signs)

export const PLANETS_IN_SIGNS: Record<string, string> = {

  // Sun in Signs (12 entries)
  Sun_Aries: `Solar return Sun in Aries brings urgency, initiative, and self-assertiveness to the year's central themes and questions of identity and direction. What is begun under this influence carries the force and speed of genuine personal commitment, and the year tends to reward those who act on conviction rather than waiting for perfect conditions. The characteristic risk is that of moving faster than wisdom ordinarily advises — the impulse to initiate is vivid and the confidence is real, but the consequences of hasty action are fully as real.`,

  Sun_Taurus: `Solar return Sun in Taurus brings a quality of patience, material focus, and the steady consolidation of what has been begun to the year's central themes and questions of identity and direction. The year's energy is slower-moving and more cautious than some, but what is built under this influence tends to be genuinely durable. The characteristic risk is that of mistaking comfort for progress — the year rewards those who are willing to move deliberately but genuinely forward rather than those who mistake inertia for prudence.`,

  Sun_Gemini: `Solar return Sun in Gemini brings intellectual curiosity, communicative energy, and the making of connections to the year's central themes and questions of identity and direction. The year's energy is mental and versatile, and the primary work tends to be the clarification and articulation of what is genuinely true. The characteristic risk is that of mistaking the ability to say something for the truthfulness of what is said — the year rewards those who use the year's communicative gifts in service of genuine clarity rather than in service of the merely clever.`,

  Sun_Cancer: `Solar return Sun in Cancer is Sun in its exaltation, bringing emotional depth, genuine nurture, and the deepening of intimate connection to the year's central themes and questions of identity and direction. The year's energy is introverted and feeling-centred, and the primary work tends to be the cultivation of genuine security and authentic belonging. The characteristic risk is that of excessive caution or the prioritisation of comfort over growth — the year rewards those who use the year's emotional intelligence in service of genuine development rather than mere protection.`,

  Sun_Leo: `Solar return Sun in Leo brings creative self-expression, personal confidence, and the desire to be genuinely seen and recognised to the year's central themes and questions of identity and direction. The year's energy is expansive and outward-facing, and what is produced or expressed under this influence carries the force of genuine personal investment. The characteristic risk is that of self-promotion that substitutes for genuine substance — the year rewards those who use the year's creative confidence in service of work that is genuinely worth doing rather than mere self-aggrandisement.`,

  Sun_Virgo: `Solar return Sun in Virgo brings precision, practical focus, and the commitment to genuine usefulness to the year's central themes and questions of identity and direction. The year's energy is analytical and service-oriented, and the primary work tends to be the refinement of daily practice and the improvement of what is already in hand. The characteristic risk is that of perfectionism that becomes paralysing — the year rewards those who use the year's discriminating intelligence in service of genuine improvement rather than those for whom the pursuit of perfect becomes the enemy of the good.`,

  Sun_Libra: `Solar return Sun in Libra brings relational focus, diplomatic grace, and the honest assessment of partnership and fairness to the year's central themes and questions of identity and direction. The year's energy is collaborative and other-oriented, and the primary work tends to be the clarification of what genuine reciprocity and genuine equality actually require. The characteristic risk is that of the loss of personal direction in the service of maintaining relationship harmony — the year rewards those who use the year's relational intelligence in service of genuine mutuality rather than those for whom peace becomes the enemy of truth.`,

  Sun_Scorpio: `Solar return Sun in Scorpio brings intensity, penetrating insight, and the willingness to engage with what is hidden and transformative to the year's central themes and questions of identity and direction. The year's energy is concentrated and deep, and the primary work tends to be the honest engagement with what is most carefully avoided. The characteristic risk is that of the confusion of genuine depth with obsessive engagement with darkness — the year rewards those who use the year's penetrating intelligence in service of genuine transformation rather than those for whom the pursuit of darkness becomes an end in itself.`,

  Sun_Sagittarius: `Solar return Sun in Sagittarius brings expansiveness, philosophical vision, and the pursuit of meaning and understanding to the year's central themes and questions of identity and direction. The year's energy is broad and forward-looking, and the primary work tends to be the expansion of the worldview and the honest engagement with what lies beyond the comfortable and familiar. The characteristic risk is that of optimism that becomes naive or vision that becomes evasive — the year rewards those who use the year's expansive intelligence in service of genuine understanding rather than those for whom the pursuit of the inspiring becomes the enemy of the honest.`,

  Sun_Capricorn: `Solar return Sun in Capricorn is Sun in its exaltation, bringing discipline, genuine ambition, and the patient building of what will last to the year's central themes and questions of identity and direction. The year's energy is serious and structural, and the primary work tends to be the creation of lasting foundations for future development. The characteristic risk is that of an excess of caution or the prioritisation of worldly achievement over genuine development — the year rewards those who use the year's disciplinary focus in service of genuinely meaningful building rather than mere accumulation or status.`,

  Sun_Aquarius: `Solar return Sun in Aquarius brings originality, collective consciousness, and the pursuit of what is genuinely innovative to the year's central themes and questions of identity and direction. The year's energy is inventive and future-oriented, and the primary work tends to be the creation of what has not yet existed. The characteristic risk is that of innovation that is merely unconventional or the pursuit of the genuinely new without the patience required to actualise it — the year rewards those who use the year's innovative intelligence in service of what will genuinely matter rather than those for whom the pursuit of the different becomes an end in itself.`,

  Sun_Pisces: `Solar return Sun in Pisces brings spiritual sensitivity, compassionate imagination, and the dissolution of rigid boundaries between self and other to the year's central themes and questions of identity and direction. The year's energy is fluid and boundless, and the primary work tends to be the cultivation of genuine compassion and the honest engagement with what lies beyond rational understanding. The characteristic risk is that of a loss of personal boundaries or the confusion of compassion with the loss of discernment — the year rewards those who use the year's spiritual sensitivity in service of genuine compassion rather than those for whom the loss of self becomes the primary work.`,

  // Moon in Signs (12 entries)
  Moon_Aries: `Solar return Moon in Aries brings immediacy, reactivity, and genuine courage to the year's emotional tone and instinctive responses. The emotional body is quick to respond and quick to recover, and the year tends to reward those who trust their instincts and act on them without excessive deliberation. The characteristic risk is that of reactivity without wisdom or the impulse to respond before genuine reflection — the year favours those who use the Moon's natural courage as a bridge to genuine action rather than those who become imprisoned by hesitation.`,

  Moon_Taurus: `Solar return Moon in Taurus brings steadiness, sensory richness, and the need for genuine material and emotional security to the year's emotional tone and instinctive responses. The emotional body is stable and reliable, and the year tends to reward those who take time to build real security rather than seeking it through panic or haste. The characteristic risk is that of excessive attachment to security or the use of comfort as a substitute for genuine engagement — the year favours those who use the Moon's steadiness as a foundation for genuine growth rather than those for whom safety becomes an excuse for stagnation.`,

  Moon_Gemini: `Solar return Moon in Gemini brings mental curiosity, communicative fluency, and a need for variety and intellectual stimulation to the year's emotional tone and instinctive responses. The emotional body is quick-moving and restless, and the year tends to reward those who follow their curiosity and make the connections their instincts suggest. The characteristic risk is that of emotional superficiality or the use of communication as a substitute for genuine feeling — the year favours those who use the Moon's natural fluency as a bridge to deeper understanding rather than those for whom talking becomes a substitute for feeling.`,

  Moon_Cancer: `Solar return Moon in Cancer is Moon in its domicile, bringing emotional depth, genuine nurture, and the need for authentic belonging to the year's emotional tone and instinctive responses. The emotional body is sensitive and permeable, and the year tends to reward those who honour their genuine emotional needs rather than denying them in the service of apparent strength. The characteristic risk is that of excessive defensiveness or the use of emotional sensitivity as an excuse for withdrawal — the year favours those who use the Moon's natural depth as a bridge to genuine intimacy rather than those for whom protection becomes a substitute for connection.`,

  Moon_Leo: `Solar return Moon in Leo brings dramatic expression, emotional generosity, and the need to be genuinely valued and acknowledged to the year's emotional tone and instinctive responses. The emotional body is warm and expansive, and the year tends to reward those who open their hearts and allow themselves to be genuinely seen. The characteristic risk is that of emotional performance or the need for recognition becoming more important than the authenticity it should reflect — the year favours those who use the Moon's natural warmth as a bridge to genuine connection rather than those for whom the desire to be seen becomes a substitute for being genuinely seen.`,

  Moon_Virgo: `Solar return Moon in Virgo brings analytical precision, the impulse toward service, and the need for genuine usefulness to the year's emotional tone and instinctive responses. The emotional body is discerning and practical, and the year tends to reward those who channel their emotional intelligence toward genuine improvement and real help. The characteristic risk is that of emotional coldness or the use of analysis as a substitute for genuine feeling — the year favours those who use the Moon's natural precision as a bridge to genuine care rather than those for whom the pursuit of perfection becomes a substitute for the messy authenticity of real emotion.`,

  Moon_Libra: `Solar return Moon in Libra brings relational focus, diplomatic grace, and the need for genuine partnership and fairness to the year's emotional tone and instinctive responses. The emotional body is oriented toward others, and the year tends to reward those who invest genuinely in relationship while maintaining their own centre. The characteristic risk is that of the loss of emotional authenticity in the service of harmony or the use of politeness as a substitute for genuine honesty — the year favours those who use the Moon's natural grace as a bridge to genuine connection rather than those for whom the need for harmony becomes more important than the truth.`,

  Moon_Scorpio: `Solar return Moon in Scorpio brings emotional intensity, penetrating honesty, and the need to engage with what is most difficult and hidden to the year's emotional tone and instinctive responses. The emotional body is deep and powerful, and the year tends to reward those who are willing to go beneath the surface and engage with genuine transformation. The characteristic risk is that of emotional obsession or the use of intensity as a substitute for genuine engagement — the year favours those who use the Moon's natural depth as a bridge to genuine healing rather than those for whom the pursuit of darkness becomes an end in itself.`,

  Moon_Sagittarius: `Solar return Moon in Sagittarius brings optimism, a need for genuine meaning and understanding, and the impulse toward expansion to the year's emotional tone and instinctive responses. The emotional body is buoyant and forward-looking, and the year tends to reward those who allow their hopes and dreams to guide them toward genuine growth. The characteristic risk is that of emotional naivety or the use of optimism as a substitute for genuine engagement with what is difficult — the year favours those who use the Moon's natural hopefulness as a bridge to genuine development rather than those for whom the pursuit of the inspiring becomes a substitute for the honest.`,

  Moon_Capricorn: `Solar return Moon in Capricorn brings emotional restraint, the need for genuine responsibility and achievement, and the impulse toward self-reliance to the year's emotional tone and instinctive responses. The emotional body is controlled and serious, and the year tends to reward those who meet their emotional needs through genuine accomplishment and the patient building of what is real. The characteristic risk is that of emotional suppression or the use of self-reliance as a substitute for genuine connection — the year favours those who use the Moon's natural discipline as a bridge to genuine maturity rather than those for whom the need for control becomes more important than the possibility of authentic feeling.`,

  Moon_Aquarius: `Solar return Moon in Aquarius brings emotional detachment, a need for genuine independence and innovation, and the impulse toward the collective good to the year's emotional tone and instinctive responses. The emotional body is objective and future-oriented, and the year tends to reward those who maintain their emotional independence while engaging genuinely with others. The characteristic risk is that of emotional coldness or the use of objectivity as a substitute for genuine compassion — the year favours those who use the Moon's natural clarity as a bridge to genuine understanding rather than those for whom the pursuit of objectivity becomes more important than the possibility of authentic feeling.`,

  Moon_Pisces: `Solar return Moon in Pisces brings emotional sensitivity, spiritual attunement, and the dissolution of rigid boundaries between self and other to the year's emotional tone and instinctive responses. The emotional body is permeable and boundless, and the year tends to reward those who trust their intuition and allow their compassion to guide their choices. The characteristic risk is that of the loss of emotional boundaries or the use of sensitivity as a substitute for genuine engagement — the year favours those who use the Moon's natural compassion as a bridge to genuine healing rather than those for whom the dissolution of self becomes an end in itself.`,

  // Mercury in Signs (12 entries)
  Mercury_Aries: `Solar return Mercury in Aries brings speed, directness, and competitive intellectual energy to the year's mental style and communicative approach. The mind operates quickly and decisively, and the year tends to reward those who trust their rapid conclusions and act on them without excessive second-guessing. The characteristic risk is that of premature judgment or the assumption that speed equals accuracy — the year favours those who use Mercury's natural quickness as a bridge to genuine understanding rather than those for whom the first impulse becomes the final word.`,

  Mercury_Taurus: `Solar return Mercury in Taurus brings deliberation, practical focus, and the commitment to genuine clarity and usefulness to the year's mental style and communicative approach. The mind operates slowly but thoroughly, and the year tends to reward those who take time to think things through and communicate with precision and care. The characteristic risk is that of mental stubbornness or the equation of slow thinking with deep thinking — the year favours those who use Mercury's natural deliberation as a bridge to genuine understanding rather than those for whom the refusal to reconsider becomes more important than the discovery of what is actually true.`,

  Mercury_Gemini: `Solar return Mercury in Gemini is Mercury in its domicile, bringing intellectual fluency, communicative brilliance, and the capacity to hold multiple perspectives simultaneously to the year's mental style and communicative approach. The mind is at its most agile and most creative, and the year tends to reward those who follow their intellectual curiosity wherever it leads. The characteristic risk is that of intellectual superficiality or the equation of the ability to think about something with the possession of genuine understanding — the year favours those who use Mercury's natural fluency as a bridge to genuine depth rather than those for whom the making of clever connections becomes more important than the discovery of what is actually true.`,

  Mercury_Cancer: `Solar return Mercury in Cancer brings intuitive intelligence, emotional understanding, and the orientation of all communication toward care and connection to the year's mental style and communicative approach. The mind operates through feeling as much as through logic, and the year tends to reward those who honour their instincts and communicate from genuine emotional awareness. The characteristic risk is that of the equation of feeling with thinking or the use of emotional reasoning as a substitute for genuine analysis — the year favours those who use Mercury's natural intuition as a bridge to genuine understanding rather than those for whom the preference for how something feels becomes more important than the discovery of what is actually true.`,

  Mercury_Leo: `Solar return Mercury in Leo brings dramatic communication, creative expression, and the orientation of all thinking toward personal significance to the year's mental style and communicative approach. The mind is engaged and expressive, and the year tends to reward those who invest their intellectual energy in ideas and expressions that matter genuinely to them. The characteristic risk is that of intellectual performance or the equation of the ability to articulate something with the truth of what is being articulated — the year favours those who use Mercury's natural expressiveness as a bridge to genuine communication rather than those for whom the desire to be heard becomes more important than the truth of what is being said.`,

  Mercury_Virgo: `Solar return Mercury in Virgo is Mercury in its exaltation, bringing precision, analytical rigor, and the commitment to genuine usefulness and clarity to the year's mental style and communicative approach. The mind is at its most discerning and most practical, and the year tends to reward those who apply their analytical gifts to real problems in service of genuine improvement. The characteristic risk is that of perfectionism or the equation of the ability to find fault with the possession of genuine wisdom — the year favours those who use Mercury's natural precision as a bridge to genuine understanding rather than those for whom the pursuit of perfect becomes more important than the achievement of good.`,

  Mercury_Libra: `Solar return Mercury in Libra brings diplomatic communication, the capacity to hold opposing viewpoints simultaneously, and the orientation of all thinking toward fairness and relationship to the year's mental style and communicative approach. The mind is engaged in constant balance, and the year tends to reward those who are willing to see multiple perspectives and communicate with grace and diplomacy. The characteristic risk is that of intellectual paralysis or the equation of the ability to understand both sides with the possession of genuine wisdom — the year favours those who use Mercury's natural diplomacy as a bridge to genuine understanding rather than those for whom the pursuit of perfect balance becomes more important than the discovery of what is actually true.`,

  Mercury_Scorpio: `Solar return Mercury in Scorpio brings penetrating investigation, the capacity to perceive what is hidden, and the orientation of all communication toward truth and transformation to the year's mental style and communicative approach. The mind is engaged in constant probing, and the year tends to reward those who are willing to go beneath the surface and pursue genuine understanding wherever it leads. The characteristic risk is that of psychological obsession or the equation of the ability to perceive hidden motives with the possession of genuine wisdom — the year favours those who use Mercury's natural penetration as a bridge to genuine understanding rather than those for whom the pursuit of secrets becomes more important than the discovery of what is actually true.`,

  Mercury_Sagittarius: `Solar return Mercury in Sagittarius brings expansive thinking, the pursuit of broad philosophical understanding, and the orientation of all communication toward meaning and vision to the year's mental style and communicative approach. The mind is engaged in constant expansion, and the year tends to reward those who are willing to follow their intellectual curiosity beyond the boundaries of the comfortable and familiar. The characteristic risk is that of intellectual grandiosity or the equation of the ability to think in broad terms with the possession of genuine wisdom — the year favours those who use Mercury's natural expansiveness as a bridge to genuine understanding rather than those for whom the pursuit of the impressive becomes more important than the discovery of what is actually true.`,

  Mercury_Capricorn: `Solar return Mercury in Capricorn brings disciplined thinking, the commitment to practical clarity and usefulness, and the orientation of all communication toward genuine achievement to the year's mental style and communicative approach. The mind is engaged in careful construction, and the year tends to reward those who apply their thinking to real problems and real solutions that matter in the material world. The characteristic risk is that of intellectual rigidity or the equation of the ability to construct a logical argument with the possession of genuine wisdom — the year favours those who use Mercury's natural discipline as a bridge to genuine understanding rather than those for whom the pursuit of the provable becomes more important than the discovery of what is actually true.`,

  Mercury_Aquarius: `Solar return Mercury in Aquarius is Mercury in its traditional domicile, bringing innovative thinking, the capacity to perceive patterns and connections, and the orientation of all communication toward collective good to the year's mental style and communicative approach. The mind is engaged in constant pattern recognition, and the year tends to reward those who are willing to think in genuinely original ways and communicate their insights to others. The characteristic risk is that of intellectual arrogance or the equation of the ability to perceive novel connections with the possession of genuine wisdom — the year favours those who use Mercury's natural innovation as a bridge to genuine understanding rather than those for whom the pursuit of the novel becomes more important than the discovery of what is actually true.`,

  Mercury_Pisces: `Solar return Mercury in Pisces brings intuitive thinking, the capacity to perceive the poetic and metaphorical dimensions of communication, and the orientation of all thinking toward compassion and spiritual understanding to the year's mental style and communicative approach. The mind is engaged in constant association and metaphor, and the year tends to reward those who trust their intuition and communicate through images and feelings as much as through logic. The characteristic risk is that of intellectual confusion or the equation of the ability to perceive emotional resonance with the possession of genuine clarity — the year favours those who use Mercury's natural intuition as a bridge to genuine understanding rather than those for whom the pursuit of the poetic becomes more important than the discovery of what is actually true.`,

  // Venus in Signs (12 entries)
  Venus_Aries: `Solar return Venus in Aries brings directness, the impulse to pursue what is desired, and genuine preference in matters of attraction and aesthetic taste to the year's relational style and capacity for pleasure. Desire is clear and unambiguous, and the year tends to reward those who act on their genuine preferences without excessive hesitation or second-guessing. The characteristic risk is that of hasty commitment or the equation of the intensity of desire with the depth of feeling — the year favours those who use Venus's natural directness as a bridge to genuine connection rather than those for whom the impulse to pursue becomes more important than the exploration of what is actually worth pursuing.`,

  Venus_Taurus: `Solar return Venus in Taurus is Venus in its domicile, bringing sensory richness, material generosity, and the profound capacity for genuine pleasure and lasting affection to the year's relational style and capacity for pleasure. Desire is steady and reliable, and the year tends to reward those who allow themselves the genuine pleasure of sensory and material richness. The characteristic risk is that of excessive attachment or the equation of possession with love — the year favours those who use Venus's natural steadiness as a bridge to genuine affection rather than those for whom the need to hold onto what is desired becomes more important than the discovery of what is actually worth holding.`,

  Venus_Gemini: `Solar return Venus in Gemini brings communicative charm, intellectual attraction, and the need for genuine variety and mental stimulation in matters of relationship and pleasure to the year's relational style and capacity for pleasure. Desire is mental and curious, and the year tends to reward those who are willing to engage with multiple attractions and keep their relational life interesting through communication and novelty. The characteristic risk is that of emotional superficiality or the equation of the ability to charm with genuine affection — the year favours those who use Venus's natural fluency as a bridge to genuine connection rather than those for whom the making of pleasant conversation becomes more important than the discovery of what is actually worth connecting with.`,

  Venus_Cancer: `Solar return Venus in Cancer brings emotional depth, genuine nurture, and the profound capacity for tender affection and authentic belonging to the year's relational style and capacity for pleasure. Desire is emotional and protective, and the year tends to reward those who are willing to be vulnerable and allow themselves to need what they genuinely desire. The characteristic risk is that of emotional neediness or the equation of care with possession — the year favours those who use Venus's natural tenderness as a bridge to genuine intimacy rather than those for whom the need to be cared for becomes more important than the discovery of what is actually worth caring for.`,

  Venus_Leo: `Solar return Venus in Leo brings generous expression, creative romance, and the impulse toward genuine significance and personal investment in matters of affection and pleasure to the year's relational style and capacity for pleasure. Desire is warm and expansive, and the year tends to reward those who invest their hearts fully in what and whom they love. The characteristic risk is that of dramatic excess or the equation of the intensity of feeling with the authenticity of affection — the year favours those who use Venus's natural warmth as a bridge to genuine connection rather than those for whom the desire to be seen as loving becomes more important than the discovery of what is actually worth loving.`,

  Venus_Virgo: `Solar return Venus in Virgo brings discerning taste, the impulse toward genuine service in relationship, and the capacity for tender care and practical support to the year's relational style and capacity for pleasure. Desire is subtle and particular, and the year tends to reward those who find their pleasure in the careful tending of what they love. The characteristic risk is that of excessive criticism or the equation of the ability to perceive faults with the possession of genuine affection — the year favours those who use Venus's natural precision as a bridge to genuine care rather than those for whom the pursuit of perfect becomes more important than the celebration of what is actually worth loving.`,

  Venus_Libra: `Solar return Venus in Libra is Venus in its exaltation, bringing genuine grace, relational harmony, and the profound capacity for partnership and reciprocal affection to the year's relational style and capacity for pleasure. Desire is balanced and fair, and the year tends to reward those who invest in genuine partnership and maintain relational harmony through honesty and mutual respect. The characteristic risk is that of the loss of authenticity in the service of harmony or the equation of agreeableness with genuine affection — the year favours those who use Venus's natural grace as a bridge to genuine connection rather than those for whom the pursuit of harmony becomes more important than the discovery of what is actually worth connecting with.`,

  Venus_Scorpio: `Solar return Venus in Scorpio brings intense passion, the capacity for profound psychological and physical intimacy, and the willingness to engage fully with what is most hidden and transformative to the year's relational style and capacity for pleasure. Desire is powerful and all-consuming, and the year tends to reward those who are willing to go all the way down and engage with genuine transformation. The characteristic risk is that of emotional obsession or the equation of the intensity of passion with the authenticity of love — the year favours those who use Venus's natural penetration as a bridge to genuine intimacy rather than those for whom the pursuit of intensity becomes more important than the discovery of what is actually worth desiring.`,

  Venus_Sagittarius: `Solar return Venus in Sagittarius brings expansive romance, the impulse toward genuine adventure in matters of the heart, and the capacity for generous and optimistic affection to the year's relational style and capacity for pleasure. Desire is idealistic and forward-looking, and the year tends to reward those who are willing to take risks and allow their hopes to guide their choices in love. The characteristic risk is that of romantic idealism or the equation of the ability to inspire with the possession of genuine affection — the year favours those who use Venus's natural generosity as a bridge to genuine connection rather than those for whom the pursuit of the romantic ideal becomes more important than the discovery of what is actually worth pursuing.`,

  Venus_Capricorn: `Solar return Venus in Capricorn brings enduring commitment, the willingness to build something real and lasting in matters of affection, and the capacity for steady and reliable love to the year's relational style and capacity for pleasure. Desire is patient and serious, and the year tends to reward those who are willing to commit their affection to what is genuinely worth building. The characteristic risk is that of emotional restraint or the equation of commitment with love — the year favours those who use Venus's natural steadiness as a bridge to genuine affection rather than those for whom the need for control becomes more important than the discovery of what is actually worth desiring.`,

  Venus_Aquarius: `Solar return Venus in Aquarius brings intellectual attraction, genuine friendship as the foundation of affection, and the capacity for partnership that honors genuine independence to the year's relational style and capacity for pleasure. Desire is unconventional and idealistic, and the year tends to reward those who are willing to connect with others on genuinely equal terms. The characteristic risk is that of emotional detachment or the equation of the ability to think about affection with the possession of genuine feeling — the year favours those who use Venus's natural openness as a bridge to genuine connection rather than those for whom the need for independence becomes more important than the discovery of what is actually worth connecting with.`,

  Venus_Pisces: `Solar return Venus in Pisces is Venus in its traditional domicile, bringing spiritual romance, the dissolution of boundaries between self and other, and the profound capacity for compassionate and transcendent affection to the year's relational style and capacity for pleasure. Desire is boundless and spiritualised, and the year tends to reward those who are willing to dissolve their boundaries and allow themselves to be genuinely touched by what they encounter. The characteristic risk is that of the loss of discernment or the equation of the ability to feel compassion with the possession of genuine wisdom in matters of the heart — the year favours those who use Venus's natural compassion as a bridge to genuine connection rather than those for whom the pursuit of transcendence becomes more important than the discovery of what is actually worth desiring.`,

  // Mars in Signs (12 entries)
  Mars_Aries: `Solar return Mars in Aries is Mars in its domicile, bringing raw drive, immediate assertion, and the unambiguous expression of desire and anger to the year's energy style and assertive approach. The year moves quickly and decisively, and the year tends to reward those who act on their convictions without excessive hesitation or second-guessing. The characteristic risk is that of hasty action or the equation of speed with correctness — the year favours those who use Mars's natural courage as a bridge to genuine accomplishment rather than those for whom the impulse to act becomes more important than the consideration of what is actually worth doing.`,

  Mars_Taurus: `Solar return Mars in Taurus brings patience, stubborn persistence, and the willingness to do the sustained work required to build something genuinely durable and real to the year's energy style and assertive approach. The year moves slowly but steadily, and the year tends to reward those who are willing to stick with what matters until it is genuinely complete. The characteristic risk is that of obstinacy or the equation of unwillingness to move with strength — the year favours those who use Mars's natural persistence as a bridge to genuine accomplishment rather than those for whom the refusal to yield becomes more important than the discovery of when flexibility is actually required.`,

  Mars_Gemini: `Solar return Mars in Gemini brings intellectual aggression, mental quickness, and the capacity to fight with words as much as with direct action to the year's energy style and assertive approach. The year's energy is mental and communicative, and the year tends to reward those who use their intellectual sharpness in service of genuine engagement. The characteristic risk is that of argumentativeness or the equation of the ability to debate with the possession of genuine conviction — the year favours those who use Mars's natural quickness as a bridge to genuine accomplishment rather than those for whom the desire to win the argument becomes more important than the discovery of what is actually true.`,

  Mars_Cancer: `Solar return Mars in Cancer brings protective intensity, emotional assertion, and the willingness to fight for what matters most — home, family, and genuine emotional security to the year's energy style and assertive approach. The year's energy is defensive and protective, and the year tends to reward those who are willing to stand up for their emotional needs and what they genuinely care about. The characteristic risk is that of passive aggression or the equation of sensitivity with weakness — the year favours those who use Mars's natural protectiveness as a bridge to genuine courage rather than those for whom the need to defend becomes more important than the discovery of what is actually worth defending.`,

  Mars_Leo: `Solar return Mars in Leo brings courageous self-expression, creative intensity, and the willingness to fight for genuine significance and personal integrity to the year's energy style and assertive approach. The year's energy is brave and outward-facing, and the year tends to reward those who are willing to put themselves fully forward and stand up for what they genuinely believe. The characteristic risk is that of arrogance or the equation of courage with righteousness — the year favours those who use Mars's natural boldness as a bridge to genuine courage rather than those for whom the desire to be seen as courageous becomes more important than the discovery of what is actually worth standing up for.`,

  Mars_Virgo: `Solar return Mars in Virgo brings precise action, the willingness to do detailed work, and the commitment to genuine improvement and usefulness to the year's energy style and assertive approach. The year's energy is careful and analytical, and the year tends to reward those who apply their energy to real problems and real solutions. The characteristic risk is that of excessive criticism or the equation of the ability to find fault with the possession of genuine strength — the year favours those who use Mars's natural precision as a bridge to genuine accomplishment rather than those for whom the pursuit of perfect becomes more important than the achievement of good.`,

  Mars_Libra: `Solar return Mars in Libra brings diplomatic assertion, the willingness to fight for fairness and equality, and the capacity to maintain balance while still taking genuine action to the year's energy style and assertive approach. The year's energy is careful and collaborative, and the year tends to reward those who are willing to assert themselves while maintaining relational harmony. The characteristic risk is that of paralysis or the equation of the need for fairness with the possession of genuine strength — the year favours those who use Mars's natural diplomacy as a bridge to genuine accomplishment rather than those for whom the pursuit of harmony becomes more important than the discovery of when decisive action is actually required.`,

  Mars_Scorpio: `Solar return Mars in Scorpio brings penetrating intensity, the willingness to go all the way down, and the capacity for sustained engagement with what is most difficult and transformative to the year's energy style and assertive approach. The year's energy is deep and concentrated, and the year tends to reward those who are willing to engage with genuine psychological and material transformation. The characteristic risk is that of obsession or the equation of the ability to go deep with the possession of genuine strength — the year favours those who use Mars's natural penetration as a bridge to genuine accomplishment rather than those for whom the pursuit of secrets becomes more important than the discovery of what is actually worth pursuing.`,

  Mars_Sagittarius: `Solar return Mars in Sagittarius brings expansive energy, the willingness to take risks and pursue genuine growth, and the capacity for bold action in service of vision and meaning to the year's energy style and assertive approach. The year's energy is broad and forward-looking, and the year tends to reward those who are willing to follow their convictions into new territory. The characteristic risk is that of recklessness or the equation of optimism with wisdom — the year favours those who use Mars's natural boldness as a bridge to genuine accomplishment rather than those for whom the desire to explore becomes more important than the discovery of what is actually worth pursuing.`,

  Mars_Capricorn: `Solar return Mars in Capricorn brings disciplined ambition, strategic focus, and the willingness to do sustained work in service of genuine achievement and lasting power to the year's energy style and assertive approach. The year's energy is serious and structural, and the year tends to reward those who apply their ambition to goals that matter and are willing to do the sustained work required to achieve them. The characteristic risk is that of excessive control or the equation of the ability to build with the possession of genuine wisdom — the year favours those who use Mars's natural discipline as a bridge to genuine accomplishment rather than those for whom the need for control becomes more important than the discovery of when flexibility is actually required.`,

  Mars_Aquarius: `Solar return Mars in Aquarius is Mars in its traditional domicile, bringing innovative energy, the willingness to challenge convention, and the capacity for action in service of genuine change and collective good to the year's energy style and assertive approach. The year's energy is inventive and future-oriented, and the year tends to reward those who are willing to fight for what is genuinely new and genuinely good. The characteristic risk is that of revolutionary excess or the equation of the ability to challenge authority with the possession of genuine wisdom — the year favours those who use Mars's natural innovation as a bridge to genuine accomplishment rather than those for whom the desire to be different becomes more important than the discovery of what is actually worth changing.`,

  Mars_Pisces: `Solar return Mars in Pisces brings compassionate action, the willingness to fight for what is vulnerable and in need, and the capacity for action guided by vision and spiritual conviction to the year's energy style and assertive approach. The year's energy is fluid and idealistic, and the year tends to reward those who are willing to put their energy in service of something larger than themselves. The characteristic risk is that of ineffectual idealism or the equation of good intentions with genuine accomplishment — the year favours those who use Mars's natural compassion as a bridge to genuine action rather than those for whom the desire to help becomes more important than the discovery of what is actually required to make a genuine difference.`,

  // Jupiter in Signs (12 entries)
  Jupiter_Aries: `Solar return Jupiter in Aries expands the year's opportunities through bold initiative, personal courage, and the willingness to go first without waiting for conditions to be perfect. Growth arrives through action rather than planning, and the year rewards those who trust their instincts and commit fully to what they are pursuing. The risk is the overconfidence that Aries Jupiter consistently produces — the belief that enthusiasm alone is sufficient preparation.`,

  Jupiter_Taurus: `Solar return Jupiter in Taurus expands the year's opportunities through material accumulation, sensory richness, and a patient, sustained approach to building what is genuinely valuable. Growth is slower than with other Jupiter signs but more tangibly durable — what is gained this year tends to be genuinely kept. Financial opportunity is real, though the Taurean tendency toward excess means that genuine abundance and overindulgence can be difficult to distinguish in the moment.`,

  Jupiter_Gemini: `Solar return Jupiter in Gemini expands the year's opportunities through intellectual curiosity, communicative reach, and the willingness to pursue multiple promising directions simultaneously. Growth arrives through the making of connections — between ideas, between people, between opportunities that appear unrelated until the right perspective reveals their common thread. The risk is the scattering of genuinely good opportunities across too many fronts to develop any of them to their full potential.`,

  Jupiter_Cancer: `Solar return Jupiter in Cancer is Jupiter in its exaltation, bringing exceptional warmth, emotional generosity, and a quality of genuine abundance in the domains of home, family, and inner life to the year. Growth arrives through emotional intelligence, through the deepening of genuine belonging, and through the willingness to nurture what is most truly valuable rather than what is merely impressive. The year is particularly supportive of domestic expansion, family development, and the cultivation of genuine inner security.`,

  Jupiter_Leo: `Solar return Jupiter in Leo expands the year's opportunities through creative confidence, generous self-expression, and a genuine willingness to be seen and to lead from the warmth of genuine personal investment. Growth arrives in proportion to the courage with which you put yourself and your work fully forward, and the year rewards those who resist the impulse to make themselves smaller than they are. The risk is the grandiosity that Jupiter in Leo can produce — the genuine gifts of this placement are most fully realised when they are in service of something larger than self-promotion.`,

  Jupiter_Virgo: `Solar return Jupiter in Virgo expands the year's opportunities through meticulous craft, genuine usefulness, and a willingness to do the detailed work that creates real and lasting value. Growth arrives through precision and honest improvement rather than through vision and bold initiative, and the year rewards those who are willing to go back and get it right rather than declare it finished and move on. The risk is that Jupiter's natural expansiveness and Virgo's natural perfectionism work against each other, producing anxiety rather than productive discernment.`,

  Jupiter_Libra: `Solar return Jupiter in Libra expands the year's opportunities through partnership, diplomatic grace, and the cultivation of relationships that are genuinely mutually enriching. Growth arrives through others — through the doors that significant partnerships open, through the opportunities that a well-tended network makes available, and through the creative and professional synergies that genuine collaboration produces. The year strongly favours joint ventures, significant new relationships, and any effort that benefits from the involvement of a skilled and well-chosen partner.`,

  Jupiter_Scorpio: `Solar return Jupiter in Scorpio expands the year's opportunities through depth, investigation, and the willingness to go where others are reluctant to look. Growth arrives through the honest engagement with what has been hidden — through research that uncovers what was concealed, through psychological work that releases what has been limiting, and through the shared resources and transformative alliances that Scorpio's penetrating intelligence makes possible. The year rewards those who are willing to go all the way down.`,

  Jupiter_Sagittarius: `Solar return Jupiter in Sagittarius is Jupiter in its domicile, bringing the fullest and most unimpeded expression of the planet's expansive, philosophical, and horizon-expanding energy to the year. Growth arrives through genuine adventurousness — through travel, through the pursuit of higher learning, through the honest expansion of the worldview beyond what has been comfortable and familiar. The year is among the most broadly fortunate of Jupiter placements, though the risk of excess is equally at its most fully expressed.`,

  Jupiter_Capricorn: `Solar return Jupiter in Capricorn expands the year's opportunities through disciplined ambition, strategic patience, and the willingness to do the sustained work that genuine achievement requires. Growth arrives more slowly than with other Jupiter signs but carries more genuine weight — what is built this year is built to last. The year rewards those who combine Jupiter's genuine confidence with Capricorn's honest assessment of what is actually required to achieve the goal.`,

  Jupiter_Aquarius: `Solar return Jupiter in Aquarius expands the year's opportunities through original thinking, collective involvement, and the pursuit of what is genuinely innovative rather than merely successful by conventional measures. Growth arrives through the willingness to depart from established frameworks and to pursue what is genuinely new — in ideas, in social involvements, and in the vision of what the future might become. The year strongly supports involvement with groups and causes that aspire to something genuinely larger than individual interest.`,

  Jupiter_Pisces: `Solar return Jupiter in Pisces is Jupiter in its traditional domicile, bringing a quality of spiritual generosity, compassionate expansiveness, and genuine grace to the year's opportunities. Growth arrives through openness, through the willingness to trust and to be guided by something larger than rational calculation, and through the compassionate engagement with what is most vulnerable and most in need of care. Creative and spiritual work is particularly inspired, and the year carries a quality of quiet but genuine good fortune that is more felt than seen.`,

  // Saturn in Signs (12 entries)
  Saturn_Aries: `Solar return Saturn in Aries imposes the year's discipline and limitation on the domain of personal initiative and self-assertion, requiring that impulse be subjected to genuine patience and honest assessment before it becomes action. The characteristic Aries urge to move first and think later is checked by Saturn's demand for accountability, and the year rewards those who learn to act with both courage and genuine forethought. The tension between urgency and restraint is the year's central creative challenge.`,

  Saturn_Taurus: `Solar return Saturn in Taurus imposes the year's discipline and limitation on the material world, requiring a more honest and more rigorous approach to financial management, the use of resources, and the relationship between what you have and what you genuinely need. Comfort and security cannot be assumed — they must be genuinely built through sustained and patient effort. The year rewards those who engage seriously with the material foundations of their lives rather than managing by optimistic approximation.`,

  Saturn_Gemini: `Solar return Saturn in Gemini imposes the year's discipline and limitation on the domain of communication and intellectual life, requiring that thinking be more structured, more honest, and more carefully expressed than Gemini's natural fluency normally demands. Writing and intellectual work proceed more slowly and with more genuine rigour, and the results — when the discipline is genuinely applied — tend to be more substantial and more lasting. Commitments to communicate clearly and precisely are more important and more demanding than in other years.`,

  Saturn_Cancer: `Solar return Saturn in Cancer is Saturn in its detriment, imposing the year's discipline and limitation on the domain of emotional life, home, and the need for genuine security and belonging in ways that can feel particularly constricting. Emotional needs feel more demanding and less easily met, domestic responsibilities weigh more heavily, and the inner life requires more honest and more structured attention than it usually receives. The year asks for genuine emotional maturity — the willingness to feel what is actually being felt rather than managing it from a safe distance.`,

  Saturn_Leo: `Solar return Saturn in Leo imposes the year's discipline and limitation on the domain of creative self-expression, personal confidence, and the desire to be genuinely seen and recognised. The impulse toward self-expression is checked by Saturn's demand for genuine substance over performance — the year asks whether what you are offering is genuinely worth offering, and withholds the easy recognition that less disciplined years might provide. Creative work produced under this influence tends to be harder-won and more genuinely solid.`,

  Saturn_Virgo: `Solar return Saturn in Virgo is one of the most naturally productive Saturn placements — the sign's native orientation toward precision, usefulness, and honest self-assessment aligns well with Saturn's own demands, producing a year of genuinely disciplined and genuinely useful work. The standards you hold yourself and others to are high, the attention to detail is exacting, and the results of sustained application tend to be among the most carefully crafted of any Saturn sign. The risk is perfectionism that becomes paralysis rather than precision that produces quality.`,

  Saturn_Libra: `Solar return Saturn in Libra is Saturn in its exaltation, bringing the year's discipline and structure to the domain of relationship, fairness, and the honest management of how you engage with others in ways that are genuinely productive and genuinely clarifying. Relationships are assessed with unusual honesty — what is equitable, what is genuinely reciprocal, and what has been maintained through habit rather than genuine mutual value are all brought into focus. Legal and contractual matters are taken more seriously and handled with more genuine care.`,

  Saturn_Scorpio: `Solar return Saturn in Scorpio imposes the year's discipline and limitation on the domain of shared resources, psychological depth, and the hidden dimensions of power and transformation. Financial arrangements with others require more careful and more honest management, and the psychological work of the year demands genuine engagement with what has been avoided rather than what is merely uncomfortable. The year rewards those willing to go into the most difficult interior territory with the honesty and patience that genuine transformation requires.`,

  Saturn_Sagittarius: `Solar return Saturn in Sagittarius imposes the year's discipline and limitation on the domain of belief, philosophical vision, and the broad horizons of meaning and understanding. The expansive optimism that Sagittarius naturally produces is subjected to Saturn's honest scrutiny — beliefs must be genuinely examined rather than merely held, and the vision of what is possible must be grounded in what is actually achievable rather than what is merely inspiring. The year rewards those who pursue genuine understanding rather than comfortable conviction.`,

  Saturn_Capricorn: `Solar return Saturn in Capricorn is Saturn in its domicile, bringing the fullest and most concentrated expression of the planet's demand for discipline, genuine achievement, and the patient building of what will last to the year's central themes. The year asks more of you professionally and personally than most, and delivers more genuinely lasting results to those who meet those demands with real commitment. What is built under Saturn in Capricorn tends to be among the most solid and most enduring work of a life.`,

  Saturn_Aquarius: `Solar return Saturn in Aquarius is Saturn in its traditional domicile, bringing discipline and structure to the domain of collective involvement, social responsibility, and the pursuit of what is genuinely innovative rather than merely unconventional. The year asks that radical ideas be submitted to the test of genuine usefulness — that vision be paired with the patient structural work required to make it real. Group involvements and collective projects are most rewarding when they are pursued with both genuine principle and genuine accountability.`,

  Saturn_Pisces: `Solar return Saturn in Pisces imposes the year's discipline and limitation on the domain of the spiritual, the imaginative, and the hidden interior life in ways that can feel both clarifying and constricting. The boundlessness that Pisces naturally inhabits is given form and structure by Saturn's demands — spiritual practice must be genuinely sustained rather than merely aspired to, and the creative imagination must be directed toward actual completion rather than beautiful incompletion. The year rewards those who bring genuine discipline to their most interior and most aspirational dimensions.`,

  // Uranus in Signs (12 entries)
  Uranus_Aries: `Solar return Uranus in Aries expresses the year's disruptive and liberating energy through sudden, courageous, and highly personal acts of self-assertion and new beginning. Breaks from the past are sharp and unambiguous — what is released is released completely, and what is initiated carries the force of genuine and irreversible departure.`,

  Uranus_Taurus: `Solar return Uranus in Taurus expresses the year's disruptive energy through sudden and sometimes unsettling revisions to what seemed most fixed and most reliable — financial structures, material circumstances, and deeply held values. Liberation arrives through the willingness to release attachment to security that was never as solid as it appeared and to find stability in a more genuinely flexible relationship with what you have and what you need.`,

  Uranus_Gemini: `Solar return Uranus in Gemini expresses the year's liberating and disruptive energy through sudden intellectual breakthroughs, unexpected communications, and a quality of electric speed in the movement between ideas and connections. The mind operates at its most innovative and most unpredictable, and the year favours those willing to follow an idea wherever it leads without insisting on knowing the destination in advance.`,

  Uranus_Cancer: `Solar return Uranus in Cancer expresses the year's disruptive energy through sudden and sometimes destabilising changes to home, family, and the emotional foundations of security and belonging. Liberation arrives through the willingness to release inherited family patterns and emotional structures that have been maintained through habit rather than genuine choice, and to build a sense of inner home on more authentically personal foundations.`,

  Uranus_Leo: `Solar return Uranus in Leo expresses the year's liberating energy through sudden creative breakthroughs, unexpected acts of self-expression, and a quality of genuinely original personal flair that refuses the conventional and the expected. The impulse toward authentic self-expression is at its most electrically alive, and the year rewards those willing to be genuinely and conspicuously themselves rather than a more comfortable approximation.`,

  Uranus_Virgo: `Solar return Uranus in Virgo expresses the year's disruptive and liberating energy through sudden revisions to work practices, health approaches, and the daily structures through which ordinary life is organised and sustained. Innovation arrives through the application of genuinely new methods to the practical dimensions of existence, and the year favours those willing to radically revise what has simply become habit in the name of what is genuinely more effective.`,

  Uranus_Libra: `Solar return Uranus in Libra expresses the year's liberating energy through sudden and sometimes unexpected changes in significant relationships, social structures, and the conventions through which partnership and fairness are normally managed. Liberation arrives through the willingness to engage with relationships on more genuinely equal and more genuinely honest terms than convention normally permits, even when that honesty disrupts what had seemed comfortably settled.`,

  Uranus_Scorpio: `Solar return Uranus in Scorpio expresses the year's disruptive energy through sudden and sometimes explosive surfacing of what has been hidden, repressed, or operating beneath the threshold of conscious awareness. Liberation arrives through the honest confrontation with what has been most carefully avoided, and the year favours those willing to go into the most difficult psychological and material territory without flinching.`,

  Uranus_Sagittarius: `Solar return Uranus in Sagittarius expresses the year's liberating energy through sudden philosophical breakthroughs, unexpected encounters with radically different belief systems, and a quality of electric expansiveness in the pursuit of meaning and understanding. The worldview is disrupted and enlarged simultaneously, and the year rewards those willing to let what they thought they knew be genuinely revised by what they actually encounter.`,

  Uranus_Capricorn: `Solar return Uranus in Capricorn expresses the year's disruptive energy through sudden and sometimes dramatic changes to professional structures, institutional arrangements, and the conventional definitions of achievement and authority. Liberation arrives through the willingness to rebuild career and public life on more genuinely authentic foundations, even when what must be dismantled to do so appeared solid and well-established.`,

  Uranus_Aquarius: `Solar return Uranus in Aquarius is Uranus in its domicile, bringing the fullest and most unimpeded expression of the planet's innovative, liberating, and collectively oriented energy to the year. The impulse toward genuine originality, social experimentation, and the radical revision of what has been accepted as normal is at its most alive and most productive, and the year strongly rewards those willing to be genuinely and consequentially different.`,

  Uranus_Pisces: `Solar return Uranus in Pisces expresses the year's liberating energy through sudden spiritual openings, unexpected creative inspiration, and a quality of electric permeability between the conscious and the unconscious dimensions of experience. Liberation arrives through the willingness to release the rigid boundaries of ordinary rational identity and to allow what is genuinely larger and more mysterious to move through the life with less resistance than usual.`,

  // Neptune in Signs (12 entries)
  Neptune_Aries: `Solar return Neptune in Aries dissolves the boundaries of individual self-assertion, bringing a quality of idealistic personal vision and a tendency to act on inspiration rather than calculation to the year's character. The risk is impulsive idealism — the confusion of what is passionately imagined with what is actually possible.`,

  Neptune_Taurus: `Solar return Neptune in Taurus dissolves the fixed outlines of material security and personal value, bringing a more fluid and more spiritually informed relationship with money, possessions, and what is genuinely worth having to the year. The risk is financial fog — a tendency to see material circumstances through the lens of what is wished for rather than what is actually present.`,

  Neptune_Gemini: `Solar return Neptune in Gemini dissolves the boundaries of ordinary rational communication, bringing a quality of inspired, poetic, and highly associative thinking to the year's intellectual life. The risk is the confusion of the brilliantly imagined with the reliably true — the mind is at its most creative and its least precise simultaneously.`,

  Neptune_Cancer: `Solar return Neptune in Cancer dissolves the boundaries between self and family, between personal feeling and the emotional field of the home, bringing a quality of deep compassionate attunement and sometimes overwhelming emotional permeability to the year. The risk is the loss of personal emotional boundaries in the service of others' needs.`,

  Neptune_Leo: `Solar return Neptune in Leo dissolves the boundaries of personal creative identity, bringing a quality of inspired, spiritually animated self-expression and a tendency toward romantic idealism about one's own gifts and significance to the year. The risk is the confusion of genuine creative vision with the desire to be seen as genuinely visionary.`,

  Neptune_Virgo: `Solar return Neptune in Virgo dissolves the clarity of analytical precision, bringing a quality of compassionate service, healing orientation, and sometimes paralysing self-doubt to the year's relationship with work and daily practice. The risk is the undermining of genuine discernment by an idealism that cannot be practically grounded.`,

  Neptune_Libra: `Solar return Neptune in Libra dissolves the fixed outlines of relationship and fairness, bringing a quality of romantic idealism, longing for genuine soul connection, and sometimes naive trust in the goodwill of others to the year's relational life. The risk is the idealisation of partners and the consequent disappointment when the reality beneath the ideal becomes unavoidable.`,

  Neptune_Scorpio: `Solar return Neptune in Scorpio dissolves the boundaries between the conscious and unconscious mind, bringing a quality of deep spiritual intensity, psychological permeability, and sometimes obsessive engagement with what is hidden and transformative to the year. The risk is the confusion of genuine depth with the fascination with darkness for its own sake.`,

  Neptune_Sagittarius: `Solar return Neptune in Sagittarius dissolves the fixed outlines of philosophical certainty, bringing a quality of spiritual seeking, visionary idealism, and a tendency toward beliefs that are more beautiful than verifiable to the year's relationship with meaning and understanding. The risk is the adoption of inspiring but fundamentally evasive belief systems that substitute transcendence for honest engagement.`,

  Neptune_Capricorn: `Solar return Neptune in Capricorn dissolves the fixed outlines of institutional authority and worldly ambition, bringing a quality of idealistic vocation and sometimes confused professional direction to the year's relationship with achievement and public life. The risk is the confusion of what is genuinely called for with what is merely conventionally impressive.`,

  Neptune_Aquarius: `Solar return Neptune in Aquarius dissolves the fixed outlines of social convention and collective identity, bringing a quality of utopian vision, humanitarian idealism, and sometimes unrealistic faith in collective human possibility to the year's relationship with community and the future. The risk is the confusion of inspiring collective vision with the hard and patient work that genuine social change actually requires.`,

  Neptune_Pisces: `Solar return Neptune in Pisces is Neptune in its domicile, bringing the fullest expression of the planet's dissolving, spiritually sensitising, and boundary-dissolving energy to the year in the sign most naturally aligned with those qualities. Spiritual openness, creative inspiration, and the compassionate dissolution of the barriers between self and other are at their most fully and most genuinely expressed.`,

  // Pluto in Signs (12 entries)
  Pluto_Aries: `Solar return Pluto in Aries intensifies the year's transformative energy through the domain of personal identity and the will to initiate, bringing a quality of ruthless self-reinvention and the compulsive destruction of what is no longer genuinely alive in the self. What is shed this year cannot be recovered — and was not worth recovering.`,

  Pluto_Taurus: `Solar return Pluto in Taurus intensifies the year's transformative energy through the domain of material reality and personal value, bringing a quality of deep and irreversible revision to the relationship between security, possession, and genuine worth. What seemed most fixed and most reliable is revealed as subject to the same process of stripping and rebuilding that Pluto applies to everything it touches.`,

  Pluto_Gemini: `Solar return Pluto in Gemini intensifies the year's transformative energy through the domain of communication and intellectual life, bringing a quality of penetrating investigative power and the compulsive need to get beneath the surface of every idea and every exchange. What is said and what is meant are subjected to a depth of scrutiny that ordinary intellectual life rarely demands.`,

  Pluto_Cancer: `Solar return Pluto in Cancer intensifies the year's transformative energy through the domain of home, family, and the deepest emotional foundations of security and belonging, bringing a quality of irreversible change to the structures through which intimate life has been organised and sustained. What is released from the family system and the inner emotional world tends to have been ready to go for longer than the year in which it finally does.`,

  Pluto_Leo: `Solar return Pluto in Leo intensifies the year's transformative energy through the domain of creative self-expression and personal power, bringing a quality of compulsive drive toward genuine creative significance and the stripping away of performance that substitutes for authentic self-expression. What emerges from the year's creative pressure is more genuinely and more powerfully the self.`,

  Pluto_Virgo: `Solar return Pluto in Virgo intensifies the year's transformative energy through the domain of work, health, and daily practice, bringing a quality of deep and sometimes ruthless revision to the structures of ordinary life and the relationship between genuine service and compulsive self-improvement. What is truly useful is separated, slowly and not always comfortably, from what has merely been habitual.`,

  Pluto_Libra: `Solar return Pluto in Libra intensifies the year's transformative energy through the domain of relationship and fairness, bringing a quality of deep and sometimes irreversible power dynamics to the most significant partnerships and the honest question of what genuine equality and genuine reciprocity actually require. Relationships that survive Pluto's scrutiny in Libra tend to be rebuilt on more honestly mutual foundations.`,

  Pluto_Scorpio: `Solar return Pluto in Scorpio is Pluto in its domicile, bringing the fullest and most concentrated expression of the planet's transformative, stripping, and ultimately regenerative energy to the year in the sign most naturally aligned with those qualities. Nothing that is not genuinely alive survives the year unchanged — and what does survive is more genuinely, more powerfully, and more irreversibly itself.`,

  Pluto_Sagittarius: `Solar return Pluto in Sagittarius intensifies the year's transformative energy through the domain of belief, meaning, and the philosophical structures through which life is understood, bringing a quality of compulsive truth-seeking and the irreversible dismantling of beliefs that have served comfort rather than genuine understanding. What is left when the comfortable beliefs are gone tends to be more honestly and more durably one's own.`,

  Pluto_Capricorn: `Solar return Pluto in Capricorn intensifies the year's transformative energy through the domain of institutional authority, professional structure, and the conventional definitions of achievement and power, bringing a quality of deep and sometimes ruthless revision to the systems through which worldly life has been organised. What is built after the stripping away tends to be founded on more genuinely solid and more genuinely accountable ground.`,

  Pluto_Aquarius: `Solar return Pluto in Aquarius intensifies the year's transformative energy through the domain of collective life, social structure, and the systems through which human beings organise their shared existence, bringing a quality of profound and irreversible collective transformation to the background against which individual lives are lived. The future being built under this influence is being built from the root up.`,

  Pluto_Pisces: `Solar return Pluto in Pisces intensifies the year's transformative energy through the domain of the spiritual, the unconscious, and the most hidden and most boundless dimensions of human experience, bringing a quality of deep and sometimes dissolving encounter with what lies beyond the ordinary limits of the self. What is released from the hidden dimensions of the life under this influence tends to have been ready for release for far longer than it appears.`,

};
