// src/content/pluto_in_houses.ts
// Solar Return: Pluto in each of the 12 houses
// Sources: Mary Fortier Shea "Planets in Solar Returns" (3rd ed.) — primary;
// Liz Greene "The Outer Planets and Their Cycles"; Stephen Arroyo
// "Astrology, Karma & Transformation"; Jeff Green "Pluto: The Evolutionary Journey of the Soul"
// NOTE: Pluto's house position shows where the year's deepest transformation,
// power dynamics, compulsion, and irreversible change are concentrated.
// Pluto moves even more slowly than Neptune (~12-20 years per sign depending
// on orbital position), so its SR house shifts almost entirely through changes
// in SR location. Pluto does not merely change what it touches — it strips
// it down to the essential, removes what is no longer genuinely alive, and
// rebuilds from a deeper foundation. Its transits are rarely comfortable
// and rarely forgettable. What Pluto destroys was already dying;
// what it builds tends to last.

export const PLUTO_IN_HOUSES: Record<number, string> = {

  1: `Solar Return Pluto in the first house places the year's most intense transformative energy directly in your personal identity, self-presentation, and relationship with your own power. This is among the most personally intense placements in a solar return — the self is undergoing a process of fundamental revision that operates at a depth and with a force that cannot be managed, negotiated with, or comfortably scheduled. You may find yourself changed in ways you did not choose and cannot fully explain, driven by compulsions and imperatives that arise from somewhere deeper than conscious preference. The way you move through the world, present yourself to others, and understand who you are is being fundamentally revised. Others may find you more intense, more magnetic, or more formidable than usual — there is something in the quality of your presence that carries more weight. Power dynamics in your personal life are highlighted: who has power over you, where you have surrendered power you should have retained, and where you are exercising power in ways that are genuinely aligned with your deepest values are all live questions. The year may involve a significant encounter with mortality, either literally or through an experience that brings the reality of impermanence into sharp focus. What emerges from this year's process of self-revision is more genuinely and more powerfully yourself — stripped of pretensions and performances that were never truly yours.`,

  2: `Solar Return Pluto in the second house brings deep, irreversible transformation to your finances, material circumstances, and most fundamentally to your relationship with what you value and what gives you a sense of personal worth. Financial circumstances may undergo significant and sometimes dramatic change — losses, windfalls, restructurings, or the sudden revelation that what seemed financially secure was built on less solid ground than appeared. The material dimension of your life is being revised at a level deeper than ordinary financial fluctuation. More significantly, Pluto in the second asks the most fundamental question of this house: what do you actually value, and is your life genuinely organised around those values or around a substitute for them? The compulsive relationship with money, possessions, and material security — whatever form that compulsion takes — is brought into focus and subjected to a process of revision that may feel like loss before it feels like liberation. Your sense of self-worth is equally subject to Pluto's stripping process: the layers of value that have been borrowed from others' approval, from accumulated possessions, or from financial standing are removed, and what remains is more genuinely and more durably your own. What you discover you actually value at the end of this year tends to be less negotiable and more truly yours than what you began with.`,

  3: `Solar Return Pluto in the third house brings deep, transformative, and sometimes obsessive intensity to the domains of communication, intellectual life, the immediate environment, and relationships with siblings and neighbours. The mind is more penetrating than usual — you think more deeply, investigate more relentlessly, and are less satisfied with surface explanations or comfortable simplifications. Research and investigation of any kind benefit from Pluto's compulsive thoroughness; the year supports intellectual work that goes to the root of things rather than skimming productive surfaces. Writing takes on more power and more darkness — the capacity to name what is usually unsaid, to go where comfortable discourse does not, is heightened. Communication with others may carry a quality of intensity that is not always easy — words have more weight than usual, and conversations that seem ordinary can tip into territory that reveals hidden tensions or unspoken truths. Relationships with siblings or those in the immediate environment may be subject to power dynamics, hidden agendas, or significant and irreversible change. The local environment may change in ways that cannot be undone. At its best, Pluto in the third produces a year of genuine intellectual depth and communicative power — writing and thinking that bears the mark of someone who has gone all the way down and returned with something real.`,

  4: `Solar Return Pluto in the fourth house brings deep, irreversible transformation to the foundations of your life — your home, your family, your psychological roots, and the innermost structures of your sense of self and security. This is one of the most profoundly interior Pluto placements, and its work proceeds primarily in the hidden dimensions of your life rather than in the visible external world. The home may be subject to significant and sometimes dramatic change — a move that ends a chapter, the loss or transformation of the family structure, or the revelation of what has been hidden within the family system. Family dynamics may involve power struggles, the surfacing of long-buried secrets, or a confrontation with inherited patterns that have been operating below conscious awareness. The psychological foundations are the deepest focus of Pluto's work in the fourth — old structures of inner security, inherited beliefs about who you are and what you deserve, and the deepest psychological roots of your sense of self are being revised at a level that ordinary introspection rarely reaches. Therapy and serious psychological work are strongly supported and may produce more genuinely transformative results than in other years. What Pluto builds in the fourth house — after the stripping away of what was false or dead — is a more genuine, more deeply rooted, and more truly indestructible sense of inner foundation.`,

  5: `Solar Return Pluto in the fifth house brings intense, transformative, and sometimes obsessive energy to the domains of creativity, romance, self-expression, and the life force itself. Creative work is driven by a compulsive quality — the need to make something that is genuinely true, genuinely powerful, and genuinely yours rather than merely accomplished or admirable. The creative output of a Pluto in the fifth year often carries an intensity and darkness that is different in kind from what comes more easily — it bears the mark of genuine encounter with the depths. Romantic life is subject to Pluto's characteristic intensity: attractions are more consuming, relationships more power-charged, and the line between genuine intimacy and compulsive attachment is more difficult to hold clearly. New relationships formed under this influence are rarely casual — they tend to be transformative, for better or worse, and leave both people genuinely changed. Existing relationships may be subject to power struggles or a confrontation with what has been unacknowledged in the dynamic between you. If you have children, their development or behaviour may raise significant and sometimes difficult questions. The life force itself — the capacity for genuine self-expression and genuine joy — is being revised at its root, and what emerges is more powerfully and more authentically your own creative and vital energy.`,

  6: `Solar Return Pluto in the sixth house brings deep, compulsive, and ultimately transformative intensity to the domains of work, health, and daily routine. The working life may be subject to significant power dynamics — struggles for control, the revelation of hidden agendas in the workplace, or the confrontation with working conditions or professional relationships that are genuinely unhealthy and require fundamental revision rather than accommodation. Work may become obsessive — driven by a compulsive need to master, control, or transform that exceeds what ordinary professional motivation explains. The working environment may undergo significant and irreversible change. Health is the most serious dimension of Pluto in the sixth — chronic issues that have been managed rather than genuinely addressed may surface with an urgency that demands real attention, and the year strongly supports medical investigation that goes beneath the surface of symptoms to their actual causes. Lifestyle practices and daily routines that have been maintained through habit rather than genuine health may be forcibly revised. At its best, Pluto in the sixth is a year of fundamental revision of the relationship between your daily life and your deepest vitality — work and routine stripped of what is merely habitual and rebuilt around what is genuinely life-sustaining.`,

  7: `Solar Return Pluto in the seventh house brings the year's most intense transformative energy to your closest relationships — the partnerships, collaborations, and one-to-one connections through which you are most deeply known and most genuinely challenged. Existing relationships may undergo significant and irreversible transformation — either deepening into something more genuinely authentic through a confrontation with what has not been honestly acknowledged, or ending because the confrontation reveals that what was being sustained was not genuinely alive. Power dynamics in close relationships are highlighted with unusual clarity: where power is shared equitably, where it has been surrendered in ways that are self-defeating, and where it is being exercised in ways that are harmful are all brought into focus by Pluto's unsparing gaze. New relationships formed under Pluto in the seventh carry a quality of intensity and inevitability — the sense of being drawn toward someone by something deeper than ordinary attraction. Professional partnerships and collaborations may be subject to power struggles or significant restructuring. Legal matters may be intense and consequential. At its best, Pluto in the seventh produces a year in which your most important relationships are tested at the depth required to reveal whether they are built on something genuinely real — and in which what survives that testing is more durably and more honestly intimate than what existed before.`,

  8: `Solar Return Pluto in the eighth house is Pluto in its natural domicile — the eighth house is associated with Scorpio, the sign Pluto rules — and the result is a year of the most concentrated and most powerful Plutonian energy, operating in the domain where it is most at home. Transformation is not merely possible this year; it is, in some form, inevitable. The eighth house governs shared resources, deep intimacy, power, death and rebirth, the hidden dimensions of life, and the boundary between what is visible and what is not. With Pluto here, all of these domains are charged with an intensity and a sense of irreversibility that makes this one of the most significant solar return placements possible. Financial matters involving others — joint finances, inheritance, debt, insurance — may be subject to dramatic change. Power struggles over shared resources are possible. Psychologically, the unconscious is at its most active and most demanding — what has been repressed, denied, or hidden comes forward with a force that is difficult to resist and ultimately unproductive to resist. The deepest shadow material becomes available for genuine integration. The encounter with mortality — one's own or another's — may be part of the year's texture. Sexual and intimate life may be intensely alive, intensely transformative, or intensely complicated. What Pluto builds in its own house, after the stripping away of everything that was false, is a more genuinely powerful, more genuinely authentic, and more genuinely alive engagement with the deepest dimensions of existence.`,

  9: `Solar Return Pluto in the ninth house brings deep, compulsive, and ultimately transformative intensity to the domains of belief, philosophy, higher education, long-distance travel, and the broad meaning-making structures through which you understand your life. The philosophical and spiritual life is not merely expanded this year — it is subjected to Pluto's stripping process, which removes what has been believed for comfort or convention rather than from genuine conviction. Belief systems that have been held without honest examination are brought under a pressure that tests whether they are actually true or merely consoling. What survives that pressure tends to be held with a depth and a commitment that more comfortable years do not produce. What does not survive needed to go. Higher education may be pursued with a compulsive intensity and may involve subject matter that deals with power, transformation, death, or the hidden dimensions of human experience. Long-distance travel, if it occurs, tends to be genuinely transformative rather than merely broadening. Legal matters may be significant and consequential. The confrontation with ideologies — both your own and others' — is a central theme, and the year may involve an encounter with the ways in which belief systems can be used to exercise power over others or to avoid the more difficult work of genuine transformation. At its best, Pluto in the ninth produces a worldview that has been genuinely tested and is genuinely, irreversibly one's own.`,

  10: `Solar Return Pluto in the tenth house brings the year's most intense transformative energy to your career, public reputation, and relationship with authority and worldly power. The professional life may undergo significant and irreversible change — the loss of a position, a dramatic shift in career direction, the revelation of hidden dimensions of your professional environment, or a confrontation with the power structures of your industry or institution. Power dynamics in the professional sphere are highlighted: who has power over your professional life, how that power is exercised, and whether your own exercise of professional authority is genuinely aligned with your deepest values are all live questions. The public reputation may be subject to Pluto's stripping process — what has been maintained through image management or performance rather than genuine substance is at greater risk than what is built on authentic foundation. Encounters with powerful authority figures may be significant and consequential. Ambition takes on a more compulsive quality — the drive to achieve, to transform the professional sphere, or to exercise genuine power in the world is stronger and less negotiable than in other years. At its best, Pluto in the tenth is a year in which your professional life is restructured at the root level — stripped of what was merely career rather than genuine vocation — and rebuilt around what is most deeply and most powerfully yours to offer the world.`,

  11: `Solar Return Pluto in the eleventh house brings deep, transformative, and sometimes power-charged intensity to your social world, friendships, group involvements, and long-range aspirations. The social sphere may undergo significant and irreversible change — friendships that seemed permanent may end, power dynamics within your social and professional network may be revealed with uncomfortable clarity, or your involvement with groups and collective projects may be subject to struggles over control, direction, or genuine values. The question of who your people actually are — as distinct from those who have been in your life through habit, proximity, or mutual convenience — is brought into sharp focus. Group involvements may involve encounters with the shadow dimensions of collective behaviour: the way groups exercise power, exclude, and coerce, even in ostensibly aligned communities. Long-range aspirations are subjected to Pluto's stripping process — the goals and visions that have been pursued for reasons of ambition, approval, or convention are revealed as such, and what remains after that revelation is more genuinely and more powerfully yours. The future you build from Pluto's work in the eleventh is built on a more honest and more deeply motivated foundation. At its best, this is a year of fundamental revision of your relationship with collective life — a clearer, more honest, and more genuinely committed engagement with the people and causes that are most truly aligned with who you are.`,

  12: `Solar Return Pluto in the twelfth house brings the year's most intense transformative energy to the hidden, invisible, and most deeply interior dimensions of your life. This is the most inward of all Pluto placements — its work proceeds almost entirely below the threshold of what is visible from the outside, and the transformation it produces may not become apparent to others, or even fully to yourself, until the year has ended and its work is complete. The unconscious is at its most active and most relentless — what has been suppressed, denied, or hidden for years surfaces with a force and persistence that is difficult to manage and ultimately impossible to permanently evade. Old wounds, inherited patterns, and the deepest shadow material come forward, not with Pluto's eighth house directness, but with the more subtle and more pervasive quality of the twelfth. Dreams may be intense and revelatory. A quality of psychic sensitivity or of being genuinely in contact with dimensions of experience that ordinary waking life excludes may be part of the year's texture. Hidden enemies or undermining forces — internal as much as external — may require honest attention. Institutions, hidden constraints, and the structures of what has been inescapable may begin to lose their hold. At its best, Pluto in the twelfth produces a year of the most profound and most lasting interior transformation — the kind that does not announce itself but that quietly and irrevocably removes what was never truly yours and makes space for what is.`,
};
