// src/content/saturn_in_houses.ts
// Solar Return: Saturn in each of the 12 houses
// Sources: Mary Fortier Shea "Planets in Solar Returns" (3rd ed.) — primary;
// Cafe Astrology Solar Return series; Robert Hand "Planets in Transit";
// Liz Greene "Saturn: A New Look at an Old Devil"
// NOTE: Saturn's house position shows where discipline, limitation, responsibility,
// and the demands of reality are concentrated for the year. It is not a malefic
// placement — it is a placement of necessary work. Saturn shows where the year's
// most important lessons live, and where the greatest long-term rewards are
// available to those willing to engage honestly with what is being asked of them.
// Saturn moves slowly (~2.5 years per sign), so its house shifts year to year
// primarily through changes in SR location rather than sign ingress.

export const SATURN_IN_HOUSES: Record<number, string> = {

  1: `Solar Return Saturn in the first house places the themes of discipline, responsibility, and sober self-assessment at the very centre of your personal identity and self-expression for the year. You are more serious than usual — more aware of your limitations, more conscious of where you fall short of your own standards, and more inclined to approach life with caution and deliberate effort rather than spontaneous confidence. This is not a comfortable placement, but it is a productive one for those willing to engage with it honestly. Saturn in the first house asks you to take yourself seriously in the most fundamental sense: to build your life on what is genuinely solid rather than what merely feels good, and to do the work of becoming more authentically yourself rather than performing a version of yourself that others will find appealing. Physical vitality may be lower than usual, or health matters may require attention and discipline. The year can feel heavy, particularly in the first half, but what you build under this influence tends to have real substance. Relationships may feel more demanding or more restricted than usual. At its best, Saturn in the first house produces a year of genuine maturation — a clearer, more honest, more capable version of yourself emerges from the discipline the year requires.`,

  2: `Solar Return Saturn in the second house focuses the year's themes of discipline, limitation, and necessary work on your finances, your material circumstances, and your sense of personal value. Money tends to feel tighter than usual — not necessarily through catastrophic loss, but through a general constriction that requires more careful management, more realistic budgeting, and more honest assessment of what is financially sustainable. Income may be lower, expenses higher, or financial responsibilities more demanding. The year asks you to build a genuinely solid material foundation rather than one based on optimistic assumptions about future income or the generosity of others. This is an excellent year for addressing financial structures that have been avoiding attention — debt management, realistic long-term financial planning, or the honest assessment of whether your income is genuinely sustainable. Your sense of self-worth is also under Saturn's discipline: the year asks you to base your value on what you have genuinely built and genuinely earned rather than on borrowed confidence or external validation. The financial constriction of this year, when engaged with honestly, tends to produce more genuinely stable material circumstances in the years that follow.`,

  3: `Solar Return Saturn in the third house brings discipline, restriction, and serious demands to the domains of communication, intellectual work, and your immediate environment for the year. Writing becomes more demanding — the standard you hold yourself to is higher, progress feels slower, and the critical faculty is more active than the generative one. This is not a year in which words flow effortlessly, but it is a year in which words, when they do come, have more weight and more precision. If you are working on a significant writing project, Saturn in the third can produce genuine quality through the very demand for discipline and rigour it imposes. Formal study is well-supported — Saturn rewards sustained, structured learning with real mastery. Relationships with siblings and neighbours may be more demanding or more distant. Short trips may be delayed or subject to practical complications. The mental environment can feel heavier and more critical than usual, and negative thinking patterns may require conscious attention. The mind works better in this year when given clear structure and realistic goals rather than open-ended creative freedom. What is learned and written under Saturn's discipline in the third tends to be genuinely solid and lasting.`,

  4: `Solar Return Saturn in the fourth house brings the year's most serious demands to bear on your home, family, and psychological foundations. Domestic circumstances may require significant practical attention — property matters, structural repairs, family responsibilities, or the demands of a parent or elder relative may absorb considerable time and energy. Home life feels more demanding and less effortlessly comfortable than in other years. Family relationships carry a quality of obligation and sometimes burden — old family patterns, unresolved dynamics, or the weight of family history may surface and require honest engagement. The inner life is equally subject to Saturn's demands: the fourth house rules the deepest psychological foundations, and Saturn here asks for an honest reckoning with what those foundations are actually made of. Therapy, honest self-examination, and any process that builds genuine psychological substance rather than comfortable illusion are well-supported and productive. The year can feel emotionally heavy, particularly around home and family. What is built in the interior dimensions of your life under this influence — genuine emotional maturity, more honest self-knowledge, more solid psychological foundations — tends to be lasting and real.`,

  5: `Solar Return Saturn in the fifth house brings discipline, restriction, and serious demands to the domains of creativity, romance, pleasure, and self-expression. Creative work requires more effort than usual — the year asks for discipline and sustained commitment rather than effortless inspiration. This is not a year in which creativity flows freely, but it is a year in which genuine craft can be developed and meaningful creative work can be brought to completion through sustained application. Romance may feel more constrained or more serious — new relationships formed under this influence tend to be more deliberate and more genuinely considered than those formed under lighter planetary influences, and existing relationships may feel the weight of unresolved practical matters. If you have children, their demands and responsibilities may be more significant this year. The pleasure of leisure feels harder to access — there may be a quality of guilt or inadequacy around simply enjoying yourself without productive justification. At its best, Saturn in the fifth produces a year of genuine creative development — work of real substance rather than charming but shallow output — and relationships that are chosen with genuine seriousness rather than romantic impulse.`,

  6: `Solar Return Saturn in the sixth house is one of the most demanding but also most genuinely productive Saturn placements. The sixth house governs work, health, and daily routine — all domains in which Saturn's demand for discipline, structure, and honest assessment can produce real and lasting results. The year asks for more work, more sustained effort, and a more rigorous approach to the daily structure of your professional life. Job demands may increase significantly, or the standards you hold yourself to may become more exacting. This is an excellent year for developing genuine professional mastery through sustained effort, for taking on work that requires the kind of serious long-term commitment that Saturn rewards. Health also requires serious and honest attention — chronic issues should not be ignored, and the year supports the establishment of genuinely sustainable health practices rather than optimistic but short-lived commitments. The physical body may feel more fragile or more demanding of care than in other years. Daily routine feels heavier and more obligatory. What is built in the domains of professional discipline and genuine physical care under Saturn in the sixth tends to be among the most durable and genuinely earned achievements of a person's working life.`,

  7: `Solar Return Saturn in the seventh house brings the year's most serious demands to your closest relationships — both personal partnerships and significant professional collaborations. Existing relationships are tested by a quality of weight and obligation that feels different from the warm generosity of other years — practical matters, unresolved tensions, and the honest question of whether the relationship is built on genuinely solid foundations are all brought into focus. Relationships that are genuinely solid tend to deepen and mature under this influence; those built on less honest foundations may not survive Saturn's scrutiny. New relationships formed under Saturn in the seventh tend to be serious, deliberate, and sometimes marked by age difference, significant practical considerations, or a quality of karmic weight. These relationships, precisely because they are not formed in the glow of uncritical enthusiasm, can be among the most genuinely lasting. Legal matters require careful and serious attention. Professional partnerships and collaborations are subject to the same quality of honest assessment — you are asked to be genuinely accountable to those you work closely with, and to hold them to the same standard. The year tends to reveal what your most important relationships are actually made of.`,

  8: `Solar Return Saturn in the eighth house brings discipline, restriction, and serious demands to the domains of shared resources, transformation, intimacy, and the hidden dimensions of life. Financial matters involving other people — joint finances with a partner, inheritance, debt, insurance, or investment — require careful and serious attention. Financial obligations and restructuring may be significant. Debt management, the careful handling of other people's resources, and the honest assessment of financial arrangements that have not been clearly defined are all appropriate focuses for the year. Deep psychological and transformational work is both more demanding and more genuinely productive under Saturn's influence in the eighth — this is a year in which shadow material surfaces not in the free-flowing way of Neptune or the explosive way of Pluto, but in the slower, more structural way that Saturn governs. What needs to be released, restructured, or genuinely transformed is presented with a quality of inevitability and realistic demand. Intimacy requires more genuine honesty and accountability than is comfortable. Research and investigation produce real results through sustained effort. At its best, Saturn in the eighth produces a year of profound and lasting psychological restructuring.`,

  9: `Solar Return Saturn in the ninth house brings discipline, restriction, and serious demands to the domains of higher education, long-distance travel, publishing, philosophy, and the broad horizons of belief and meaning. Advanced study requires more sustained effort and encounters more genuine obstacles — but the mastery produced by working through those obstacles under Saturn's influence tends to be more genuinely solid than what comes more easily in other years. Publishing and significant writing projects require patience, persistence, and a willingness to work through setbacks without abandoning the work. Long-distance travel may be delayed, curtailed, or subject to practical complications. More significantly, the philosophical and belief structures through which you have understood your life are subjected to Saturn's honest scrutiny — comfortable assumptions about meaning, about the way the world works, or about the sources of authority in your life may come under pressure. This is not always comfortable, but it tends to produce a more genuinely examined and more honestly held worldview. Legal matters require careful attention and realistic expectations. At its best, Saturn in the ninth is a year of genuine intellectual and spiritual maturation — beliefs tested and either strengthened or revised through honest engagement with what is actually true.`,

  10: `Solar Return Saturn in the tenth house is one of the most significant placements in a solar return — Saturn in its own natural house (the tenth is associated with Capricorn, Saturn's domicile) brings the full weight of the planet's demands for discipline, accountability, and genuine achievement to bear on your career, public reputation, and worldly standing. The year may bring increased professional responsibility, significant career challenges, or a public reckoning with the quality and substance of what you have built professionally. Authority figures — bosses, institutions, the public — hold you to a higher standard, and the year tends to reveal quite starkly whether your professional standing is built on genuine substance or on reputation that exceeds the underlying reality. If your work is genuinely solid, Saturn in the tenth can bring significant recognition and advancement — not the warm enthusiasm of Jupiter, but the sober respect that comes from demonstrated competence and sustained effort. If there are gaps between reputation and substance, the year tends to surface them. This is an excellent year for taking professional ambitions seriously, for doing the hardest work you are capable of, and for building the kind of career foundation that will sustain long-term recognition.`,

  11: `Solar Return Saturn in the eleventh house brings discipline, restriction, and honest demands to your social world, friendships, group involvements, and long-range aspirations. The social sphere feels more contracted than usual — fewer connections, more demanding friendships, or a quality of isolation within your broader network that prompts honest reassessment of which relationships are genuinely sustaining and which are merely habitual. Groups and organisations to which you belong may make more demands, or the quality of belonging may feel more obligatory than freely chosen. Long-range goals and aspirations — those things you have been working toward over years rather than months — are subjected to Saturn's honest scrutiny: which goals are genuinely worth the sustained effort they require, and which have been comfortable ambitions that substitute for the harder work of genuine commitment? The year asks you to be more selective and more genuinely accountable in your social and collective involvements. Friendships that survive Saturn in the eleventh tend to be genuinely solid. Goals that are refined under this influence tend to be more honestly aligned with what you are actually willing to do. The social contraction of this year often precedes a more genuinely chosen and more authentic expansion in the years that follow.`,

  12: `Solar Return Saturn in the twelfth house is one of the most challenging Saturn placements — the twelfth house is Saturn's traditional domicile of greatest difficulty, and the combination of Saturn's demands with the twelfth house's themes of hidden matters, self-undoing, isolation, and the unconscious can produce a year of considerable inner pressure. Responsibilities and obligations that feel onerous but that cannot easily be shed, a quality of isolation or restriction that is difficult to articulate or resolve, and a general heaviness in the hidden dimensions of your life characterise this placement at its most difficult. Karmic patterns, old psychological structures, and the weight of what has not been properly resolved in earlier years tend to surface with a quality of unavoidable urgency. This is an excellent year for therapy, for serious inner work, for honest engagement with what you have been avoiding. Spiritual practice and solitary reflection produce genuine and lasting results. The year often involves a significant ending — the conclusion of a long chapter — that clears the ground for something genuinely new to begin. At its best, Saturn in the twelfth is a year of profound inner restructuring: uncomfortable, demanding, and ultimately productive of a more genuinely solid and more honestly examined inner life.`,
};
