// src/content/sr_natal_contacts.ts
// Solar Return: SR planet conjunct natal planet contacts
// Key format: "sr_planet_conjunct_natal_planet" — all lowercase
// e.g. "sr_sun_conjunct_natal_moon", "sr_saturn_conjunct_natal_venus"
// Coverage: all 10 SR planets conjunct all 10 natal planets = 100 entries
// Sources: Mary Fortier Shea "Planets in Solar Returns" (3rd ed.) — primary;
// Robert Hand "Planets in Transit"; Liz Greene outer planet texts
// NOTE: These contacts describe the year's SR planet activating the natal
// planet's principle — the SR planet is the activating energy, the natal
// planet is the domain of life being activated. Conjunction only (0°, orb ~3°).
// Entries: 3-4 sentences

export const SR_NATAL_CONTACTS: Record<string, string> = {

  // SR SUN CONJUNCT NATAL PLANETS
  sr_sun_conjunct_natal_sun: `The solar return Sun conjunct the natal Sun — which occurs only when the SR is cast for the birth location — places the year's full identity focus on the most central and most personally essential dimension of who you are. The year tends to bring a quality of genuine self-clarification: what you are most essentially, stripped of the accommodations and compromises that other years accumulate, is more fully available and more urgently calling for expression. Personal initiatives undertaken in pure alignment with your most genuine values and most essential character are strongly supported. The year is most productive when you resist the dilution of genuine self-expression in favour of what is merely expected or merely convenient.`,

  sr_sun_conjunct_natal_moon: `The solar return Sun conjunct the natal Moon activates the deepest emotional foundations and instinctive responses of the natal chart with the year's full identity and conscious direction. The year brings emotional life into the foreground of conscious awareness in ways that more defended years do not permit — what has been felt but not fully acknowledged surfaces with a quality of genuine urgency and genuine productive significance. Home, family, and the domains of genuine inner security are highlighted, and the year tends to bring personal and emotional themes directly into the centre of what is being worked on and worked toward. Emotional honesty is both more available and more genuinely demanded.`,

  sr_sun_conjunct_natal_mercury: `The solar return Sun conjunct the natal Mercury activates the natal chart's communicative intelligence and mental approach with the year's full identity and conscious direction. Intellectual and communicative work are more personally invested and more genuinely central to the year's experience than in years when the Sun falls elsewhere, and the quality of thinking and self-expression tends to be both more alive and more personally significant. Writing, teaching, and the articulation of personal ideas are particularly well-supported, and the year tends to bring intellectual development into the foreground of what is most essentially being worked on. Mental clarity and genuine self-expression through language are among the year's primary vehicles of personal development.`,

  sr_sun_conjunct_natal_venus: `The solar return Sun conjunct the natal Venus activates the natal chart's aesthetic sensibility, relational warmth, and capacity for genuine pleasure and connection with the year's full identity and conscious direction. Relationships, creative work, and the domains of beauty and genuine enjoyment are more personally central than in other years, and the year tends to bring both the rewards and the genuine demands of Venus's domain into the foreground of conscious attention. New relationships or the significant deepening of existing ones are well-supported, and creative and aesthetic projects benefit from the personal investment that the Sun's contact with natal Venus consistently produces. The year asks that genuine personal values — in love and in beauty — be lived rather than merely held.`,

  sr_sun_conjunct_natal_mars: `The solar return Sun conjunct the natal Mars activates the natal chart's drive, assertiveness, and physical vitality with the year's full identity and conscious direction. Personal initiative is stronger and more genuinely central to the year's experience than in other years — the will to pursue what is wanted with directness and force is more fully available, and the year tends to reward decisive action with genuine results. Physical energy is heightened, competitive situations tend to favour genuine engagement over diplomatic management, and the year asks that the personal drive indicated by natal Mars be directed toward goals that are genuinely worth the energy they require. The risk is impulsiveness and the tendency to assert more forcefully than the situation genuinely warrants.`,

  sr_sun_conjunct_natal_jupiter: `The solar return Sun conjunct the natal Jupiter activates the natal chart's principle of expansion, philosophical confidence, and genuine good fortune with the year's full identity and conscious direction. The year tends to bring a quality of genuine personal expansiveness and the sense of enlarged possibility — the natal Jupiter's house and sign describe the domain in which this expansion is most naturally expressed, and the year supports the active pursuit of what natal Jupiter has always promised with more confidence and more genuine personal investment than other years provide. Opportunity, philosophical development, and the willingness to reach beyond what is already established are all strongly supported. The year is most productive when genuine expansion is matched by honest assessment of what is actually being taken on.`,

  sr_sun_conjunct_natal_saturn: `The solar return Sun conjunct the natal Saturn activates the natal chart's principle of discipline, limitation, and the demanding work of genuine self-construction with the year's full identity and conscious direction. The year tends to bring a quality of serious personal reckoning — the natal Saturn's house and sign describe the domain in which the year's most demanding questions of genuine accountability and honest self-assessment are concentrated. Physical vitality may be lower than in other years, and the year can feel heavier and more demanding than the optimistic years that flank it. What is built through this year's honest engagement with natal Saturn's demands tends to be among the most genuinely solid and most lastingly real personal achievements of the decade.`,

  sr_sun_conjunct_natal_uranus: `The solar return Sun conjunct the natal Uranus activates the natal chart's principle of liberation, originality, and the disruptive impulse toward authentic self-expression with the year's full identity and conscious direction. The year tends to bring a quality of genuine personal awakening — the natal Uranus's house and sign describe the domain in which the year's most urgent demand for authenticity and liberation is focused, and what has been constrained or maintained through habit in that domain may suddenly become genuinely intolerable. The impulse toward personal reinvention is strong and not easily managed through ordinary self-discipline. What follows the disruption this year initiates tends to be more genuinely and more freely chosen than what preceded it.`,

  sr_sun_conjunct_natal_neptune: `The solar return Sun conjunct the natal Neptune activates the natal chart's principle of spiritual sensitivity, creative imagination, and the dissolving of ordinary ego boundaries with the year's full identity and conscious direction. The year tends to bring a quality of heightened personal sensitivity and creative inspiration — the natal Neptune's house and sign describe the domain in which the year's most genuinely inspired and most genuinely evasive tendencies are concentrated. Artistic work, spiritual practice, and compassionate engagement with others are powerfully supported. The risk is the dissolution of personal clarity and direction in the beautiful but evasive territory that Neptune always inhabits — the year benefits from both genuine openness and enough grounded structure to give inspiration somewhere real to go.`,

  sr_sun_conjunct_natal_pluto: `The solar return Sun conjunct the natal Pluto activates the natal chart's principle of transformation, depth, and the compulsive encounter with what is most essentially true with the year's full identity and conscious direction. The year tends to bring a quality of genuine personal transformation — the natal Pluto's house and sign describe the domain in which the year's most fundamental and most irreversible process of stripping and rebuilding is concentrated. Power dynamics, the honest question of where genuine personal power lies, and the demand for authentic engagement with what has been most carefully avoided are all brought into the full light of the year's conscious attention. What emerges from this year's encounter with natal Pluto tends to be more genuinely and more powerfully the self.`,

  // SR MOON CONJUNCT NATAL PLANETS
  sr_moon_conjunct_natal_sun: `The solar return Moon conjunct the natal Sun activates the most central principle of the natal chart — the essential self, the will, the core identity — with the year's emotional instincts and deepest feeling responses. The year tends to bring personal and creative life into genuinely emotional focus — what you are most essentially is experienced and expressed through feeling rather than through deliberate conscious direction. The emotional life is more personally central and more genuinely alive than in more defended years, and the year tends to bring the private inner life into productive contact with what is most publicly and most essentially yourself. Genuine emotional honesty about who you are and what you want is both more available and more genuinely demanded.`,

  sr_moon_conjunct_natal_moon: `The solar return Moon conjunct the natal Moon — which recurs approximately every 18-19 years — marks a year of exceptional emotional depth, instinctive self-knowledge, and genuine access to the deepest foundations of the emotional life. The natal Moon's house and sign describe the domain in which this emotional depth is most fully expressed, and the year tends to bring a quality of genuine emotional homecoming — a return to what is most instinctively true about how you feel, what you need, and where genuine security actually lives. Family and domestic themes are highlighted, and the year supports deep inner work with a quality of natural emotional authority and genuine intuitive reliability.`,

  sr_moon_conjunct_natal_mercury: `The solar return Moon conjunct the natal Mercury activates the natal chart's communicative and intellectual principle with the year's full emotional depth and instinctive sensitivity. Thinking and feeling are more thoroughly intertwined than in other years — ideas arrive with emotional weight, and emotional experience is more readily available for articulation through language and communication. Writing that draws on genuine personal feeling, journaling, and any communicative work that benefits from the honest expression of inner experience are particularly well-supported. The year tends to bring the intellectual and emotional dimensions of experience into productive and sometimes revelatory contact.`,

  sr_moon_conjunct_natal_venus: `The solar return Moon conjunct the natal Venus activates the natal chart's relational warmth, aesthetic sensibility, and capacity for genuine pleasure with the year's full emotional depth and instinctive feeling responses. The year tends to bring a quality of exceptional personal warmth and emotional availability in relationships — what natal Venus has always described in terms of the capacity for love and genuine connection is experienced this year with more genuine emotional depth and more instinctive personal investment. Creative and aesthetic work benefits from the emotional richness this contact provides. The year is well-suited to the deepening of significant relationships and to creative projects that require genuine emotional investment alongside aesthetic sensibility.`,

  sr_moon_conjunct_natal_mars: `The solar return Moon conjunct the natal Mars activates the natal chart's drive, assertiveness, and physical vitality with the year's emotional instincts and deepest feeling responses. The year tends to bring a quality of emotionally driven action — what is felt is acted on with more immediacy and more personal force than in years when the emotional and active principles operate at greater distance. Emotional reactivity is heightened, and the line between genuine passionate engagement and impulsive emotional assertion is more difficult to maintain. The year is most productive when the considerable energy this contact generates is directed toward goals that are genuinely worth the emotional investment they are receiving.`,

  sr_moon_conjunct_natal_jupiter: `The solar return Moon conjunct the natal Jupiter activates the natal chart's principle of expansion, philosophical confidence, and genuine good fortune with the year's emotional depth and instinctive warmth. The year tends to bring a quality of emotional generosity and genuine inner abundance — the natal Jupiter's domain is experienced with more warmth, more instinctive confidence, and more genuine emotional investment than in other years. Family relationships and domestic circumstances tend to benefit from this contact's quality of natural goodwill and expansive warmth. The year supports the emotional willingness to reach beyond what is already established with genuine confidence and genuine inner backing.`,

  sr_moon_conjunct_natal_saturn: `The solar return Moon conjunct the natal Saturn activates the natal chart's principle of discipline, limitation, and the demanding work of genuine self-construction with the year's full emotional depth and instinctive feeling responses. The year tends to bring emotional life into the territory that natal Saturn governs — the domain of genuine responsibility, honest limitation, and the demanding question of what is actually sustainable. Emotional needs may feel more constrained and less easily met than in other years, and family and domestic responsibilities may weigh more heavily. What is worked out emotionally under this contact tends to be more genuinely solid and more honestly owned than what comes more easily in warmer years.`,

  sr_moon_conjunct_natal_uranus: `The solar return Moon conjunct the natal Uranus activates the natal chart's principle of liberation, originality, and disruptive authentic change with the year's full emotional depth and instinctive feeling responses. The year tends to bring a quality of sudden emotional awakening — the domain that natal Uranus governs is experienced with more emotional urgency and more instinctive demand for genuine freedom and authentic expression than in other years. Domestic and emotional life may be subject to unexpected disruptions, and the need for genuine freedom within the emotional life and the closest relationships is at its most urgent and least negotiable. What is disrupted tends to be what was maintained through habit rather than genuine choice.`,

  sr_moon_conjunct_natal_neptune: `The solar return Moon conjunct the natal Neptune activates the natal chart's principle of spiritual sensitivity, creative imagination, and boundary dissolution with the year's full emotional depth and instinctive feeling responses. The year tends to bring a quality of exceptional emotional permeability — the domain that natal Neptune governs is experienced with the full force of the emotional life's most sensitive and most compassionate capacities. Creative work, spiritual practice, and compassionate service are powerfully supported. The risk is the loss of emotional clarity and personal boundary in the beautiful but demanding territory of Neptune's dissolving influence — the year benefits from both genuine openness and deliberate attention to the maintenance of enough inner structure to remain genuinely present.`,

  sr_moon_conjunct_natal_pluto: `The solar return Moon conjunct the natal Pluto activates the natal chart's principle of transformation, depth, and the compulsive encounter with what is most essentially true with the year's full emotional depth and instinctive feeling responses. The year tends to bring a quality of emotionally intense and sometimes overwhelming psychological depth — the domain that natal Pluto governs is experienced with the full force of the emotional life's most powerful and most honest capacities. What has been most carefully repressed or avoided in the emotional life tends to surface with a quality of genuine urgency. Deep psychological work and the honest engagement with the most demanding emotional material are both strongly supported and genuinely demanded.`,

  // SR MERCURY CONJUNCT NATAL PLANETS
  sr_mercury_conjunct_natal_sun: `The solar return Mercury conjunct the natal Sun activates the most central principle of the natal chart with the year's communicative intelligence and analytical attention. The year tends to bring the central identity themes of the natal Sun into sharp intellectual focus — what you are most essentially is thought about, written about, and articulated with more genuine personal investment and more analytical clarity than in other years. Intellectual projects with genuine personal significance are strongly supported, and the year rewards the honest communication of what is most centrally and most essentially yours.`,

  sr_mercury_conjunct_natal_moon: `The solar return Mercury conjunct the natal Moon activates the natal chart's deepest emotional foundations with the year's communicative intelligence and analytical attention. The year tends to bring emotional life into intellectual focus — feelings that have been experienced but not fully understood or articulated become more available for genuine reflection and honest communication. Journaling, therapy, and any communicative process that supports the honest articulation of inner experience are particularly well-supported. The year is well-suited to writing or intellectual work that draws on genuine emotional depth and personal memory.`,

  sr_mercury_conjunct_natal_mercury: `The solar return Mercury conjunct the natal Mercury activates the natal chart's communicative and intellectual principle with its own most direct and most natural energy. The year tends to bring a quality of exceptional intellectual focus and communicative clarity — the natal Mercury's house and sign describe the domain in which this mental energy is most naturally and most productively expressed, and the year supports intellectual and communicative work in that domain with a quality of natural effectiveness and genuine personal investment. Writing, research, and the articulation of ideas that have been developing over previous years are particularly well-supported.`,

  sr_mercury_conjunct_natal_venus: `The solar return Mercury conjunct the natal Venus activates the natal chart's relational warmth and aesthetic sensibility with the year's communicative intelligence and analytical attention. The year tends to bring relational and aesthetic themes into sharper intellectual focus — the ability to articulate what you find beautiful, what you value in relationships, and what you want from your most significant connections is more fully available and more genuinely productive than in other years. Creative writing, aesthetic criticism, and any communicative work that benefits from both analytical precision and genuine aesthetic sensibility are particularly well-supported.`,

  sr_mercury_conjunct_natal_mars: `The solar return Mercury conjunct the natal Mars activates the natal chart's drive and assertiveness with the year's communicative intelligence and analytical energy. The year tends to bring a quality of sharp, assertive intellectual engagement — debates, negotiations, and the forceful communication of what you actually think are more central and more genuinely alive than in other years. Writing and speaking carry more edge and more genuine conviction, and the impulse to defend a position or challenge an opposing one is more readily available. The year is most productive when this intellectual force is directed toward genuinely worthwhile arguments and genuinely important communications.`,

  sr_mercury_conjunct_natal_jupiter: `The solar return Mercury conjunct the natal Jupiter activates the natal chart's principle of expansion and philosophical confidence with the year's communicative intelligence and analytical attention. The year tends to bring a quality of genuine intellectual expansiveness — the natal Jupiter's domain is engaged with more broad-ranging curiosity, more philosophical ambition, and more genuine communicative confidence than in other years. Writing and publishing projects with genuine intellectual scope are well-supported, and the year rewards the willingness to think and communicate on a genuinely significant scale in the domain that natal Jupiter governs.`,

  sr_mercury_conjunct_natal_saturn: `The solar return Mercury conjunct the natal Saturn activates the natal chart's principle of discipline and demanding self-construction with the year's communicative intelligence and analytical attention. The year tends to bring intellectual and communicative work into the territory that natal Saturn governs with a quality of serious rigour and honest self-assessment. Writing and thinking proceed more slowly and with more genuine discipline, and the critical faculty is more active and more demanding than in other years. What is produced through this year's intellectual discipline tends to be more genuinely solid and more lastingly valuable than what comes more easily.`,

  sr_mercury_conjunct_natal_uranus: `The solar return Mercury conjunct the natal Uranus activates the natal chart's principle of liberation and original disruption with the year's communicative intelligence and analytical energy. The year tends to bring a quality of sudden intellectual breakthrough in the domain that natal Uranus governs — ideas arrive with an electric originality, and the impulse to think in genuinely new ways and to communicate what is genuinely unconventional is more urgently available than in other years. The year is well-suited to intellectual and communicative work that breaks new ground and that follows genuine insight wherever it leads without insisting on the destination in advance.`,

  sr_mercury_conjunct_natal_neptune: `The solar return Mercury conjunct the natal Neptune activates the natal chart's principle of spiritual sensitivity and creative imagination with the year's communicative intelligence and analytical attention. The year tends to bring intellectual and communicative work into the territory that natal Neptune governs with a quality of inspired creativity and genuine imaginative depth. Writing, poetry, and any communicative work that proceeds through image, metaphor, and emotional resonance rather than purely logical argument are particularly well-supported. The risk is the characteristic confusion of what is brilliantly imagined with what is actually, verifiably true.`,

  sr_mercury_conjunct_natal_pluto: `The solar return Mercury conjunct the natal Pluto activates the natal chart's principle of transformation and compulsive depth with the year's communicative intelligence and analytical energy. The year tends to bring intellectual and communicative work into the territory that natal Pluto governs with a quality of penetrating investigative thoroughness and genuine psychological depth. Research, psychological insight, and any intellectual work that requires going beneath the surface of things to what is actually operating are powerfully supported. Communications carry more weight and more genuine consequence than in other years, and what is said in the domain that natal Pluto governs tends to be said with a force and a finality that requires genuine care.`,

  // SR VENUS CONJUNCT NATAL PLANETS
  sr_venus_conjunct_natal_sun: `The solar return Venus conjunct the natal Sun activates the most central principle of the natal chart with the year's relational warmth, aesthetic sensibility, and capacity for genuine pleasure and connection. The year tends to bring a quality of genuine personal charm and creative vitality to the most essentially central dimension of who you are — identity is expressed through beauty, through warmth, and through the genuine capacity to attract and to connect. Romantic, creative, and social life are all more personally central and more genuinely rewarding than in other years. The year is well-suited to any personal initiative that benefits from genuine warmth and the capacity to make what you do genuinely appealing to others.`,

  sr_venus_conjunct_natal_moon: `The solar return Venus conjunct the natal Moon activates the natal chart's deepest emotional foundations with the year's relational warmth and aesthetic sensibility. The year tends to bring a quality of genuine emotional pleasure and warmth to the domains of home, family, and inner security — what natal Moon describes as the basis of genuine emotional belonging is experienced with more beauty, more comfort, and more genuine relational richness than in other years. Family relationships benefit from genuine warmth and goodwill, domestic circumstances tend to be more aesthetically pleasing and more emotionally comfortable, and the year is well-suited to creative work that draws on deep personal feeling and genuine inner warmth.`,

  sr_venus_conjunct_natal_mercury: `The solar return Venus conjunct the natal Mercury activates the natal chart's communicative and intellectual principle with the year's relational warmth and aesthetic sensibility. The year tends to bring a quality of genuine communicative grace and aesthetic intelligence — the domain that natal Mercury governs is engaged with more warmth, more genuine relational attunement, and more natural aesthetic sensibility than in other years. Writing and intellectual work benefit from a quality of genuine elegance and warmth, and the year is well-suited to any communicative project that benefits from the capacity to make ideas both clear and genuinely beautiful.`,

  sr_venus_conjunct_natal_venus: `The solar return Venus conjunct the natal Venus activates the natal chart's relational and aesthetic principle with its own most direct and most natural energy. The year tends to bring a quality of exceptional personal warmth, aesthetic vitality, and genuine pleasure in the most essentially Venusian dimensions of the life — the natal Venus's house and sign describe the domain in which this warmth and beauty are most naturally and most productively expressed, and the year supports relational and creative work in that domain with a quality of natural grace and genuine personal investment. The year is well-suited to significant romantic developments, creative projects, and the genuine enjoyment of what is most beautiful and most sustaining.`,

  sr_venus_conjunct_natal_mars: `The solar return Venus conjunct the natal Mars activates the natal chart's drive and physical vitality with the year's relational warmth and aesthetic sensibility. The year tends to bring a quality of genuine romantic and creative vitality — the desire for connection and beauty is fused with the natal Mars's drive and physical energy in ways that produce genuine passionate engagement with both relationships and creative work. Romantic life is more energised and more genuinely alive than in more passive years, and the year rewards those who act on genuine attraction and genuine creative inspiration with enough confidence and warmth to follow through.`,

  sr_venus_conjunct_natal_jupiter: `The solar return Venus conjunct the natal Jupiter activates the natal chart's principle of expansion and genuine good fortune with the year's relational warmth and aesthetic sensibility. The year tends to bring a quality of genuine abundance and expansive warmth to the domain that natal Jupiter governs — relationships, creative work, and the capacity for genuine pleasure are all more naturally generous and more genuinely rewarding in that domain than in other years. The year is well-suited to significant romantic and creative developments, and tends to attract genuinely good things and genuinely good people with a quality of easy natural goodwill.`,

  sr_venus_conjunct_natal_saturn: `The solar return Venus conjunct the natal Saturn activates the natal chart's principle of discipline and honest limitation with the year's relational warmth and aesthetic sensibility. The year tends to bring a quality of serious relational and creative engagement to the domain that natal Saturn governs — love and beauty must be earned rather than simply felt, and the most significant relationships of the year carry a quality of genuine weight and honest obligation. What is built in relationships and creative work under this contact tends to be more genuinely solid and more lastingly real than what comes more easily — the warmth Venus brings to Saturn's domain is both more genuinely needed and more genuinely productive than Venus's warmth in less demanding territory.`,

  sr_venus_conjunct_natal_uranus: `The solar return Venus conjunct the natal Uranus activates the natal chart's principle of liberation and original disruption with the year's relational warmth and aesthetic sensibility. The year tends to bring sudden, unexpected, and sometimes genuinely transformative developments in the relational and creative domains that natal Uranus governs — attractions arrive unexpectedly, aesthetic preferences shift with a quality of electric originality, and the established patterns of connection and creative expression in that domain are disrupted by the impulse toward something more authentic and more genuinely alive. The year is well-suited to new and unconventional connections and to creative work that genuinely departs from the established.`,

  sr_venus_conjunct_natal_neptune: `The solar return Venus conjunct the natal Neptune activates the natal chart's principle of spiritual sensitivity and creative imagination with the year's relational warmth and aesthetic sensibility. The year tends to bring a quality of exceptional beauty, romantic idealism, and inspired creative sensitivity to the domain that natal Neptune governs — love and aesthetic experience in that domain are more genuinely enchanting and more genuinely susceptible to the beautiful self-deception that Neptune always introduces. Creative work of genuine emotional and spiritual depth is powerfully supported. The risk is the idealisation that Venus in contact with Neptune consistently produces — seeing what is wished for rather than what is actually present.`,

  sr_venus_conjunct_natal_pluto: `The solar return Venus conjunct the natal Pluto activates the natal chart's principle of transformation and compulsive depth with the year's relational warmth and aesthetic sensibility. The year tends to bring a quality of intense and sometimes overwhelming relational and creative depth to the domain that natal Pluto governs — love and beauty in that domain are experienced with more genuine force and more transformative consequence than in other years. Significant relationships carry more genuine weight and more irreversible impact, and creative work benefits from the willingness to engage with what is genuinely dark and genuinely true rather than what is merely aesthetically pleasant.`,

  // SR MARS CONJUNCT NATAL PLANETS
  sr_mars_conjunct_natal_sun: `The solar return Mars conjunct the natal Sun activates the most central principle of the natal chart with the year's drive, assertiveness, and physical vitality. The year tends to bring a quality of genuine personal force and decisive initiative to the most essentially central dimension of who you are — identity is expressed through action, through competition, and through the willingness to pursue what is wanted with directness and genuine physical energy. The year rewards personal courage and decisive action, and tends to punish hesitation and excessive diplomatic management of what would benefit from straightforward assertion.`,

  sr_mars_conjunct_natal_moon: `The solar return Mars conjunct the natal Moon activates the natal chart's deepest emotional foundations with the year's drive, assertiveness, and physical energy. The year tends to bring emotional life into the territory of genuine action and passionate engagement — feelings that have been held in check by caution or diplomacy surface with more urgency and more genuine force than in other years. Emotional reactivity is heightened, and the line between genuine passionate engagement and impulsive emotional assertion is more difficult to maintain in the domain that natal Moon governs. The year is most productive when this emotional force is directed toward what is genuinely worth fighting for.`,

  sr_mars_conjunct_natal_mercury: `The solar return Mars conjunct the natal Mercury activates the natal chart's communicative and intellectual principle with the year's drive and assertive energy. The year tends to bring a quality of sharp, forceful intellectual engagement to the domain that natal Mercury governs — debates, negotiations, and the direct communication of what you actually think are more central and more genuinely alive than in other years. The impulse to defend a position or challenge opposing views with genuine conviction and genuine force is readily available, and the year rewards intellectual courage and honest assertion in the domain where natal Mercury operates.`,

  sr_mars_conjunct_natal_venus: `The solar return Mars conjunct the natal Venus activates the natal chart's relational warmth and aesthetic sensibility with the year's drive and physical vitality. The year tends to bring a quality of genuine passionate engagement to the relational and creative domains that natal Venus governs — the desire for connection and beauty is energised by the drive to pursue and act on what is genuinely wanted, producing a more alive and more actively pursued quality of romantic and creative engagement. The year rewards those who act on genuine attraction and genuine creative inspiration with enough confidence to follow through without excessive hedging.`,

  sr_mars_conjunct_natal_mars: `The solar return Mars conjunct the natal Mars activates the natal chart's drive and physical vitality with its own most direct and most natural energy. The year tends to bring a quality of exceptional personal energy and assertive confidence to the domain that natal Mars governs — physical vitality is heightened, competitive situations tend to favour genuine decisive engagement, and the impulse to pursue what is wanted with directness and force is more fully available than in other years. The year strongly rewards those who direct this exceptional energy toward genuinely worthwhile goals with enough self-awareness to avoid the impulsiveness that Mars in contact with itself can produce.`,

  sr_mars_conjunct_natal_jupiter: `The solar return Mars conjunct the natal Jupiter activates the natal chart's principle of expansion and genuine opportunity with the year's drive, assertiveness, and physical vitality. The year tends to bring a quality of confident, energised pursuit of genuine opportunity in the domain that natal Jupiter governs — ambition is bolder, action is more decisive, and the sense of genuine possibility is supported by more genuine physical energy and competitive confidence than in other years. The year rewards decisive engagement with the opportunities natal Jupiter describes, though the risk of overextension through overconfident action remains.`,

  sr_mars_conjunct_natal_saturn: `The solar return Mars conjunct the natal Saturn activates the natal chart's principle of discipline and honest limitation with the year's drive and assertive energy — a combination that is both genuinely productive and genuinely demanding. The year tends to bring the full force of personal initiative into the territory that natal Saturn governs with a quality of disciplined, strategic patience that neither planet achieves as effectively alone. Action is slowed by Saturn's demands for genuine accountability, but what is accomplished through that disciplined engagement tends to be more genuinely solid and more lastingly earned than what comes more easily in other years.`,

  sr_mars_conjunct_natal_uranus: `The solar return Mars conjunct the natal Uranus activates the natal chart's principle of liberation and disruptive originality with the year's drive and physical energy — a combination that is both exceptionally alive and genuinely unpredictable. The year tends to bring sudden, decisive, and sometimes explosive action in the domain that natal Uranus governs — the impulse to break free and to act on what is most authentically wanted in that domain is at its most urgent and most unstoppable. The year strongly rewards genuine decisive action toward authentic liberation, while requiring genuine care about where the considerable energy of this contact is actually directed.`,

  sr_mars_conjunct_natal_neptune: `The solar return Mars conjunct the natal Neptune activates the natal chart's principle of spiritual sensitivity and creative imagination with the year's drive and physical energy. The year tends to bring the full force of personal initiative into the domain that natal Neptune governs with a quality of inspired motivation that is most effective when the direction is genuinely aligned with inner calling. Creative, healing, and spiritually motivated action in that domain are powerfully supported, and the year rewards those who direct genuine personal energy toward what is most genuinely meaningful in the territory natal Neptune describes.`,

  sr_mars_conjunct_natal_pluto: `The solar return Mars conjunct the natal Pluto activates the natal chart's principle of transformation and compulsive depth with the year's drive and physical vitality — one of the most intensely powerful contacts in a solar return. The year tends to bring a quality of focused, driven, and sometimes ruthless personal force to the domain that natal Pluto governs — what has been avoided or managed from a safe distance in that domain may suddenly require direct and fully engaged confrontation. The year rewards genuine strategic courage and honest values-based action, and demands honest attention to whether the means being used are genuinely justified by the ends being pursued.`,

  // SR JUPITER CONJUNCT NATAL PLANETS
  sr_jupiter_conjunct_natal_sun: `The solar return Jupiter conjunct the natal Sun activates the most central principle of the natal chart with the year's expansive confidence and genuine good fortune. The year tends to bring a quality of genuine personal enlargement and optimistic forward momentum to the most essentially central dimension of who you are — identity is expressed with more confidence, more breadth, and more genuine sense of personal possibility than in other years. Personal initiatives undertaken with genuine commitment are strongly supported, and the year tends to deliver genuine rewards to those who act on Jupiter's expanded sense of what they are capable of with honest follow-through.`,

  sr_jupiter_conjunct_natal_moon: `The solar return Jupiter conjunct the natal Moon activates the natal chart's deepest emotional foundations with the year's expansive warmth and genuine good fortune. The year tends to bring a quality of genuine emotional abundance and generous warmth to the domains of home, family, and inner security that natal Moon describes. Family relationships tend to be more harmonious and more genuinely nourishing, domestic circumstances may expand or improve, and the emotional life has an overall quality of genuine spaciousness and natural goodwill. The year supports the emotional willingness to reach beyond what is already established in the domain natal Moon governs.`,

  sr_jupiter_conjunct_natal_mercury: `The solar return Jupiter conjunct the natal Mercury activates the natal chart's communicative and intellectual principle with the year's expansive confidence and philosophical breadth. The year tends to bring a quality of genuine intellectual expansiveness and communicative ambition to the domain that natal Mercury governs — ideas are pursued with more breadth, writing and publishing projects benefit from a genuine sense of larger significance, and the willingness to communicate on a genuinely ambitious scale is more naturally available than in other years. The year rewards intellectual confidence and the genuine reach toward what matters most in the domain natal Mercury describes.`,

  sr_jupiter_conjunct_natal_venus: `The solar return Jupiter conjunct the natal Venus activates the natal chart's relational warmth and aesthetic sensibility with the year's expansive confidence and genuine good fortune. The year tends to bring a quality of exceptional personal warmth, relational abundance, and genuine good fortune in the creative and relational domains that natal Venus governs. Significant romantic and creative developments are well-supported, and the year tends to attract genuinely good things and genuinely good people to the domain that natal Venus describes with a quality of easy natural generosity and genuine expansive warmth.`,

  sr_jupiter_conjunct_natal_mars: `The solar return Jupiter conjunct the natal Mars activates the natal chart's drive and physical vitality with the year's expansive confidence and genuine good fortune. The year tends to bring a quality of exceptional confident energy and ambitious forward momentum to the domain that natal Mars governs — physical vitality is strong, the sense of genuine possibility is enlarged, and the year rewards decisive action with genuine results that more timid or more constrained years cannot approach. The risk of overextension remains, but the combination of Jupiter's confidence and natal Mars's drive is among the most productive in a solar return.`,

  sr_jupiter_conjunct_natal_jupiter: `The solar return Jupiter conjunct the natal Jupiter — which occurs approximately every 12 years — marks a year of genuine personal renewal and expansive forward momentum in the domain that natal Jupiter governs. The year tends to bring a quality of genuine optimistic confidence and enlarged personal possibility to the most naturally fortunate and most philosophically significant dimension of the natal chart. Significant opportunities in the domain natal Jupiter describes are available, and the year strongly rewards those who act on them with genuine commitment and genuine follow-through rather than simply enjoying the expanded sense of possibility.`,

  sr_jupiter_conjunct_natal_saturn: `The solar return Jupiter conjunct the natal Saturn activates the natal chart's principle of discipline and honest limitation with the year's expansive confidence and genuine good fortune. The year tends to bring a quality of genuine disciplined ambition — Jupiter's confidence and Saturn's honest structural demands cooperate in the domain that natal Saturn governs in ways that allow genuine progress without the overextension that Jupiter alone might produce. The year supports the patient, disciplined pursuit of genuinely significant goals in the domain natal Saturn describes with more confidence and more natural forward momentum than Saturn alone typically provides.`,

  sr_jupiter_conjunct_natal_uranus: `The solar return Jupiter conjunct the natal Uranus activates the natal chart's principle of liberation and original disruption with the year's expansive confidence and genuine good fortune. The year tends to bring sudden, unexpected, and genuinely fortunate developments in the domain that natal Uranus governs — breakthroughs, unexpected opportunities, and the sudden positive resolution of what has been constrained are all characteristic. The year rewards genuine openness to what is genuinely new and genuinely liberating in the domain natal Uranus describes, and tends to deliver the kind of sudden positive development that more cautious years cannot produce.`,

  sr_jupiter_conjunct_natal_neptune: `The solar return Jupiter conjunct the natal Neptune activates the natal chart's principle of spiritual sensitivity and creative imagination with the year's expansive confidence and genuine good fortune. The year tends to bring a quality of genuinely inspired expansiveness and spiritual abundance to the domain that natal Neptune governs — creative, spiritual, and compassionate work in that domain is both more inspired and more generously supported than in other years. The risk is the inflation of inspiration beyond what honest practical engagement can support — the year is most productive when the genuine spiritual and creative expansiveness of this contact is grounded in enough honest structure to give it actual form.`,

  sr_jupiter_conjunct_natal_pluto: `The solar return Jupiter conjunct the natal Pluto activates the natal chart's principle of transformation and compulsive depth with the year's expansive confidence and genuine good fortune. The year tends to bring a quality of ambitious, sometimes driven forward momentum to the most fundamentally transformative dimension of the natal chart — the domain that natal Pluto governs is engaged with more confidence, more expansive ambition, and more genuine sense of transformative possibility than in other years. The year rewards those who pursue significant and lasting transformation in that domain with genuine commitment and honest values, and tends to deliver genuine and lasting results to those willing to go all the way down.`,

  // SR SATURN CONJUNCT NATAL PLANETS
  sr_saturn_conjunct_natal_sun: `The solar return Saturn conjunct the natal Sun activates the most central principle of the natal chart with the year's full disciplinary weight and honest demand for genuine accountability. The year tends to bring a quality of serious personal reckoning to the most essentially central dimension of who you are — the gap between who you intend to be and who you are actually being is brought into the full light of Saturn's honest scrutiny. The year is not designed for comfort or ease, but for the kind of genuine maturation that only Saturn's honest demand for substance over performance reliably produces. What is built through this year's honest engagement with what Saturn asks tends to be among the most lastingly real personal achievements of the decade.`,

  sr_saturn_conjunct_natal_moon: `The solar return Saturn conjunct the natal Moon activates the natal chart's deepest emotional foundations with the year's full disciplinary weight and honest demand for genuine self-sufficiency. The year tends to bring a quality of emotional austerity and genuine personal accountability to the domain that natal Moon governs — emotional needs may feel more constrained and less easily met, and the question of where genuine emotional security actually comes from rather than where it has been conveniently assumed to come from is brought into honest focus. The year tends to produce genuine emotional maturity in those willing to engage honestly with what it is actually asking.`,

  sr_saturn_conjunct_natal_mercury: `The solar return Saturn conjunct the natal Mercury activates the natal chart's communicative and intellectual principle with the year's full disciplinary demand for rigour, precision, and honest self-assessment. The year tends to bring intellectual and communicative work in the domain that natal Mercury governs to a higher standard than other years require — writing proceeds more slowly, the critical faculty is more active and more demanding, and what is produced tends to be more genuinely solid precisely because it has been subjected to Saturn's honest scrutiny. Long-term intellectual projects benefit particularly from the discipline this contact provides.`,

  sr_saturn_conjunct_natal_venus: `The solar return Saturn conjunct the natal Venus activates the natal chart's relational warmth and aesthetic sensibility with the year's full disciplinary weight and honest demand for genuine substance over comfortable illusion. The year tends to bring a quality of serious relational and creative assessment to the domain that natal Venus governs — what is genuinely worth sustaining and what has been maintained through habit or comfort rather than genuine mutual value are brought into honest focus. What survives Saturn's honest scrutiny in the relational and creative domain tends to be more genuinely solid and more lastingly real than what is not subjected to it.`,

  sr_saturn_conjunct_natal_mars: `The solar return Saturn conjunct the natal Mars activates the natal chart's drive and physical vitality with the year's full disciplinary weight and honest demand for genuine accountability in action. The year tends to bring personal initiative in the domain that natal Mars governs to a higher standard of genuine strategic discipline — action is slowed, frustrated, and subjected to a quality of honest scrutiny that can feel genuinely limiting but that ultimately produces more genuinely effective and more lastingly consequential action than Mars alone typically achieves. The year rewards patient, strategically disciplined effort over force and impulsiveness.`,

  sr_saturn_conjunct_natal_jupiter: `The solar return Saturn conjunct the natal Jupiter activates the natal chart's principle of expansion and genuine good fortune with the year's full disciplinary weight and honest demand for genuine structural consolidation. The year tends to bring a quality of disciplined ambition to the domain that natal Jupiter governs — the expansive opportunities that natal Jupiter describes are available but require genuine sustained effort and honest structural planning rather than simply optimistic confidence to realise. The year rewards those who combine Jupiter's genuine vision with Saturn's honest insistence on building what will actually last.`,

  sr_saturn_conjunct_natal_saturn: `The solar return Saturn conjunct the natal Saturn — which occurs approximately every 28-30 years and constitutes the Saturn return — marks a year of fundamental life reckoning in the domain that natal Saturn governs. The first Saturn return, around age 29-30, marks the transition from youth to genuine adulthood; the second, around 58-60, marks a corresponding transition into the next major life phase. The year brings a concentrated demand for genuine accountability, honest self-assessment, and the willingness to build the life on what is most genuinely solid and most genuinely worth building — stripping away what was never truly authentic and establishing what will actually sustain the decades that follow.`,

  sr_saturn_conjunct_natal_uranus: `The solar return Saturn conjunct the natal Uranus activates the natal chart's principle of liberation and disruptive originality with the year's full disciplinary weight and honest structural demand. The year tends to bring the question of genuine freedom and authentic selfhood in the domain that natal Uranus governs into the territory of genuine practical accountability — what liberation actually requires in terms of structural rebuilding, rather than simply the disruption of what is established, is brought into honest focus. The year rewards those who pursue genuine liberation with enough structural discipline to give what is being freed an authentic and sustainable form.`,

  sr_saturn_conjunct_natal_neptune: `The solar return Saturn conjunct the natal Neptune activates the natal chart's principle of spiritual sensitivity and creative imagination with the year's full disciplinary demand for honest practical grounding. The year tends to bring the most inspirational and most evasive dimensions of the life into the territory of genuine honest accountability — spiritual and creative aspirations in the domain that natal Neptune governs are subjected to Saturn's honest question of what is actually achievable and actually real. The year is most productive when genuine spiritual and creative vision is paired with enough structural discipline to give it actual form rather than remaining permanently aspirational.`,

  sr_saturn_conjunct_natal_pluto: `The solar return Saturn conjunct the natal Pluto activates the natal chart's principle of transformation and compulsive depth with the year's full disciplinary weight and honest structural demand — one of the most seriously demanding contacts in a solar return. The year tends to bring the most fundamental and most irreversible dimensions of the natal chart's transformative principle into the territory of genuine honest accountability and patient structural rebuilding. What cannot be sustained in the domain that natal Pluto governs is removed with a force that exceeds ordinary limitation, and what is being asked to be rebuilt is required to be genuinely solid in ways that the original structures were not.`,

  // SR URANUS CONJUNCT NATAL PLANETS
  sr_uranus_conjunct_natal_sun: `The solar return Uranus conjunct the natal Sun activates the most central principle of the natal chart with the year's disruptive, liberating, and authenticity-demanding energy. The year tends to bring a quality of sudden and sometimes dramatic personal awakening — who you are most essentially is disrupted, challenged, and ultimately more genuinely available than the accommodated version of yourself that other years maintain. The impulse toward radical personal authenticity is at its most urgent and most uncompromising, and the year strongly rewards those willing to release what has been performed rather than genuinely lived.`,

  sr_uranus_conjunct_natal_moon: `The solar return Uranus conjunct the natal Moon activates the natal chart's deepest emotional foundations with the year's disruptive and liberating energy. The year tends to bring sudden and unexpected disruptions to the emotional foundations and domestic circumstances that natal Moon describes — what has seemed most settled and most secure in that domain may prove less fixed than it appeared. The disruption consistently points toward a more authentic and more genuinely chosen emotional life, but the transition can feel genuinely destabilising in the short term.`,

  sr_uranus_conjunct_natal_mercury: `The solar return Uranus conjunct the natal Mercury activates the natal chart's communicative and intellectual principle with the year's disruptive originality and sudden electric insight. The year tends to bring a quality of sudden intellectual breakthrough and genuine communicative originality to the domain that natal Mercury governs — ideas arrive with an electric quality, unconventional intellectual directions become suddenly compelling, and the impulse to think and communicate in genuinely new ways is at its most alive and most productively urgent.`,

  sr_uranus_conjunct_natal_venus: `The solar return Uranus conjunct the natal Venus activates the natal chart's relational warmth and aesthetic sensibility with the year's disruptive, liberating energy. The year tends to bring sudden and unexpected developments in the relational and creative domains that natal Venus governs — new and unconventional connections may arrive suddenly, existing relationships may be subject to unexpected strain or sudden revelation, and aesthetic preferences may shift with a quality of genuine electric originality. The disruption consistently points toward more authentic and more genuinely chosen ways of loving and creating.`,

  sr_uranus_conjunct_natal_mars: `The solar return Uranus conjunct the natal Mars activates the natal chart's drive and physical vitality with the year's disruptive, liberating, and electric energy — a combination that is both exceptionally alive and genuinely unpredictable. The year tends to bring sudden, decisive, and sometimes explosive action in the domain that natal Mars governs — the drive to act and the impulse toward liberation are fused in ways that produce exceptional energy and genuine risk of impulsive consequences. The year strongly rewards genuine courage and decisive authentic action while requiring genuine care about where the considerable energy of this contact is directed.`,

  sr_uranus_conjunct_natal_jupiter: `The solar return Uranus conjunct the natal Jupiter activates the natal chart's principle of expansion and good fortune with the year's disruptive and liberating energy. The year tends to bring sudden, unexpected, and genuinely fortunate breakthroughs in the domain that natal Jupiter governs — opportunities arrive with a quality of genuine surprise and genuine forward momentum, and the year rewards those who are prepared to act on unexpected openings with genuine confidence before conditions are fully established.`,

  sr_uranus_conjunct_natal_saturn: `The solar return Uranus conjunct the natal Saturn activates the natal chart's principle of discipline and established structure with the year's disruptive and liberating energy — a genuinely productive tension between what has been built and what needs to be fundamentally revised. The year tends to bring the structures that natal Saturn describes into genuine contact with the demand for liberation and authentic change — what is genuinely load-bearing and deserves to be preserved is distinguished from what is simply familiar, and the year rewards the willingness to reform what has become too rigid without simply destroying what is genuinely necessary.`,

  sr_uranus_conjunct_natal_uranus: `The solar return Uranus conjunct the natal Uranus — which occurs at the Uranus return around age 84 — marks a year of fundamental liberation and genuine personal renewal at the most profound level of authentic selfhood. For younger people who experience SR Uranus conjunct natal Uranus through location changes rather than age, the year brings the full disruptive and liberating energy of Uranus to its own natal position — the domain that natal Uranus governs is the site of the year's most urgent and most fundamental demand for genuine authenticity and freedom.`,

  sr_uranus_conjunct_natal_neptune: `The solar return Uranus conjunct the natal Neptune activates the natal chart's principle of spiritual sensitivity and creative imagination with the year's disruptive and liberating energy. The year tends to bring sudden spiritual or creative breakthroughs in the domain that natal Neptune governs — the boundary between the conscious and unconscious is more permeable than usual, and what arrives through that permeability carries a quality of genuine electric revelation rather than the gradual dissolution that Neptune alone typically produces.`,

  sr_uranus_conjunct_natal_pluto: `The solar return Uranus conjunct the natal Pluto activates the natal chart's principle of transformation and compulsive depth with the year's disruptive and liberating energy. The year tends to bring sudden and sometimes dramatic ruptures in the most fundamental and most transformative dimension of the natal chart — what has been building beneath the surface in the domain that natal Pluto governs surfaces with a quality of sudden electric force that is both genuinely liberating and genuinely impossible to simply manage or contain.`,

  // SR NEPTUNE CONJUNCT NATAL PLANETS
  sr_neptune_conjunct_natal_sun: `The solar return Neptune conjunct the natal Sun activates the most central principle of the natal chart with the year's dissolving, idealistic, and spiritually sensitising influence. The year tends to bring a quality of genuine personal dissolution — the clear outlines of who you most essentially are become more fluid and more permeable, and the year may proceed through inspiration, compassion, and spiritual openness more than through deliberate self-directed effort. Creative and spiritual work are powerfully supported; the risk is the loss of personal direction in the beautiful but evasive territory that Neptune always inhabits.`,

  sr_neptune_conjunct_natal_moon: `The solar return Neptune conjunct the natal Moon activates the natal chart's deepest emotional foundations with the year's dissolving, spiritually sensitising influence. The year tends to bring a quality of exceptional emotional permeability and compassionate depth to the domain that natal Moon governs — the emotional boundaries between self and other, between personal feeling and the felt experience of those around you, are more permeable than usual. Spiritual practice, creative work of genuine emotional depth, and compassionate service are powerfully supported; the risk is the loss of emotional clarity and personal boundary in Neptune's dissolving field.`,

  sr_neptune_conjunct_natal_mercury: `The solar return Neptune conjunct the natal Mercury activates the natal chart's communicative and intellectual principle with the year's dissolving, imaginative, and spiritually sensitising influence. The year tends to bring a quality of inspired creative intelligence and poetic sensitivity to the domain that natal Mercury governs — the mind is more imaginative and more symbolically receptive than usual, and writing, poetry, and creative communication are genuinely inspired. The risk is the characteristic confusion of what is brilliantly imagined with what is actually, verifiably true in the domain natal Mercury describes.`,

  sr_neptune_conjunct_natal_venus: `The solar return Neptune conjunct the natal Venus activates the natal chart's relational warmth and aesthetic sensibility with the year's dissolving idealism and spiritual beauty. The year tends to bring a quality of exceptional romantic idealism and inspired creative sensitivity to the domain that natal Venus governs — love and beauty are more genuinely enchanting and more genuinely susceptible to Neptune's idealising influence than in other years. Creative work of genuine emotional and spiritual depth is powerfully supported; the risk is seeing what is wished for rather than what is actually present in the most significant relationships.`,

  sr_neptune_conjunct_natal_mars: `The solar return Neptune conjunct the natal Mars activates the natal chart's drive and physical vitality with the year's dissolving, spiritually sensitising influence. The year tends to bring a quality of inspired but sometimes diffuse and misdirected motivation to the domain that natal Mars governs — personal drive is most reliable and most genuinely effective when aligned with genuine inner calling rather than external expectation or ambition. Creative, healing, and spiritually motivated action in that domain are powerfully supported; the risk is the dissipation of genuine energy in the pursuit of goals that are more beautiful than achievable.`,

  sr_neptune_conjunct_natal_jupiter: `The solar return Neptune conjunct the natal Jupiter activates the natal chart's principle of expansion and genuine good fortune with the year's dissolving idealism and spiritual generosity. The year tends to bring a quality of genuinely inspired expansiveness and spiritual abundance to the domain that natal Jupiter governs — the aspirations and philosophical vision of that domain are more alive, more spiritually resonant, and more genuinely inspiring than in other years. The risk is the characteristic inflation of inspired vision beyond what honest practical engagement can support.`,

  sr_neptune_conjunct_natal_saturn: `The solar return Neptune conjunct the natal Saturn activates the natal chart's principle of discipline and established structure with the year's dissolving and spiritually sensitising influence. The year tends to bring a quality of genuine uncertainty and sometimes disorienting dissolution to the structures and disciplines that natal Saturn describes — what has seemed most solid and most reliably structured in that domain may prove more fluid and more revisable than it appeared. The year is most productive when genuine spiritual openness is paired with enough honest structural attention to prevent the dissolution from becoming simply destabilising.`,

  sr_neptune_conjunct_natal_uranus: `The solar return Neptune conjunct the natal Uranus activates the natal chart's principle of liberation and original disruption with the year's dissolving and spiritually sensitising influence. The year tends to bring a quality of genuinely inspired liberation and spiritual breakthrough to the domain that natal Uranus governs — the impulse toward authentic change is more spiritually informed and more genuinely open than the purely disruptive energy of Uranus alone typically produces. Creative, spiritual, and visionary dimensions of the liberation that natal Uranus describes are particularly alive and productive.`,

  sr_neptune_conjunct_natal_neptune: `The solar return Neptune conjunct the natal Neptune — which occurs at the Neptune return around age 165 and is therefore not experienced in a single lifetime — marks the theoretical completion of Neptune's full cycle. For practical purposes, SR Neptune approaching natal Neptune in later life brings a quality of profound spiritual summation and compassionate review to the most sensitive and most spiritually significant dimension of the natal chart.`,

  sr_neptune_conjunct_natal_pluto: `The solar return Neptune conjunct the natal Pluto activates the natal chart's principle of transformation and compulsive depth with the year's dissolving, spiritually sensitising influence. The year tends to bring a quality of genuinely inspired spiritual depth and compassionate engagement with what is most transformative in the natal chart — the compulsive intensity of natal Pluto's domain is softened and spiritually informed by Neptune's dissolving influence, and the year supports genuine spiritual and psychological transformation with more grace and more genuine inner openness than Pluto alone typically produces.`,

  // SR PLUTO CONJUNCT NATAL PLANETS
  sr_pluto_conjunct_natal_sun: `The solar return Pluto conjunct the natal Sun activates the most central principle of the natal chart with the year's compulsive, transformative, and stripping intensity. The year tends to bring a quality of deep and irreversible personal transformation — who you are most essentially is subjected to Pluto's unsparing scrutiny, and what has been performed rather than genuinely lived is stripped away with a force and a finality that more comfortable years do not approach. The year strongly rewards genuine personal courage and honest values-based engagement with what is most essentially being asked to change and most essentially being asked to be preserved.`,

  sr_pluto_conjunct_natal_moon: `The solar return Pluto conjunct the natal Moon activates the natal chart's deepest emotional foundations with the year's compulsive, transformative intensity. The year tends to bring deep and irreversible transformation to the emotional foundations that natal Moon describes — what has been most carefully maintained in the emotional life and domestic sphere may be subjected to Pluto's stripping force in ways that are genuinely demanding but ultimately productive of a more genuinely solid and more honestly chosen emotional foundation. Deep psychological work is both strongly supported and genuinely demanded.`,

  sr_pluto_conjunct_natal_mercury: `The solar return Pluto conjunct the natal Mercury activates the natal chart's communicative and intellectual principle with the year's compulsive, penetrating, and transformative intensity. The year tends to bring a quality of driven, investigative intellectual depth to the domain that natal Mercury governs — research, psychological insight, and the compulsive pursuit of what is most essentially true in that domain are powerfully supported and powerfully driven. Communications carry more weight and more genuine consequence than in other years, and what is thought and said in that domain tends to be said with a force and finality that requires genuine care.`,

  sr_pluto_conjunct_natal_venus: `The solar return Pluto conjunct the natal Venus activates the natal chart's relational warmth and aesthetic sensibility with the year's compulsive, transformative intensity. The year tends to bring deep and sometimes overwhelming relational and creative transformation to the domain that natal Venus governs — love and beauty in that domain are experienced with more genuine force and more irreversible consequence than in other years. Power dynamics in significant relationships require honest attention, and creative work benefits from the willingness to engage with what is genuinely dark and genuinely true rather than what is merely aesthetically comfortable.`,

  sr_pluto_conjunct_natal_mars: `The solar return Pluto conjunct the natal Mars activates the natal chart's drive and physical vitality with the year's compulsive, focused, and sometimes ruthlessly intense transformative energy. The year tends to bring a quality of exceptional, driven, and sometimes overwhelming personal force to the domain that natal Mars governs — the drive to pursue what is most essentially wanted in that domain is at its most compulsive and its most consequential, and what is pursued under this contact tends to be pursued with a depth of commitment and a willingness to go through difficulty that other years do not produce. Honest values-based direction of this exceptional energy is essential.`,

  sr_pluto_conjunct_natal_jupiter: `The solar return Pluto conjunct the natal Jupiter activates the natal chart's principle of expansion and genuine good fortune with the year's compulsive, transformative intensity. The year tends to bring a quality of driven, ambitious, and deeply motivated pursuit of significant transformation in the domain that natal Jupiter governs — the expansive opportunities that natal Jupiter describes are pursued with more genuine depth, more focused power, and more honest willingness to go all the way down than Jupiter alone typically produces. The year rewards those who pursue the most significant and most lasting transformation with genuine commitment and honest values.`,

  sr_pluto_conjunct_natal_saturn: `The solar return Pluto conjunct the natal Saturn activates the natal chart's principle of discipline and established structure with the year's compulsive, transformative, and stripping intensity. The year tends to bring the most fundamental structures and most essential disciplines of the natal chart into the territory of genuine irreversible transformation — what has been built in the domain that natal Saturn governs is subjected to Pluto's honest question of whether it is genuinely solid and genuinely worth sustaining, and what cannot honestly be answered in the affirmative is removed with a force that exceeds ordinary structural revision.`,

  sr_pluto_conjunct_natal_uranus: `The solar return Pluto conjunct the natal Uranus activates the natal chart's principle of liberation and disruptive originality with the year's compulsive, transformative intensity. The year tends to bring a quality of deep, irreversible liberation and genuinely transformative disruption to the domain that natal Uranus governs — the impulse toward authentic freedom in that domain is backed by Pluto's compulsive force and genuine transformative depth, producing a quality of liberation that is both more consequential and more lastingly real than disruption alone produces.`,

  sr_pluto_conjunct_natal_neptune: `The solar return Pluto conjunct the natal Neptune activates the natal chart's principle of spiritual sensitivity and creative imagination with the year's compulsive, transformative intensity. The year tends to bring a quality of deep and irreversible spiritual and psychological transformation to the domain that natal Neptune governs — the most idealistic, most evasive, and most spiritually sensitive dimensions of the life are subjected to Pluto's honest and unsparing scrutiny, and what survives that scrutiny tends to be more genuinely and more lastingly spiritually real than what preceded the encounter.`,

  sr_pluto_conjunct_natal_pluto: `The solar return Pluto conjunct the natal Pluto — which does not occur within a normal human lifespan given Pluto's orbital period of 248 years — marks a purely theoretical completion of Pluto's full cycle. For SR purposes, approaching this contact in advanced age brings a quality of profound summation and irreversible transformation to the most essentially transformative principle of the natal chart — the deepest reckoning with what has been most fundamentally true and most fundamentally transformative across the entire span of a life.`,
};
