// src/content/sun_in_houses.ts
// Solar Return: Sun in each of the 12 houses
// Sources: Mary Fortier Shea "Planets in Solar Returns" (3rd ed.);
// Cafe Astrology solar return series; Journeys Solar Return Report (Volguine method);
// Mary Shea website angular/succedent/cadent framework.
// NOTE: SR Sun sign never changes year to year — only the HOUSE changes.
// These texts describe the house placement only, not the sign.

export const SUN_IN_HOUSES: Record<number, string> = {

  1: `The Solar Return Sun in your first house marks this as a year fundamentally about you — your identity, your self-expression, and how you show up in the world. This is one of the most personally powerful Sun placements in the solar return, and its effects are felt immediately. You are likely to feel more energised, more visible, and more driven to assert your individual will than in other years. New personal initiatives tend to succeed now, particularly those that require you to step forward rather than work behind the scenes. Physical vitality is generally strong, and others notice your presence in a way that may surprise you. The risk of this placement is self-absorption — the first house focus can narrow your peripheral vision and make the needs of others less apparent. There may be a tendency to take personal action without fully considering the impact on those around you. This is a year to pursue your own goals with genuine conviction, but also to remain conscious of the relational cost of single-minded self-focus. Themes connected to the natal house where your Ascendant degree falls will also be highlighted throughout the year.`,

  2: `The Solar Return Sun in the second house turns your focus toward what you value, what you own, and what sustains you financially and materially. This is generally a year when money, income, and financial security occupy more of your conscious attention than usual. You may be working to establish, protect, or increase your financial base — and the drive to do so comes not just from practical necessity but from a deeper need to feel secure and grounded. Self-worth and financial worth often become intertwined under this placement, and the year may prompt important realisations about the relationship between how you value yourself and what you allow yourself to earn. New income streams are possible, particularly if you are actively developing skills or offerings that reflect your genuine values. The second house is also about what you truly value beyond money — your possessions, your talents, and your sense of what is worth protecting. Overspending on comfort and pleasure is a risk, as the second house Sun can create a desire for material ease that outpaces resources. The year works best when you invest intentionally in what will sustain you, rather than spending for short-term satisfaction.`,

  3: `The Solar Return Sun in the third house emphasises the life of the mind — communication, learning, local movement, and the exchange of ideas. This is a year when your thinking becomes the primary vehicle for your growth and expression. Your mind is active, curious, and restless, and you will want to gather information, read widely, study, and share what you are discovering. Writing, teaching, speaking, and community engagement are all natural expressions of this placement. The mental processes are central to whatever you accomplish — or fail to accomplish — in the year ahead. Organising your thoughts and learning to communicate them with clarity and precision will be among your most important tasks. Mental instability is a genuine risk when the Sun is in the third house: anxiety, scattered thinking, and even depression can arise if the mind is not directed toward meaningful study or purposeful expression. The more you channel this mental energy into real intellectual engagement — a course, a writing project, a teaching role — the more productive and stable the year tends to be. Relationships with siblings, neighbours, and those in your immediate environment take on greater significance. Short trips, local commitments, and frequent communication are all characteristic of a third house Sun year.`,

  4: `The Solar Return Sun in the fourth house draws your energy inward — toward your home, your family, your roots, and your emotional foundations. This is typically a quieter year in terms of outward ambition, but an extraordinarily important one in terms of inner development. You are being asked to attend to the private, foundational dimensions of your life: where you live, how you relate to your family of origin, what emotional security means to you, and what kind of home environment you need in order to thrive. Physical changes of residence are common with this placement, as are renovations, significant family developments, and a deepening of domestic life. If your outer life has been especially demanding in previous years, a fourth house Sun often signals a necessary contraction — a year of coming home to yourself. Psychological work, therapy, and exploration of family patterns are particularly fruitful now, as the fourth house governs the unconscious roots from which your current life grows. Do not underestimate the year because it appears to lack external momentum. The foundations you build or repair during a fourth house Sun year will support everything that follows.`,

  5: `The Solar Return Sun in the fifth house illuminates a year of creative expression, pleasure, romance, and a reconnection with what makes life genuinely enjoyable. The fifth house is the domain of the Sun's natural joy — play, creativity, love affairs, children, and the full expression of your individual personality. This is a year to create: to make art, to court or deepen romance, to invest in your hobbies, and to allow yourself to have fun without apology. The ego finds its most comfortable home in the fifth house, and you may feel more naturally confident and expressive than in other years. Romantic activity is frequently highlighted, whether through the beginning of a significant relationship or the intensification of an existing one. If you have children, they become a central focus. Speculation — creative risk-taking, entrepreneurial ventures, and even literal gambling — may feature more prominently in your decision-making. The risk of this placement is excess: the fifth house pleasure principle can lead to overindulgence, self-dramatisation, or neglect of responsibility in favour of entertainment. At its best, a fifth house Sun year is one in which you remember what it feels like to be fully alive.`,

  6: `The Solar Return Sun in the sixth house places the year's central focus on work, health, daily routines, and the practical maintenance of life. This is often a demanding year in terms of responsibility — your workload may increase significantly, and the details and discipline of everyday life take on unusual importance. Career development through steady, careful effort is well-supported, and a promotion or significant expansion of your professional duties is possible. However, this is not a year of dramatic external recognition — the sixth house rewards diligence more than spotlight. Health becomes a primary concern or focus: this is an excellent year for medical check-ups, the establishment of regular exercise habits, dietary improvement, and serious attention to wellbeing. Ignoring health matters under a sixth house Sun can lead to illness that slows the year down considerably. Relationships with colleagues and employees take on greater significance. Service — the genuine desire to be useful, to solve practical problems, and to contribute to the functioning of shared systems — is the sixth house's highest expression. If you can find satisfaction in the daily discipline of work done well, this year can be quietly productive and deeply grounding.`,

  7: `The Solar Return Sun in the seventh house shifts your focus outward — toward relationships, partnerships, and the people who mirror your own qualities back to you. This is a year in which one-to-one relationships become the primary context for your growth, your challenges, and your self-understanding. Marriage, committed partnership, significant professional collaboration, and even important adversarial relationships all fall under the seventh house domain. You may feel that your sense of purpose and identity this year depends on the quality of your closest relationships — and this can be both invigorating and demanding. The seventh house Sun often brings significant relationship milestones: engagement, marriage, formal partnerships, or — in more difficult configurations — the confrontation of relationship problems that have been too long avoided. Open enemies and public opposition may also feature. The important practice of this placement is learning that the qualities you most admire or most resent in others are often aspects of yourself that you have not yet fully integrated. The year works best when you approach your partnerships as opportunities for mutual growth rather than as mirrors for self-validation.`,

  8: `The Solar Return Sun in the eighth house marks a year of deep transformation, psychological intensity, and encounters with the less visible dimensions of life. The eighth house governs shared resources, other people's money, inheritance, taxes, debt, sexuality, and — most fundamentally — the processes of endings and regeneration. This is not typically an easy year, but it is frequently a profoundly important one. You may be dealing with joint finances, a partner's changing economic situation, estate matters, or significant debt. Sexuality and intimacy may become an area of heightened awareness or challenge. More deeply, the eighth house Sun often coincides with what astrologers call a year of transformation — the shedding of something outgrown in order to make room for a genuinely new self. Psychological investigation, therapy, and serious inner work are well-supported. You may become aware of aspects of yourself that were previously unconscious. The year can feel heavy, particularly if the Sun receives difficult aspects, but the transformation it initiates is rarely lost. Come through this year honestly and you will emerge with a deeper understanding of your own power and a clearer sense of what truly matters.`,

  9: `The Solar Return Sun in the ninth house opens a year of expansion, philosophical exploration, and the broadening of your world beyond its familiar boundaries. The ninth house governs higher education, long-distance travel, foreign cultures, religion, philosophy, publishing, and the great questions of meaning and belief. This is a year to push the boundaries of your experience — to study something that challenges your existing framework of understanding, to travel somewhere genuinely unfamiliar, or to engage seriously with questions of faith, ethics, and purpose. You may find yourself drawn to academia, writing, teaching, or broadcasting in a more public or expansive capacity than usual. Legal matters may require attention. The ninth house Sun year tends to feel optimistic and adventurous — there is a sense that the horizon is wider than it seemed before, and that growth is possible in directions you had not previously considered. The risk is philosophical overconfidence or the tendency to pursue experiences at the expense of completing existing commitments. Beliefs you have held without examination may be tested. The year is most rewarding when you approach it as a genuine student of life, open to having your thinking changed.`,

  10: `The Solar Return Sun in the tenth house places public life, career, reputation, and worldly achievement at the centre of the year ahead. This is among the most professionally potent positions of the Sun in a solar return — your ambitions are heightened, your drive for recognition is strong, and the year tends to involve significant movement in your professional life. A promotion, a public role, a change in career direction, or a notable increase in your professional visibility are all strongly associated with this placement. You are likely to be more concerned than usual with how you appear to the world, with your professional standing, and with the legacy you are building. Authority figures — employers, parents, or societal structures — play a significant role in the year's events. The tenth house Sun can bring you considerable public attention, and the quality of that attention depends heavily on the aspects the Sun receives: well-aspected, it brings recognition and advancement; under stress, it can bring public scrutiny or the exposure of difficulties. Regardless of the year's specific events, you are being called to step up into a greater degree of public responsibility and to take your professional self seriously.`,

  11: `The Solar Return Sun in the eleventh house brings friendships, social networks, group affiliations, community, and long-range goals into the year's primary focus. This is a year to cultivate meaningful connections, to work collaboratively toward shared objectives, and to articulate what you hope to build for the future. Your social world may expand considerably, bringing new people into your life through group activities, professional networks, or community involvement. A leadership role within a group or organisation is possible. The eleventh house also governs hopes and aspirations — and this is an excellent year to plant seeds for long-range goals that will not necessarily bear fruit immediately but that point toward where you genuinely want your life to go. Income from career activities and the financial rewards of your professional reputation are also eleventh house concerns, and the year may bring financial gains related to your work. The risk of this placement is over-investment in the collective at the expense of your individual needs, or a tendency to remain at the level of vision without doing the practical groundwork to realise it. The year is most productive when you combine genuine idealism about the future with concrete steps toward it.`,

  12: `The Solar Return Sun in the twelfth house signals a year of withdrawal, inner work, and the preparation that precedes a new cycle. The twelfth house is the most private and inward of all the houses, and with the Sun placed here, you may find that your usual drive for outward achievement is quieter than normal, replaced by a pull toward reflection, solitude, and the resolution of unfinished inner business. This is an important year for therapy, spiritual practice, creative work done in private, and the honest examination of what you have been carrying that no longer serves you. Institutions — hospitals, retreats, spiritual communities — may figure in the year's events. Some individuals with a twelfth house solar return Sun experience a year of significant retreat from the world, either by choice or circumstance. What is being cultivated in this year is often invisible from the outside, but it becomes the foundation for the more outwardly visible year that typically follows a twelfth house cycle. The risks include self-isolation, avoidance of necessary action, and the tendency to hide from circumstances that need to be faced. Hidden enemies or undermining forces may require careful navigation. The year is most fruitful when you treat it as the sacred preparation it is — letting go with intention, rather than simply drifting.`,
};
