// src/content/uranus_in_houses.ts
// Solar Return: Uranus in each of the 12 houses
// Sources: Mary Fortier Shea "Planets in Solar Returns" (3rd ed.) — primary;
// Cafe Astrology Solar Return series; Robert Hand "Planets in Transit";
// Liz Greene "The Outer Planets and Their Cycles"
// NOTE: Uranus's house position shows where disruption, sudden change, liberation,
// and awakening are concentrated for the year. Because Uranus moves very slowly
// (~7 years per sign), its house placement in a solar return shifts primarily
// through changes in SR location rather than sign movement. The same natal Uranus
// position can fall in very different SR houses depending on where the birthday
// is celebrated. Uranus does not destroy for its own sake — it breaks open what
// has become too rigid to grow, and its disruptions consistently point toward
// a more authentic version of the life being lived.

export const URANUS_IN_HOUSES: Record<number, string> = {

  1: `Solar Return Uranus in the first house places the year's most electric and unpredictable energy directly in your personal identity, self-expression, and physical presence. You are less predictable than usual — to others and, significantly, to yourself. The impulse toward personal freedom and authenticity is unusually strong, and compromises in how you present yourself or conduct your life that have been tolerable in other years may suddenly feel genuinely intolerable. You may change your appearance, your manner, your self-presentation, or some fundamental aspect of how you move through the world in ways that surprise people who thought they knew you. The year has a quality of aliveness and unpredictability — routines break down, the unexpected arrives, and the life that seemed settled turns out to be more fluid than it appeared. Physical energy is erratic rather than steady, with periods of high electrical charge alternating with periods of depletion. The risk is impulsive self-reinvention that mistakes disruption for growth — breaking what is working alongside what has genuinely become too restrictive. The year is most productive when you allow the genuine impulse toward authenticity to guide change, while maintaining enough self-awareness to distinguish real growth from mere restlessness.`,

  2: `Solar Return Uranus in the second house brings sudden and unpredictable disruption to your finances, material circumstances, and sense of personal value. Income may arrive in unexpected ways or from unexpected sources — freelance work, windfalls, or irregular payments replace the stable predictable income streams of other years. Financial circumstances can shift rapidly in either direction, and the general quality of this house placement is instability rather than catastrophe — but instability that requires genuine flexibility and a willingness to release attachment to material security as a fixed condition. The year asks you to find a more fluid relationship with money and possessions — to hold them less rigidly and to trust your capacity to generate what you need more than your capacity to hold onto what you have accumulated. Your sense of self-worth may also undergo sudden revision — values and self-assessments that seemed settled may be disrupted by experiences that prompt a more honest and more authentic appraisal of what you are genuinely worth and what you genuinely value. Financial planning benefits from building in more flexibility and contingency than usual. Rigid financial commitments entered into this year may prove difficult to sustain.`,

  3: `Solar Return Uranus in the third house brings sudden, erratic, and often brilliant energy to the domains of communication, intellectual life, and your immediate environment. Your thinking becomes faster, more associative, and less linear — ideas arrive in flashes, connections between apparently unrelated subjects become suddenly visible, and the mind operates with an electric quality that is genuinely productive for certain kinds of intellectual work while being less suited to sustained, methodical effort. Writing and communication have an urgency and aliveness that can be compelling; the risk is that ideas arrive faster than they can be properly developed or communicated. Technology and communications systems may behave erratically. Relationships with siblings or neighbours may be subject to sudden changes or disruptions. Short trips may be unplanned, improvised, or subject to unexpected developments. The local environment changes in ways that require adaptation. This is an excellent year for any intellectual or communicative work that benefits from creative disruption, unconventional thinking, or the willingness to follow an idea wherever it leads without predetermined destination. The year is less suited to work requiring sustained linear concentration.`,

  4: `Solar Return Uranus in the fourth house brings disruption, sudden change, and the impulse toward liberation to the domains of home, family, and psychological foundations. Domestic circumstances may change suddenly and unexpectedly — an unplanned move, significant changes to living arrangements, or disruptions to the stability of the home environment characterise this placement. Family dynamics may be subject to sudden revelations or upheavals — things that have been stable or assumed turn out to be less fixed than they appeared. A parent or family member may behave in unexpected ways, or long-standing family patterns may suddenly break open. The psychological foundations are equally subject to Uranus's disruptive energy — the inner life may feel less predictable and less stable than usual, with unexpected emotional responses, sudden shifts in mood or perspective, and a quality of inner restlessness that can be unsettling. At its best, Uranus in the fourth breaks open domestic and psychological structures that have become too rigid — living situations that no longer serve genuine growth, family patterns that have been maintained through habit rather than genuine choice, or inner narratives about the self that have become more constraining than true. The disruption of this year tends to point, eventually, toward a more authentic and more freely chosen way of living.`,

  5: `Solar Return Uranus in the fifth house brings electric, unpredictable, and liberating energy to the domains of creativity, romance, pleasure, and self-expression. Creative work is most alive when it follows sudden inspiration without excessive editing or control — this is a year for unconventional creative approaches, for experimenting with new forms and new mediums, and for following creative impulses that seem surprising or even slightly irrational. The results may be genuinely innovative. Romantic life is highlighted by Uranus's signature qualities: sudden attractions, unexpected developments, and a strong resistance to anything that feels like conventional romantic obligation. New relationships formed under Uranus in the fifth tend to be exciting, unconventional, and often short-lived — the intensity that makes them compelling is not always compatible with the sustained commitment that longer relationships require. Existing relationships may feel the strain of a partner's increased need for freedom and excitement. If you have children, they may behave in unexpected ways or require more flexibility from you. The year supports genuine creative risk-taking and the willingness to express yourself in ways that depart from what has been safe and familiar.`,

  6: `Solar Return Uranus in the sixth house brings sudden disruption and the impulse toward radical change to your work environment, daily routines, and health practices. Employment circumstances may change unexpectedly — job loss, sudden career shifts, changes in working conditions, or the disruption of professional relationships that had seemed stable. The impulse to break free from work that feels too constraining, too repetitive, or too far from your authentic values is strong, and the year may produce either voluntary or involuntary departure from situations that have not been genuinely working. Daily routines resist the regularity that Uranus finds constraining — the year does not support rigid scheduling, and attempts to maintain fixed daily structures tend to be disrupted by unexpected demands. Health may be subject to sudden and unexpected developments — erratic energy, nervous system-related symptoms, or health matters that require prompt attention. This is an excellent year for radically revising your approach to work and daily life in ways that better serve your genuine values and authentic needs, even when those revisions feel disruptive in the short term.`,

  7: `Solar Return Uranus in the seventh house brings sudden, unpredictable, and often liberating disruption to your closest relationships. Existing partnerships — both personal and professional — may be subject to unexpected developments that reveal how much the relationship has changed, or how much you have changed within it. The need for freedom and authenticity within relationships is unusually strong, and compromises in how you relate to others that have been manageable in other years may become suddenly intolerable. New relationships formed under Uranus in the seventh tend to arrive suddenly, feel electric and genuinely different from previous partnerships, and carry a quality of liberation — the sense that this person sees you differently and allows you to be more fully yourself. These relationships are not always stable, and their intensity does not always predict their longevity. Legal matters may develop in unexpected ways. Professional partnerships may be subject to sudden changes. At its best, Uranus in the seventh is a year in which your most important relationships become more honest — either through the honest acknowledgment of what has changed, or through the arrival of connections that allow a more authentic version of yourself to be seen and met.`,

  8: `Solar Return Uranus in the eighth house brings sudden, disruptive, and often revelatory energy to the domains of shared resources, transformation, intimacy, and the hidden dimensions of life. Financial matters involving other people — joint finances, inheritance, debt, insurance, or investment — may be subject to sudden and unexpected developments in either direction. Arrangements that seemed secure may change rapidly. Shared financial structures may require urgent revision. Psychological transformation is the most significant dimension of this placement — the unconscious is less predictable and less controllable than usual, and what has been hidden, suppressed, or avoided tends to surface with a quality of electric urgency. Dreams, synchronicities, and the eruption of previously unconscious material are characteristic. Intimacy requires more honesty and more genuine openness than is comfortable — the pretences and performances that are tolerable in other years become suddenly unsustainable. Research and investigation may produce sudden revelations. At its best, Uranus in the eighth is a year of genuine and lasting psychological liberation — the sudden release of patterns, attachments, and self-deceptions that have been limiting the life for longer than the year in which they finally break open.`,

  9: `Solar Return Uranus in the ninth house brings sudden disruption and the impulse toward radical intellectual and philosophical freedom to the domains of higher education, long-distance travel, publishing, and your broader belief systems. The worldview you have inhabited comfortably may be suddenly disrupted by experiences, ideas, or encounters that make previous certainties untenable. This is a year of genuine philosophical awakening — not the gradual expansion of Jupiter, but the sudden, electric realisation that what you thought you knew is less settled than it appeared. Long-distance travel may be sudden, unplanned, or involve unexpected developments. Higher education may proceed through unconventional paths rather than formal institutional structures. Publishing and significant intellectual projects benefit from the willingness to follow a genuinely unconventional argument or approach, even when it departs from what has been accepted. Legal matters may develop in unexpected ways. The risk is the adoption of radical or extreme positions — Uranus in the ninth can mistake the disruption of old beliefs for the achievement of genuine wisdom. The year is most productive when the intellectual liberation of this placement is accompanied by genuine humility about what is actually being seen and understood.`,

  10: `Solar Return Uranus in the tenth house brings sudden, unpredictable, and often significant disruption to your career, public reputation, and professional standing. Employment circumstances may change in ways that are not fully within your control — unexpected job loss, sudden career shifts, or disruptions to the professional structures that have defined your public life are all characteristic. The impulse toward professional freedom is unusually strong, and work that feels too constraining, too far from your authentic values, or too defined by others' expectations may become suddenly intolerable. The year may produce a significant and unexpected change in the direction of your professional life — one that feels disruptive in the short term but that proves, with hindsight, to have been pointing toward something more genuinely aligned with who you actually are. Public reputation may be subject to sudden and unexpected developments. Authority figures may behave in surprising ways, or the institutional structures through which your professional life has been organised may prove less stable than they appeared. At its best, Uranus in the tenth is a year of professional liberation — the breaking open of a career path that had become too narrow to contain the person you are continuing to become.`,

  11: `Solar Return Uranus in the eleventh house brings sudden, electric, and liberating energy to your social world, friendships, group involvements, and long-range aspirations. The social sphere is unusually alive and unpredictable — new people arrive suddenly and unexpectedly, bringing with them ideas, perspectives, and possibilities that feel genuinely different from your usual social world. Existing friendships may be disrupted — some that seemed stable may fall away suddenly, while others deepen through an unexpected shared experience or crisis. Group involvements and collaborative projects benefit from the willingness to try genuinely unconventional approaches and to work with people who operate differently from your established circle. Long-range aspirations are subject to sudden revision — the goals that seemed right at the beginning of the year may look very different by its end, as experiences and encounters shift your sense of what you are actually working toward. The future you had imagined is disrupted and replaced by something more authentically yours. Community involvement and collective projects carry a quality of genuine innovation and social experimentation. The year is most productive when you remain genuinely open to the unexpected arrivals — people, ideas, and possibilities — that Uranus in the eleventh consistently delivers.`,

  12: `Solar Return Uranus in the twelfth house brings sudden, disruptive, and often liberating energy to the hidden dimensions of your life — the unconscious, the private interior, the matters you have not made public, and the psychological patterns that operate largely below the threshold of conscious awareness. The unconscious is unusually active and unusually willing to surface what has been suppressed — dreams are vivid and often revelatory, synchronicities multiply, and a quality of electric significance attaches to experiences that might otherwise seem incidental. Long-standing psychological patterns, inherited beliefs about yourself and the world, and the self-limiting structures that have been operating in the background of your life are all subject to Uranus's liberating disruption. The year often involves a significant hidden development — something taking shape in private that has not yet become visible in the outer life. Institutions and hidden constraints may suddenly lose their hold. Spiritual breakthroughs are possible — sudden and genuine shifts in perspective that release what has been binding. The risk is that the disruption of this placement unfolds largely invisibly, and can produce a quality of inner restlessness or anxiety that is difficult to trace to any obvious external cause. What breaks open in the hidden dimensions of this year tends to surface and become visible in the year that follows.`,
};
