// src/content/venus_in_houses.ts
// Solar Return: Venus in each of the 12 houses
// Sources: Mary Fortier Shea "Planets in Solar Returns" (3rd ed.) — primary;
// Cafe Astrology Solar Return series; Journeys Yearly Solar Return Report
// NOTE: Venus's house position shows where love, pleasure, beauty, attraction,
// and financial ease are most active for the year. It also shows where you
// seek harmony and what brings genuine satisfaction. Check Venus's sign
// and aspects for additional texture on HOW these themes express.

export const VENUS_IN_HOUSES: Record<number, string> = {

  1: `Solar Return Venus in the first house brings a quality of charm, warmth, and personal magnetism to the year that others notice and respond to. You are more attractive in the broadest sense — more appealing, more socially at ease, and more inclined to present yourself with care and aesthetic intention. Your appearance may become more of a focus, and you may invest in how you look, dress, or carry yourself with more attention than in other years. This is one of the most socially pleasant positions of Venus in a solar return — the world tends to come toward you rather than requiring you to push outward, and relationships of all kinds are generally easier and more rewarding. New romantic connections are possible, and existing relationships benefit from a warmer and more appreciative quality in how you engage. Financial matters tied to personal presentation — anything from wardrobe investment to launching yourself professionally — are also supported. The risk is vanity or an over-reliance on charm and pleasantness at the expense of the deeper substance that sustains relationships and professional standing over time.`,

  2: `Solar Return Venus in the second house is Venus in its natural domain of money, values, and material pleasure — and the result is a year in which financial matters are generally better supported than usual, and in which the enjoyment of what you have becomes a genuine focus. Income may increase, particularly through work that involves Venus-ruled skills: art, beauty, design, relationship-building, or the creation of things that others find beautiful or pleasing. You are more attuned than usual to what you genuinely value, and you may make deliberate choices to bring more beauty, comfort, and aesthetic satisfaction into your daily life. Purchases of beautiful or meaningful objects are common in a second house Venus year. The desire for financial security and material pleasure is strong, and you are more motivated to earn in proportion to that desire. The risk is overspending in the pursuit of comfort and beauty, or placing too much emotional weight on financial security to the point where normal fluctuations feel threatening. At its best, this is a year of genuine material satisfaction and a clearer sense of what truly has worth in your life.`,

  3: `Solar Return Venus in the third house brings a pleasant and harmonious quality to your communications, your local environment, and your intellectual life for the year. Conversations are more enjoyable, your writing carries more grace and appeal, and the social fabric of your immediate neighbourhood and daily community is more rewarding than usual. This is an excellent year for any creative writing, for diplomatic communication, or for any kind of work that requires you to convey ideas in a form that others find genuinely attractive. Short trips may have a pleasurable, aesthetic, or romantic dimension. Relationships with siblings and neighbours tend to be warmer and more harmonious. If you are studying or taking a course, the experience is likely to be genuinely enjoyable rather than merely dutiful. Social media and creative online communication go particularly well. The risk is superficiality — a tendency to keep things pleasant and agreeable on the surface rather than engaging with the genuine depth or difficulty of situations. Communication that avoids necessary friction in the interest of keeping things comfortable can leave important things unsaid.`,

  4: `Solar Return Venus in the fourth house brings a pleasant and aesthetically pleasing quality to your home and domestic life for the year. You are more invested than usual in making your home beautiful, comfortable, and genuinely welcoming — and you may spend money on home improvements, furnishings, or decorating projects that bring real satisfaction. The domestic atmosphere is generally warmer and more harmonious, and family relationships benefit from a quality of ease and affection. This is a good year for entertaining at home, for creating a living space that truly reflects your taste, or for finding a new home that genuinely pleases you. Emotional security has an aesthetic dimension under Venus in the fourth — you feel more settled when your surroundings are beautiful and your domestic life is running smoothly. Real estate transactions may go well. The risk is using the comfort and beauty of home as a retreat from the world rather than as a genuine base from which to engage with it — a fourth house Venus can tip into staying pleasantly at home when the wider world requires your attention.`,

  5: `Solar Return Venus in the fifth house is one of the most naturally joyful placements in a solar return — Venus in the house of pleasure, romance, creativity, and self-expression creates a year in which these domains are genuinely lit up. Romantic activity is strongly highlighted: if you are single, this is a year in which a significant new romantic connection is more likely than usual; if you are partnered, the relationship benefits from a renewed quality of pleasure, affection, and playfulness. Creative work flows with greater ease and finds a more appreciative audience. You may produce art, music, writing, or any other creative expression that genuinely delights you and others. Social life is active and enjoyable. If you have children, your relationships with them are warmer and more rewarding. Leisure and recreation are important — this is a year to allow yourself genuine pleasure without guilt. The risks are overindulgence, frivolity, or a tendency to choose pleasure over responsibility when the two are in conflict. Speculative financial ventures require more caution than the generally optimistic fifth house Venus atmosphere might suggest.`,

  6: `Solar Return Venus in the sixth house brings a pleasant and harmonious quality to your work, daily routines, and health practices for the year. Your working environment is generally more agreeable, and relationships with colleagues tend to be warmer and more cooperative than in other years. Work itself may be more pleasurable — either because the nature of the work aligns with your aesthetic sensibilities, or because the social dimensions of your professional life are more rewarding. You may find that beauty, art, or relationship-building is more central to your professional work this year. Health-related improvements undertaken with genuine care and pleasure — rather than anxious obligation — go well: dietary changes that are genuinely enjoyable, physical practices that feel good rather than punishing. The risk is avoiding necessary work or health disciplines because Venus in the sixth prefers ease and pleasure over effort. There can also be a tendency to overeat or to indulge in physical comforts at the expense of genuine health. Service that comes from genuine care rather than obligation is the most satisfying expression of this placement.`,

  7: `Solar Return Venus in the seventh house is the classic partnership placement — relationships, both romantic and professional, are the central domain in which Venus's gifts of harmony, attraction, and genuine connection operate this year. This is one of the most supportive positions for marriage, the beginning of a committed relationship, or the deepening of an existing partnership into something more formally committed. Existing relationships generally benefit from a warmer, more affectionate, and more aesthetically pleasurable quality. Professional partnerships and collaborative ventures are well-supported, particularly those that involve beauty, creativity, or the kind of work that requires genuine rapport between the people involved. Legal matters that require negotiation tend to resolve more favourably than usual. Your ability to find common ground with others, to see their point of view, and to create mutually satisfying arrangements is enhanced. The risk is an over-accommodation of others at the expense of your own needs — Venus in the seventh can be so focused on maintaining relational harmony that it defers when it should hold its own position.`,

  8: `Solar Return Venus in the eighth house brings Venus into the domain of deep intimacy, shared resources, transformation, and the hidden dimensions of relationship. This is not the lightest Venus placement — the eighth house asks for depth rather than surface pleasantness — but it can be extraordinarily rich in terms of what it offers. Intimacy in close relationships may deepen significantly, with a quality of genuine emotional and physical connection that goes beyond what is usually available. Financial matters involving shared resources, inheritance, insurance, or a partner's income may resolve more favourably than expected. You may receive money or gifts through others. Investigations into hidden matters, research into subjects others find uncomfortable, or any kind of work that requires going beneath the surface of things is supported by Venus's presence. The risk is a tendency toward possessiveness, jealousy, or financial entanglement in close relationships. The attractive power of intensity and depth can draw you toward relationships or situations that are compelling but ultimately not healthy. Transformation through relationship — genuine, sometimes uncomfortable growth — is the deepest gift of this placement.`,

  9: `Solar Return Venus in the ninth house brings beauty, pleasure, and genuine enjoyment to the wider horizons of life — travel, higher education, philosophical exploration, and encounters with cultures and ideas beyond your familiar world. This is an excellent year for travel that is genuinely pleasurable rather than merely purposeful — journeys that feed the soul, expose you to beauty in unfamiliar forms, and leave you enriched. Study and learning carry a quality of genuine delight: you are drawn to subjects that captivate you, and the experience of learning is pleasurable rather than merely dutiful. Publishing, broadcasting, or teaching work that reaches a wide audience benefits from Venus's touch. Legal matters tend to resolve favourably. Relationships formed through travel, education, or philosophical community may be particularly meaningful. There is sometimes a romantic quality to long-distance connections or to relationships with people from different cultural backgrounds. The risk is a certain idealism about what travel, education, or philosophical exploration will deliver — the reality of any new experience eventually includes difficulty alongside beauty.`,

  10: `Solar Return Venus in the tenth house brings charm, aesthetic appeal, and relational skill into your public and professional life for the year. Your professional reputation may benefit from a quality of warmth and genuine likability, and you may find that your career advances through the quality of your relationships and your ability to create goodwill as much as through technical skill alone. Work in fields involving beauty, art, design, fashion, or anything requiring a refined aesthetic sensibility is particularly well-supported. A female mentor, employer, or influential contact may play a significant role in your professional advancement. The year may bring public recognition or a more visible profile than usual. Relationships with those in authority tend to be more harmonious and productive. Financial gains through your professional work are possible. The risk is allowing the desire for professional harmony and likability to soften your willingness to take difficult positions or make necessary decisions that might create friction. Professional advancement built entirely on charm without the substance to sustain it will eventually require correction.`,

  11: `Solar Return Venus in the eleventh house brings pleasure, warmth, and genuine connection to your social world, friendships, and group involvements for the year. Your social life is likely to be active and enjoyable — new friendships form more easily, existing ones deepen, and the groups and communities you belong to feel more rewarding and nourishing. A significant new friendship formed this year may become genuinely important in your life. Group activities, collaborative projects, and community involvement carry a quality of genuine pleasure rather than obligation. Financial gains related to your professional work or social network are possible — Venus in the eleventh can bring income through the people you know and the reputation you have built. Shared aesthetic or creative projects with friends or community groups go particularly well. The risk is a superficiality in the social connections of the year — enjoying the pleasantness of social life without investing in the depth that turns pleasant acquaintance into genuine friendship. At its best, this is a year of real social joy and the cultivation of meaningful community.`,

  12: `Solar Return Venus in the twelfth house brings love, beauty, and pleasure into the private and hidden dimensions of your life for the year. This is not a social Venus — it is an inward and somewhat solitary one, finding its greatest satisfaction in quiet, private experiences: solitary creative work, spiritual practice, time in nature, or the intimate depths of a relationship that does not require public acknowledgement. Secret or private love affairs are sometimes associated with this placement, though more commonly it simply describes a year in which your most significant emotional and aesthetic experiences happen away from the gaze of others. Creative work done in solitude — writing, painting, composing, or any art form that benefits from privacy and reflection — is well-supported. Spiritual and charitable engagement carries genuine satisfaction. The risk is a tendency to sacrifice your own desires and pleasures for others without acknowledging the cost, or to remain in relationships that are emotionally sustaining but cannot be fully lived in the open. What you love privately this year has genuine depth and meaning, even if the world does not see it.`,
};
